### ISSUE TITLE
Objects.log.util module not found

### ISSUE THREAD

**Issue by lsabi** [process-intelligence-solutions/pm4py#127]
Use case:
I would like to encode a xes log. So I import the function in my program via

`from pm4py.objects.log.util import get_log_encoded`

When I call the "function", I get the following error

> TypeError: 'module' object is not callable

I have to call

`get_log_encoded.get_log_encoded( *params* )`

in order to make it work. The imports of the __init__.py of that folder should be changed in order to import all the different functions from the files. Are there any problems with that? (I can do it as well, though I'd rather ask first, since it may be on purpose).

**Comment by fit-alessandro-berti** [comment]
Hello,

This is simply a function "get_log_encoded" contained into a "get_log_encoded" Python module. Except from the naming, that can be corrected, I do not see an issue that :)

For doing a pull request, we are estabilishing new guidelines, so in this moment do not push any pull request

**Comment by lsabi** [comment]
Don't worry, but my question is if it is the case of rewriting the init.py file so that one can directly import functions from that module without having to import the module and then call the function.

Example:

__init__.py:

`from objects.log.util.get_log_encoded import get_log_encoded`

my_file.py:

`from pm4py.objects.log.util import get_log_encoded`

`get_log_encoded( *params* ) `
