### ISSUE TITLE
apply_tree_dfg function argument "start_activity" not working well.

### ISSUE THREAD

**Issue by yctsai116** [process-intelligence-solutions/pm4py#128]
Hi,
When I'm doing inductive miner, the start activities seems not working properly.
This is an example for the problem.
I tried to play out the model and then do the inductive miner, however, I got different result.
`PlayOutL=pm4py.algo.simulation.playout.versions.basic_playout.apply_playout(net ,initial_marking)`
![ProM_PetriNet2](https://user-images.githubusercontent.com/44591001/69905119-09ee3780-13b0-11ea-9063-64feb4ded712.png)

`net, initial_marking, final_marking = pm4py.algo.discovery.inductive import factory.apply(PlayOutL)`
![Syn2_NF](https://user-images.githubusercontent.com/44591001/69905166-68b3b100-13b0-11ea-8534-db6a1bde32cb.png)
There should be a silent activity next to 'Activity B'.
Note : I can discover the correct model by ProM.

I tried to work until `apply_tree_dfg` and found it does not work properly on start_activities.
`start_activities=['Activity E', 'Activity D', 'Activity F', 'Activity B', 'Activity C', 'Activity J', 'Activity I', 'Activity K']`
`pm4py.algo.discovery.inductive.versions.dfg.imdfb.apply_tree_dfg(dfg, parameters, activities=activities, contains_empty_traces=False,start_activities=start_activities, end_activities=end_activities)`
![tree2](https://user-images.githubusercontent.com/44591001/69905399-35265600-13b3-11ea-8ea9-4f886f6944de.png)

**Comment by fit-alessandro-berti** [comment]
The problem has been resolved and  the solution will be included in the next release
