### ISSUE TITLE
SIMPLE algorithm

### ISSUE THREAD

**Issue by tomyc** [process-intelligence-solutions/pm4py#129]
Hi,
I would like to ask where I can find the SIMPLE algorithm? In version **1.25** it's not available. 
So, the import command `from pm4py.algo.discovery.simple.model.log import factory as simple_algorithm` doesn't work.

Regards,
Tom

**Comment by s-j-v-zelst** [comment]
Hi Tomyc,

The simple algorithm has been removed from the library, i.e., it was a 'pet project' from one of our engineers and has no underlying publication.
In case you require to find sound workflow nets, please resort to using the inductive miner implemented in PM4Py.

kind regards,

Sebastiaan.
