### ISSUE TITLE
Streaming Conformance

### ISSUE THREAD

**Issue by geminio-john** [process-intelligence-solutions/pm4py#130]
Feature Request:
Are there any plans to implement the streaming conformance steps described in the paper 'Online Conformance Checking Using Behavioural Patterns' and implemented in StreamConformance in ProM?
It seems to be a very efficient approach.
Thanks.

**Comment by s-j-v-zelst** [comment]
Dear Geminio,

Yes, we do plan to implement this feature (including many more stream based algorithms).
However, we do not expect to be able to do this on short notice.

kind regards,

Sebastiaan.
