### ISSUE TITLE
GraphViz temp files not cleaned up

### ISSUE THREAD

**Issue by martinpetrovaj** [process-intelligence-solutions/pm4py#133]
visualization/common/gview.py:25 calls gviz.view() with cleanup parameter left at it's default value == False. This results in accumulation of graph files in %TEMP% folder.

Suggestion: call with cleanup=True to avoid possible storage space cluttering.

**Comment by Javert899** [comment]
Dear Martin,

Thanks for signaling this issue

It will be solved in the next PM4Py release

**Comment by fit-alessandro-berti** [comment]
The solution has been implemented by means of using the cleanup=True option provided by graphviz.
Note that, this is a 'best effort' fix, i.e., the provided functionality might not clean up all temp files.
