### ISSUE TITLE
problem with setting measure for discovering dfg using performance variant 

### ISSUE THREAD

**Issue by jalaliamin** [process-intelligence-solutions/pm4py#135]
Hi

I am trying to use different measures for calculating labels for DFG graph using performance variant. However, it does not work as I set the parameters. The parameter works for e.g. maxNoOfEdgesInDiagram. 

Sample code:

`myParam={'maxNoOfEdgesInDiagram':20, 'aggregationMeasure':'max'}
`
...
`gviz = dfg_vis_factory.apply(dfg, parameters=myParam, log=log, variant="performance")
dfg_vis_factory.view(gviz)`

any hint would be appreciated.

Kind regards
Amin

**Comment by fit-alessandro-berti** [comment]
Dear Jalaliamin,

The aggregationMeasure shall be passed also to the DFG calculation factory, e.g.:

dfg = dfg_factory.apply(log, variant="performance", parameters=myParam)

**Comment by jalaliamin** [comment]
Thank you for reply.
When I set the variant="performance", I receive this error:


![error](https://user-images.githubusercontent.com/13148253/73079893-3496d100-3ec5-11ea-9fbf-ec75ce0cbde6.png)

**Comment by jalaliamin** [comment]
Thank you very much for the help. The problem is solved.
In addition to this setting, I had problem of **not** converting timezone in timestamps which raises error when computing the duration.

**Comment by jalaliamin** [comment]
I like also add a suggestion from the user perspective. If the models which are generated by setting these parameters look the same (like Disco), it is a great help when analyzing models. Since from analyst point of view, it is interesting to look at the same process but from the other (performance) view.

```
myParam={'maxNoOfEdgesInDiagram':5, 'aggregationMeasure':'max'}
dfg = dfg_factory.apply(cp.copy(log), parameters=myParam, variant="frequency")
gviz = dfg_vis_factory.apply(cp.copy(dfg), log=cp.copy(log), parameters=myParam, variant="frequency")
dfg_vis_factory.view(gviz)
```
![frequency](https://user-images.githubusercontent.com/13148253/73118236-d237e200-3f51-11ea-898f-1234b5a50174.png)

```
myParam={'maxNoOfEdgesInDiagram':5, 'aggregationMeasure':'max'}
dfg = dfg_factory.apply(cp.copy(log), parameters=myParam, variant="performance")
gviz = dfg_vis_factory.apply(cp.copy(dfg), log=cp.copy(log), parameters=myParam, variant="performance")
dfg_vis_factory.view(gviz)
```

![performance](https://user-images.githubusercontent.com/13148253/73118238-d82dc300-3f51-11ea-8d06-671e857609ea.png)

Or if it is not possible since the weight of edges are different due to different measure, it would be great if we can have a dfg with all measures calculated in it, so we can see all measures in the same view!

**Comment by fit-alessandro-berti** [comment]
Hello,

Thanks for the comments, I have inserted your requests in our system for being taken in consideration for future devleopments
