### ISSUE TITLE
Alignments some times taking forever to compute.

### ISSUE THREAD

**Issue by Monis1** [process-intelligence-solutions/pm4py#137]
from pm4py.algo.conformance.alignments import factory as align_factory

>> alignments = align_factory.apply_log(log, net, initial_marking, final_marking)
>> print(alignments)

Alignments for some data taking forever to give the answer.

**Comment by fit-alessandro-berti** [comment]
Dear Monis1,

To get alignments faster you have two ways:

For models without concurrency (e.g. Petri nets without AND constructs), the Dijkstra variant is faster. Please provide that to the alignments method:
aligned_traces = align_factory.apply(df, net, im, fm, version=align_factory.VERSION_DIJKSTRA_NO_HEURISTICS)

Or you can install the optional, non-open licensed, pm4pycvxopt (pip install -U pm4pycvxopt) and do
import pm4pycvxopt
aligned_traces = align_factory.apply(df, net, im, fm)

Hoping the answer helps
