### ISSUE TITLE
GraphViz process tree visualisation inconsistent

### ISSUE THREAD

**Issue by martinpetrovaj** [process-intelligence-solutions/pm4py#138]
I am using visualization.petrinet.factory.apply method to visualise a process tree (petri net generated using algo.discovery.alpha.factory.apply). Format is set to "svg", graphviz engine is left as default ("dot") and one additional graph attribute is applied for top-to-bottom layout (`gviz.graph_attr['rankdir'] = 'TB'`). Apply method parameter 'variant' is set to value "frequency".

The problem is that the same input (same dataset) produces visualisations with different node placements every time. So far I have been unable to track down the code which causes this non-deterministic behaviour.

This problem makes it unfeasible to use pm4py visualisations in production version of our software.

We have tried setting the graph attribute "start" to a fixed number, but to no avail (at least with dot engine, neato is impractical for our use case).

Could this behaviour be caused by pm4py code, or is it a bug in underlying GraphViz library?

**Comment by fit-alessandro-berti** [comment]
Dear Martin,

Yes we are aware that the position of nodes in some visualizations is not always the same;

we'll investigate whether a solution is possible within the current visualization.

If you are using an older version of PM4Py (<= 1.2.7), we suggest the upgrade to the newest (1.2.8 or 1.2.9) where an improved version of the Inductive Miner has been included.

Sincerely
Alessandro

**Comment by fit-alessandro-berti** [comment]
Dear Martin,

We'll release the fix in a future version of PM4Py;

If you need to fix it now, I suggest you to process the tree before the visualization with the following function:

def tree_sort(tree):
    """
    Sort a tree in such way that the order of the nodes
    in AND/XOR children is always the same.
    This is a recursive function

    Parameters
    --------------
    tree
        Process tree
    """
    tree.labels_hash_sum = 0
    for child in tree.children:
        tree_sort(child)
        tree.labels_hash_sum += child.labels_hash_sum
    if tree.label is not None:
        # this assures that among different executions, the same string gets always the same hash
        this_hash = int(hashlib.md5(tree.label.encode('utf-8')).hexdigest(), 16)
        tree.labels_hash_sum += this_hash
    if tree.operator is pt_op.Operator.PARALLEL or tree.operator is pt_op.Operator.XOR:
        tree.children = sorted(tree.children, key=lambda x: x.labels_hash_sum)

Sincerely
Alessandro
