### ISSUE TITLE
Exporting a log file into csv format

### ISSUE THREAD

**Issue by GhadaElkhawaga** [process-intelligence-solutions/pm4py#143]
HI, 
everytime I try to export an event log with csv format, I get this error...

`ValueError                                Traceback (most recent call last)
<ipython-input-22-80d6d577842a> in <module>()
      1 from pm4py.objects.log.exporter.csv import factory as csv_exporter
----> 2 csv_exporter.export('BPI_Challenge_2017.xes', 'bpic17_pm4py.csv')

3 frames
/usr/local/lib/python3.6/dist-packages/pm4py/objects/conversion/log/versions/to_dataframe.py in <listcomp>(.0)
     45     if type(log) is log_instance.EventLog:
     46         log = to_event_stream.transform_event_log_to_event_stream(log)
---> 47     transf_log = [dict(x) for x in log]
     48     df = pd.DataFrame.from_dict(transf_log)
     49 

ValueError: dictionary update sequence element #0 has length 1; 2 is required`

**Comment by fit-alessandro-berti** [comment]
Dear Ghada,

From what I understand from your description, you are trying to export the path of the XES log as a CSV file. You should first import the XES file through the pm4py.objects.log.importer.xes.factory class; then export the log object to CSV

If that is not the case, I suggest you to update to the latest release by doing: pip install -U pm4py==1.2.10
and retry :)

**Comment by GhadaElkhawaga** [comment]
Dear Alessandro,

Many thanks for your feedback...now it works well :)
