### ISSUE TITLE
Random fitness/precision result from token replay

### ISSUE THREAD

**Issue by fmannhardt** [process-intelligence-solutions/pm4py#148]
We have got a bug report over at the R pm4py binding that the token replay (which we have as a default -- which should be changed I guess) gives back random results for the same model and event log when called multiple times. You can find the original bug report here:
https://github.com/bupaverse/pm4py/issues/6

Is this expected behaviour? If not I can try to make the test model and log available.

**Comment by fit-alessandro-berti** [comment]
Dear Felix,

We are aware of some problems if the model contains duplicate transitions (the method cannot handle duplicate transitions properly; hence in the last release we introduced a new version of the token-based replay based on a backwards state space exploration)

However, if the model does not contain duplicate transitions, then it's weird. If you can please provide us the test model and log

Sincerely
Alessandro

**Comment by fmannhardt** [comment]
This is the model:

![image](https://user-images.githubusercontent.com/3202998/77071217-f06b0d00-69eb-11ea-98d0-442f50a35941.png)

But, I just checked it directly with PM4Py and the token replay gives consistent results. It does not find that the model perfectly fits all traces (alignment-based fitness is 1.0) but it gives always the same fitness of 0.96905...

I will investigate what goes wrong in the automatic conversion from R.
