### ISSUE TITLE
interval event log diff to log

### ISSUE THREAD

**Issue by mariagkotsopoulou** [process-intelligence-solutions/pm4py#151]
I am running pm4py version 1.2.11  in anaconda on macos. I am using BPI Challenge 2012 event log and to get estimates of the activity durations the log is transformed into an "interval" event log. 

`from pm4py.objects.log.util import interval_lifecycle
enriched_log = interval_lifecycle.assign_lead_cycle_time(log)`

Even if the number of traces is the same between the log and the enriched_log, the same does not apply for the events.  Not all events persist across the "interval" event log. So consequently, some activities are missing. Like for example

`from pm4py.algo.filtering.log.attributes import attributes_filter
attributes_filter.apply_events(enriched_log, "W_Wijzigen contractgegevens", 
                                parameters={constants.PARAMETER_CONSTANT_ATTRIBUTE_KEY: "concept:name"})`

Changing the parameters["worktiming"] and parameters["weekends"] has no impact in the result
`enriched_log = interval_lifecycle.assign_lead_cycle_time(log,
                                                         parameters={"worktiming":[0,23],"weekends":[0]})`

Could you perhaps help me understand why this is occurring?
Thank you !

**Comment by fit-alessandro-berti** [comment]
Dear Maria,
It is expected that the "interval" log contains less events than the "normal" log.
Indeed, events of the same activity instance are grouped together, and the timestamps of the event become two: one start timestamp and one completion timestamp

Events of activity instances that have only completion timestamps are left unchanged
