### ISSUE TITLE
Request for information: C++ compiler requirements under Windows

### ISSUE THREAD

**Issue by smillies** [process-intelligence-solutions/pm4py#153]
Hello there, 
I am new to pm4py. I work under Windows, and due to company policies I do not understand am not allowed to install MS Visual Studio CE, and can't get an official license for the full version at the moment. Two questions:
- Can I uninstall Visual Studio CE after I have installed pm4py?
- If not, and a C/C++ compiler is needed also at runtime, can pm4py work with the one I have now installed under Cygwin (x86_64-pc-cygwin, gcc version 9.2.0)?

**Comment by fit-alessandro-berti** [comment]
Dear smillies,

The question is complicated; it depends on your operating system and the version of Python that you install. Moreover, it depends on the fact that you use classic Python or Miniconda/Anaconda (the compiler for the two versions is different).

My suggestion is to try to install Anaconda Python 3.7 and then do "pip install pm4py".
Possibly the installation succeeds without requiring any VS C++ installation (that is strictly required below Python 3.7). Possibly the installation will fail, but then you will get some error message and then we can search for some workaround

In any case, we provide a .ZIP of a Miniconda 3.7 installation containing all the dependencies. That can be found at the address https://drive.google.com/open?id=1C5Gno-vSQ_9dQPRC-APKAsnDnRgrmMc0 

Have a nice day

Sincerely
Alessandro

**Comment by smillies** [comment]
Thanks for the help with the Minikonda archive!
