### ISSUE TITLE
sample_log does not behave as expected

### ISSUE THREAD

**Issue by ainnoot** [process-intelligence-solutions/pm4py#156]
In the [sample_log](https://github.com/pm4py/pm4py-source/blob/b5d2a76a8ca6615aa9e67dbd87368fd6c16a5b6e/pm4py/objects/log/util/sampling.py#L54) function there's no check to avoid that a trace gets sampled multiple times. When it does happen `new_log`  contains less traces than intended because the `set` data structure stores unique elements.

**Comment by fit-alessandro-berti** [comment]
Dear ainnoot,

We were able to reproduce your problem. The issue will be resolved in the next version of PM4Py.

Thanks for signaling
Alessandro
