### ISSUE TITLE
Create new Trace instance

### ISSUE THREAD

**Issue by ghost** [process-intelligence-solutions/pm4py#157]
Hi, i wonder how one can create a new Trace instance from, e.g. a list of Events extracted from a EventLog instance. I think its a easy question but I cannot find any hints neither in the documentation nor in the log.py source.

**Comment by fit-alessandro-berti** [comment]
Dear jacksbrajin,

You could look at the following example:

from pm4py.objects.log.log import Event, Trace

ev1 = Event({"concept:name": "A"})
ev2 = Event({"concept:name": "B"})
trace = Trace([ev1, ev2])
print(trace)

The trace is created from a list of events
