### ISSUE TITLE
Shallow copy of Trace objects does not behave as expected

### ISSUE THREAD

**Issue by marcopegoraro** [process-intelligence-solutions/pm4py#158]
Hello,
the shallow copy operation of Trace objects behaves like reference pointing (assignation), rather than a copy.
The following snippet

`from pm4py.objects.log.log import Trace, Event  
from copy import copy  
a = Trace()  
a.append(Event({'concept:name': 'A'}))  
b = copy(a)  
b.append(Event({'concept:name': 'B'}))  
print(a)  
print(b)`

prints the following:

`{'attributes': {}, 'events': [{'concept:name': 'A'}, '..', {'concept:name': 'B'}]}
{'attributes': {}, 'events': [{'concept:name': 'A'}, '..', {'concept:name': 'B'}]}`

**Comment by fit-alessandro-berti** [comment]
Hello Marco,

Thanks for signaling this issue. The problem has been resolved through a definition of a custom __copy__ function for Event, Trace, EventStream and EventLog object

The fix will be released in the next version of PM4Py

Sincerely
Alessandro
