### ISSUE TITLE
Documentation highlights a code snippet that doesn't work

### ISSUE THREAD

**Issue by AdamBanham** [process-intelligence-solutions/pm4py#159]
On version : '1.2.11'

Looking at the documentation at https://pm4py.fit.fraunhofer.de/documentation#importing.

To export an Eventlog object into a xes file it suggests 
`from pm4py.objects.log.exporter.xes import exporter as xes_exporter`
but doing so triggers the following error
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'exporter' from 'pm4py.objects.log.exporter.xes' (C:\Users\adam\AppData\Local\Programs\Python\Python38\lib\site-packages\pm4py\objects\log\exporter\xes\__init__.py)`

In order to import the xes_exporter, I had to change the import line to the following in order to get the exporter
`from pm4py.objects.log.exporter.xes import factory as xes_exporter`

**Comment by fit-alessandro-berti** [comment]
Dear Adam,

We recently released a new version of PM4Py, the 1.3.0, with several updates. The current documentation page covers that version

As thing stands, you have two possibilities:
A) you keep your current version as 1.2.11, and you refer to the documentation of PM4Py 1.2.x that is located at the address https://pm4py.fit.fraunhofer.de/documentation/1.2 
B) you update PM4Py to 1.3.0, with the command pip install -U pm4py. This fully supports the commands that are actually in the documentation

Thanks and have a nice day
