### ISSUE TITLE
AttributeError while visualizing reachability graph

### ISSUE THREAD

**Issue by coldembrace** [process-intelligence-solutions/pm4py#161]
Thanks for the great python lib!
I'm trying to visualize previously created reachability graph and getting the following error: 
`AttributeError: 'Transition' object has no attribute 'label'`
The corresponding code:
```
net = PetriNet("new_petri_net")
...
net.places.add(p)
...
net.transitions.add(t)
...
utils.add_arc_from_to(p, t, net)
...
reachab_graph = construct_reachability_graph(net, initial_marking)
viz = pn_visualizer.apply(reachab_graph, parameters={"show_labels": True, "show_names": False})
pn_visualizer.view(viz)
```
What I'm doing wrong here? Thanks in advance.

P.S. by the way, I wasn't able to find `construct_reachability_graph` method in the new docs (https://pm4py.fit.fraunhofer.de/documentation), strange...

**Comment by fit-alessandro-berti** [comment]
Dear coldembrace

The reachability graph that you obtain from a Petri net is a transition system; hence it should be managed through the transition system visualizer (pm4py.visualization.transition_system)

The documentation page does not still document all the available features in PM4Py; for that reason you cannot find the description of the method "construct_reachability_graph"

Thanks and have a nice day
