### ISSUE TITLE
hi，Can PM4PY solve Parallel processes/Subprocesses issues

### ISSUE THREAD

**Issue by yanqinghao** [process-intelligence-solutions/pm4py#162]
If I get data like this：
![image](https://user-images.githubusercontent.com/31135695/84502976-ec4d4380-aceb-11ea-8a47-8a118458c969.png)
can I use pm4py generate graph like this：
![image](https://user-images.githubusercontent.com/31135695/84503042-0b4bd580-acec-11ea-989c-c986d53520c0.png)
hope someone can help me， thanks！

**Comment by fit-alessandro-berti** [comment]
Dear yanqinghao,

Actually this is a custom feature of Celonis. It is also not very clear what is the real support for this.

Consider that the graph that you see has been extracted for a single process execution. Plus the fact that the termination condition for the subprocesses is always the end node of the process.

To discover concurrency, on an entire log and not a single process execution, you can use algorithms such as the Alpha Miner, Inductive Miner, Heuristics Miner

Thanks
Alessandro

**Comment by fit-alessandro-berti** [comment]
By the way,

If you have a dataset and custom visualization needs, we can have a chat on the best way to represent that type of event log.

Let me know

Thanks
Alessandro

**Comment by yanqinghao** [comment]
> By the way,
> 
> If you have a dataset and custom visualization needs, we can have a chat on the best way to represent that type of event log.
> 
> Let me know
> 
> Thanks
> Alessandro

thank you! if I have a dataset in the future, I will contact you again.

Thanks
YanQinghao
