### ISSUE TITLE
Obtain Traces for specific variants

### ISSUE THREAD

**Issue by danielkalfas** [process-intelligence-solutions/pm4py#167]
Hello,

i am currently trying to obtain all variants of .xes document and do conformance checking later for each variant. I am only possible to obtain the variants but i dont know how to get all the traces for each variant. This is how far i came. 
I am using the .xes file from your test datasets.

```
log = xes_importer.apply("receipt.xes")
from pm4py.statistics.traces.log import case_statistics
variants_count = case_statistics.get_variant_statistics(log)
variants_count = sorted(variants_count, key=lambda x: x['count'], reverse=True)
print(variants_count)
```

After printing we can see that this dataset contains 116 different variants.

I would like to get all traces from the first variant, which should have 713 traces.
```
first_variant = variants_count[0]['variant']
traces_from_first_variant= variants_filter.apply(log, first_variant)
```

If i print "traces_from_first_variant" it has 848 traces. Is it because some traces contain all the activities from the first variant but also contain some new activities?
How can i just get the corresponding traces for each variant?

Thank you very much!

**Comment by fit-alessandro-berti** [comment]
Dear Danielkalfas,

You can use the following code. The method groups the cases belonging to the same variant. So the dictionary has a key the variant and as value the list of cases sharing such variant.

from pm4py.objects.log.importer.xes import importer as xes_importer
from pm4py.statistics.variants.log import get as variants_get

log = xes_importer.apply("C:/running-example.xes")
variants = variants_get.get_variants(log)
for k, v in variants.items():
    print(k, len(v))

**Comment by danielkalfas** [comment]
Thanks you for your fast response but this does not solve my question.

By Adjusting your code i can obtain the variant with the most cases 
`from pm4py.objects.log.importer.xes import importer as xes_importer
from pm4py.statistics.variants.log import get as variants_get
log = xes_importer.apply("receipt.xes")
variants = variants_get.get_variants(log)
max =-1
max_variant = None
for k, v in variants.items():
    if len(v) >= max:
        max = len(v)
        max_variant = k
    print(k, len(v))`
in max_variant is now the most frequent variant with 713 Traces. I would like to get an eventlog with only those 713 Traces. 

After applying the follow code i get more than 713 in the corresponding eventlog:

`from pm4py.algo.filtering.log.variants import variants_filter
from copy import deepcopy
filtered_log1 = variants_filter.apply(deepcopy(log), max_variant, parameters={variants_filter.Parameters.POSITIVE: True})`

filtered_log1 contains 848 traces. When filtering filtered_log_1 again i get 4 different variants.

From my understand filtered_log1 should only contain 1 variant which same 713 traces regarding the control-flow.

**Comment by fit-alessandro-berti** [comment]
Hi,

Simply replace the filtering row with:
filtered_log1 = variants_filter.apply(deepcopy(log), [max_variant], parameters={variants_filter.Parameters.POSITIVE: True})
