### ISSUE TITLE
hi, I got some data for Parallel Processse/ Subprocess

### ISSUE THREAD

**Issue by yanqinghao** [process-intelligence-solutions/pm4py#171]
By the way,

If you have a dataset and custom visualization needs, we can have a chat on the best way to represent that type of event log.

Let me know

Thanks
Alessandro

_Originally posted by @fit-alessandro-berti in https://github.com/pm4py/pm4py-source/issues/162#issuecomment-643914345_

**Comment by yanqinghao** [comment]
[log.zip](https://github.com/pm4py/pm4py-source/files/4963602/log.zip)
this is a process simulation log.
case:concept:name means the activity , a node(data flow by)
concept:name means case id , a data stream ID
parent means which node send current node the data

**Comment by yanqinghao** [comment]
> [log.zip](https://github.com/pm4py/pm4py-source/files/4963602/log.zip)
> this is a process simulation log.
> case:concept:name means the activity , a node(data flow by)
> concept:name means case id , a data stream ID
> parent means which node get current node the data

I want to get a graph like this
![image](https://user-images.githubusercontent.com/31135695/88248095-97c9ba80-ccd2-11ea-900f-96c1d2ce460b.png)

**Comment by yanqinghao** [comment]
> > [log.zip](https://github.com/pm4py/pm4py-source/files/4963602/log.zip)
> > this is a process simulation log.
> > case:concept:name means the activity , a node(data flow by)
> > concept:name means case id , a data stream ID
> > parent means which node get current node the data
> 
> I want to get a graph like this
> ![image](https://user-images.githubusercontent.com/31135695/88248095-97c9ba80-ccd2-11ea-900f-96c1d2ce460b.png)

but i use dfg get this
![image](https://user-images.githubusercontent.com/31135695/88248142-b7f97980-ccd2-11ea-877d-91e028e3b30a.png)

**Comment by yanqinghao** [comment]
so do u have some solution to solve this problem, or change process discovery algorithm?
which algorithm can I use?
Thanks!

**Comment by fit-alessandro-berti** [comment]
Dear yanqinghao,

Thanks for the interest. Unfortunately we cannot actually spend resources to build a custom discovery algorithm for this situation

If you are interested, we could agree on some type of deal for the implementation of such feature; for this, I invite you to contact our Fraunhofer Process Mining team at the address https://pm4py.fit.fraunhofer.de/contact 

Thanks
Alessandro

**Comment by yanqinghao** [comment]
> Dear yanqinghao,
> 
> Thanks for the interest. Unfortunately we cannot actually spend resources to build a custom discovery algorithm for this situation
> 
> If you are interested, we could agree on some type of deal for the implementation of such feature; for this, I invite you to contact our Fraunhofer Process Mining team at the address https://pm4py.fit.fraunhofer.de/contact
> 
> Thanks
> Alessandro

Dear Alessandro,

Thanks for reply. I will contact with your Fraunhofer Process Mining team later.

Thanks again
Qinghao Yan
