### ISSUE TITLE
How to add lifecycle:transition?

### ISSUE THREAD

**Issue by ajithsubash** [process-intelligence-solutions/pm4py#172]
I have caseid,activity,timestamp but how to add  lifecycle:transition in the event data

**Comment by fit-alessandro-berti** [comment]
Dear ajithsubash,

Thanks for your interest

Actually if the transition attribute is not in the data, you cannot add it.
You assume that all the events are "completion" events, and you can add a column "lifecycle:transition" containing the constant value "complete"
