### ISSUE TITLE
Use more visual cues from GraphViz in heuristics_net.visualizer

### ISSUE THREAD

**Issue by davidberenstein1957** [process-intelligence-solutions/pm4py#174]
Due to my low frequency and diverse chatbot interaction data, I am bound to using the heuristics miner. Sadly, this miner does not offer the usage out-of-the-box GraphViz functionalities for adding colouring to 'concept:name' and adding width to directed edges. However, I saw that these functionalities were implemented in the petrinet.visualizer. Could you look into adding these visual cues to the heuristics_net.visualizer as well?

**Comment by fit-alessandro-berti** [comment]
Dear David,

At the moment the visualization of the Heuristics Net is done using the "pydotplus" library.

We could potentially work on a refactoring of the visualization in the next release, so you can set these properties more easily.

Thanks

**Comment by davidberenstein1957** [comment]
Dear Alessandro,

Thank you for the response. Additionally, I have created a Flask sleeve for
interactive usage of the different miners and input parameters of the
heuristics miner. I was considering just hosting a GitHub page myself but
maybe it would be a great addition to the pm4py package in general?

Kind regards,
David Berenstein

**Comment by fit-alessandro-berti** [comment]
Dear David,

Your change request has been elaborated. I think we'll publish that in the next release.

For our guidelines, it is better that the project is hosted on your Github repository.

I'll check that for sure :)

**Comment by fit-alessandro-berti** [comment]
Dear David,

We released PM4Py 1.5.1 that covers your request

**Comment by davidberenstein1957** [comment]
Hello,

Thanks for the awesome support. 

Attached you can find an image of the Flask sleeve for the Heuristics miner. I am still working on implementing the other miners and making the sleeve non-company specific but you can probably get the gist from the image.


Kind regards,
David
