### ISSUE TITLE
Inductive_miner: activity_key drops to default value

### ISSUE THREAD

**Issue by marvin-wtt** [process-intelligence-solutions/pm4py#176]
## Explanation
After executing `inductive_miner#apply`, I get an error on the ano-log (log_ano.xes) 
> KeyError: 'concept:name'  

The train-log works without any problems.

Both datasets are both generated and contain the same amount of entries. The train dataset follows the sequence `s=A.(B+F).(C|D).E`. The ano dataset followes the same rules however a few cases deviate from that pattern.

I tried to debug it and noticed, that the `activity_key` gets dropped to the default value after a few iterations. So far, I was unable to find a reason for this behaviour.  

The logs and the full traceback are attached below.

## Code to reproduce
```Python
from pm4py.util import constants
from pm4py.visualization.petrinet import visualizer as pn_visualizer
from pm4py.visualization.process_tree import visualizer as pt_visualizer
from pm4py.algo.discovery.inductive import algorithm as inductive_miner
from pm4py.objects.log.importer.xes import importer as xes_importer

log_train = xes_importer.apply('log_train.xes')
log_ano = xes_importer.apply('log_ano.xes')

params = {
    constants.PARAMETER_CONSTANT_CASEID_KEY: "case",
    constants.PARAMETER_CONSTANT_ACTIVITY_KEY: "activity",
    constants.PARAMETER_CONSTANT_TIMESTAMP_KEY: "timestamp"
}

def inductive_miner_func(log):
    net, initial_marking, final_marking = inductive_miner.apply(
        log,
        variant=inductive_miner.Variants.IMf,
        parameters = {
            **params,
            #inductive_miner.Variants.IMf.value.Parameters.NOISE_THRESHOLD: 0.5
        }
    )
    
    # Vis
    gviz = pn_visualizer.apply(net, initial_marking, final_marking)
    pn_visualizer.view(gviz)
    
    # Tree
    tree = inductive_miner.apply_tree(log, parameters = {**params,})

    # Vis
    gviz = pt_visualizer.apply(tree)
    pt_visualizer.view(gviz)
    
inductive_miner_func(log_train)
inductive_miner_func(log_ano)`
```
I also tried to use to Variant parameters - same result.
```python
parameters = {
    inductive_miner.Variants.IMf.value.Parameters.ACTIVITY_KEY: "activity",
    inductive_miner.Variants.IMf.value.Parameters.CASE_ID_KEY: "case",
    inductive_miner.Variants.IMf.value.Parameters.TIMESTAMP_KEY: "timestamp",
    #inductive_miner.Variants.IMf.value.Parameters.NOISE_THRESHOLD: 1
}
```

## Full traceback and event logs.
*NOTE: The log files are actually in .xes format. I had to rename them to .txt to upload them here on GitHub.*
[error_traceback.txt](https://github.com/pm4py/pm4py-core/files/5195346/error_traceback.txt)
[log_ano.xes.txt](https://github.com/pm4py/pm4py-core/files/5195281/log_ano.xes.txt)
[log_train.xes.txt](https://github.com/pm4py/pm4py-core/files/5195282/log_train.xes.txt)

**Comment by fit-alessandro-berti** [comment]
Dear Marvin,

Thanks for your interest and signaling

We will verify and fix the issue as soon as we can

**Comment by fit-alessandro-berti** [comment]
Dear Marvin,

We identified the issue and will release a fix in the next release

Thanks

**Comment by fit-alessandro-berti** [comment]
Dear Marvin,

The PM4Py 1.5.1 release resolves your problem

Thanks for signaling!
