### ISSUE TITLE
Performing duration statistitics

### ISSUE THREAD

**Issue by DaMuBo** [process-intelligence-solutions/pm4py#180]
Hello there,

i used pm4py version: 1.5.2.3

 I probably found an issue with the pm4py package. In special in the statistics part.
I wanted to perform an easy calculation for the median. But got always an key error for my time:timestamp.

problem with following function: 
median_case_duration = case_statistics.get_median_caseduration(log, parameters={
    case_statistics.Parameters.TIMESTAMP_KEY: "time:timestamp"
})

The issue happend here:
--> 276     duration_values = get_all_casedurations(log, parameters=parameters)
    277     if duration_values:
    278         return duration_values[int(len(duration_values) / 2)]

C:\ProgramData\Anaconda3\lib\site-packages\pm4py\statistics\traces\log\case_statistics.py in get_all_casedurations(log, parameters)
    224         List of all duration values
    225     """
--> 226     cases = get_cases_description(log, parameters=parameters)
    227     duration_values = [x["caseDuration"] for x in cases.values()]
    228 

C:\ProgramData\Anaconda3\lib\site-packages\pm4py\statistics\traces\log\case_statistics.py in get_cases_description(log, parameters)
    119         if trace:
    120             ci = trace.attributes[case_id_key] if case_id_key in trace.attributes else "EMPTY" + str(index)
--> 121             st = trace[0][timestamp_key]
    122             et = trace[-1][timestamp_key]
    123             if business_hours:

in trace[0] only stands the concept name when i tried to reengineer it a bit I found in trace[1] the time:timestamp. I used a Event Log created by the function:

- event_log = pm4py.convert_to_event_log(dataframe)

I had the same issue with the extraction of the features based on the cycle/lead time. Is maybe the convert_to_event_log outdated or are all the functions based on an other format of the event log?

**Comment by fit-alessandro-berti** [comment]
Dear DaMuBo

I guess you miss the format_dataframe command.

Example CSV:

case,activity,timestamp
1,A,1970-01-01 01:01:01
1,B,1971-01-01 01:01:01
2,A,1972-01-01 01:01:01
2,C,1974-01-01 01:01:01


Script:

import pm4py
from pm4py.statistics.traces.log import case_statistics

dataframe = pm4py.read_csv("trial.csv")
dataframe = pm4py.format_dataframe(dataframe, case_id="case", activity_key="activity", timestamp_key="timestamp")
print(dataframe)
log = pm4py.convert_to_event_log(dataframe)
case_durations = case_statistics.get_all_casedurations(log)
print(case_durations)


It works :)
