### ISSUE TITLE
TypeError while exec replay_fitness.apply with ALPHA_VERSION_PLUS

### ISSUE THREAD

**Issue by marcelotranche** [process-intelligence-solutions/pm4py#181]
Thanks for the great job with python !

I'm trying to exec  replay_fitness.apply with ALPHA_VERSION_PLUS and getting the following error:

TypeError: unhashable type: 'dict'

I think that 'artificial_start' that was generated by processing the algorithm is the reason for this problem

What I'm doing wrong here? 
Thanks in advance.

![Code_replay_fitness](https://user-images.githubusercontent.com/11780416/97769180-7bc28a00-1b07-11eb-9d8d-ea833ce46070.png)
![token_replay_error_artificial_start](https://user-images.githubusercontent.com/11780416/97769182-7cf3b700-1b07-11eb-836f-aa8a738f26a3.png)

**Comment by fit-alessandro-berti** [comment]
Dear Marcelo,

Thanks for signaling. We have been able to reproduce the issue.

The issue is with the hash function of the Trace object

We will release a fix for the issue in the next release

Thanks

**Comment by fit-sebastiaan-van-zelst** [comment]
This has been solved in release 2.0.1
