### ISSUE TITLE
Request for information: Understanding InductiveMiner (IMd)

### ISSUE THREAD

**Issue by smillies** [process-intelligence-solutions/pm4py#186]
Hello there,

I am struggling to understand cut-finding in IMd. I am familiar with some of the relevant papers on IM, in particular

"Discovering Block-Structured Process Models From Event Logs Containing Infrequent Behaviour" and "Scalable Process Discovery with Guarantees" , but none seems to go into particular detail regarding the graph-theoretical definitions of cut. In particular not when it comes to working with directly-follows graphs. In the papers, the definitions are mostly spelled out in terms of connections between individual activities in the log. Examples are shown where cuts are presented in graphical illustrations. However, the implementation in pm4py works differently, using connected components, connection matrices, and condensed graphs.

I am trying to understand the connection between the implementation in pm4py and the algorithm as presented in the papers. Are there additional papers that explains the inductive miner in those graph-theoretic terms? Something that is a little closer to a specification of the actual algorithm used in pm4py than those papers that I have mentioned?

Should I look for this type of information through another channel, instead of GitHub issue?

-- Sebastian

**Comment by fit-alessandro-berti** [comment]
Dear smillies,

The implementation details are not contained in the paper(s). I think you can take a look to the original "InductiveMinerDeprecated" implementation in ProM. For example, it is interesting to see the usage of strongly connected components in the detection of sequential cut. For the XOR: the connection with the concept of connected components is easy.
The difficulty in the parallel cut detection is the establishment of the set of start/end activities for each component. That is easy if you have a log, a bit less if you have only the DFG. The loop cut detection is particularly tricky, for both IM and IMd, and it would require much time to explain how it works.
