### ISSUE TITLE
Prediction examples repository is unavailable

### ISSUE THREAD

**Issue by vertexclique** [process-intelligence-solutions/pm4py#188]
In [here](http://pm4py.pads.rwth-aachen.de/prediction-of-remaining-time/), branch name of `bpmnIntegration2` is mentioned. But I don't see the code around.
Also, https://github.com/pm4py/pm4py-pred/blob/master/pm4pypred/algo/prediction/versions/keras_rnn.py is invalid and the repository is gone.
Where can I find the prediction code examples?

**Comment by fit-alessandro-berti** [comment]
Dear vertexclique,

The package cited in the old version of our documentation is not available anymore
