### ISSUE TITLE
BPMN Support missing?

### ISSUE THREAD

**Issue by fabigr8** [process-intelligence-solutions/pm4py#189]
Hi everybody,

i tried to import and visualize a BPMN charts based on this example:
[http://pm4py.pads.rwth-aachen.de/bpmn-2-0-management/](http://pm4py.pads.rwth-aachen.de/bpmn-2-0-management/) 

Steps: xml import --> layout --> visualize via "bpmn_vis_factory.view"

but already the import is crushing (see console output below). After researching the problem, i found that the package **pm4pybpmn** is only available in PIP but i could not found the development branch here. And in the **pm4py-core** the visualization of BPMN isn't there anymore, i think? did you change the project / dependencies or revoke the bpmn visualization support?

i also reffer to [https://github.com/pm4py/pm4py-core/issues/60](https://github.com/pm4py/pm4py-core/issues/60 )

i achieved to fix it manually, that could be done by changing "/pm4pybpmn/visualization/bpmn/versions/frequency.py" in line 11 
from " from pm4py.visualization.petrinet.versions import token_decoration" to "from pm4py.visualization.petrinet.variants import token_decoration_frequency"
and changing "/pm4pybpmn/visualization/bpmn/versions/performance.py" from "from pm4py.visualization.petrinet.versions import token_decoration" to "from pm4py.visualization.petrinet.variants import token_decoration_performance"

is there a branch to push these changes? or did i just oversee the bpmn visualization support?
maybe someone can help me with this. 

cheers. F. 

`

ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-7-5740112e0b77> in <module>()
      1 #import pm4py bib
      2 from pm4pybpmn.objects.bpmn.importer import bpmn20 as bpmn_importer3
----> 3 from pm4pybpmn.visualization.bpmn import factory as bpmn_vis_factory

4 frames

/usr/local/lib/python3.6/dist-packages/pm4pybpmn/visualization/bpmn/versions/frequency.py in <module>()
      9 from pm4pybpmn.visualization.bpmn.util.bpmn_to_figure import bpmn_diagram_to_figure
     10 from pm4py.visualization.petrinet.util import vis_trans_shortest_paths
---> 11 from pm4py.visualization.petrinet.versions import token_decoration
     12 
     13 

ModuleNotFoundError: No module named 'pm4py.visualization.petrinet.versions'

`

**Comment by fit-alessandro-berti** [comment]
Dear fabigr8,

We dropped the package "pm4pybpmn" to go for a standalone support for BPMN diagrams.

You can find the documentation on https://pm4py.fit.fraunhofer.de/documentation

A visualizer for BPMN diagrams will be probably there in the next release of PM4Py

Alessandro

**Comment by Erinaceida** [comment]
Has the visualiser been released yet?

thanks

**Comment by fit-alessandro-berti** [comment]
Dear Erinaceida,

You can visualize a BPMN diagram inside PM4Py by doing:

import pm4py
pm4py.view_bpmn(bpmn_graph_object)

**Comment by Erinaceida** [comment]
Thanks! 
This isn't in the documentation. Where can I find a complete description of all functions in pm4py? 
regards
