### ISSUE TITLE
key error in importing csv file 

### ISSUE THREAD

**Issue by tommyyama2020** [process-intelligence-solutions/pm4py#190]
After running a snippet, below appeared. Can you help me out if i did something incorrect? 

![Screen Shot 2020-12-07 at 10 01 54](https://user-images.githubusercontent.com/38548157/101298879-585fcd00-3873-11eb-9c67-16fb07e659d0.png)

**Comment by fit-alessandro-berti** [comment]
Good morning, to use a dataframe for process mining purposes, you have to assign the following columns:
- case:concept:name => the case identifier column
- concept:name => the activity column
- time:timestamp => the timestamp column

Or follow the parameters as described in the documentation
