### ISSUE TITLE
Request: upload all referenced example files

### ISSUE THREAD

**Issue by hpl002** [process-intelligence-solutions/pm4py#191]
Currently working my way through some examples, and while you very successfully document the implementation, i cannot seem to find the corresponding example files. 

E.g., the "running-example.xes" file is referenced in multiple [examples](https://github.com/pm4py/pm4py-core/tree/release/examples) but i cannot find it in the repo. Same goes for other referenced files.

I therefore kindly ask if it would be possible to upload a directory containing simple example logs, and that only these be referenced in the [examples](https://github.com/pm4py/pm4py-core/tree/release/examples).

Thanks!

BR

Herman

**Comment by fit-alessandro-berti** [comment]
Dear Herman,

All the example files are contained in either the "tests/input_data" or the "tests/compressed_input_data" folder

Sincerely
Alessandro Berti

**Comment by hpl002** [comment]
Just found it.

Thanks for getting back to me so quickly!

Future readers, follow the link: https://github.com/pm4py/pm4py-core/tree/release/tests/input_data
