### ISSUE TITLE
lifecycle:transition column not working inductive miner

### ISSUE THREAD

**Issue by rensl88** [process-intelligence-solutions/pm4py#195]
I am trying the inductive miner and the inductive miner infrequent algorithm on a dataset containing a column with lifecycle data. The column consists of  "start" and "end" labels. 

While using this dataset in proM, I am able to create a process tree and petri net which uses the lifecycle data correctly. The petri net is then very clear and shows the process in a very clear way. 

However, in pm4py, it seems the lifecycle column is not recognized, and thus a very unclear petri net is created, which for each case_id has every activity run twice, because of the lifecycle column. 

So, my question is, is it possible to use the inductive miner with a lifecycle column or is this not yet implemented in pm4py (I now tried it by naming the lifecycle column `lifecycle:transition`)

If it is possible, I would create and upload example of my code, to see what I'm missing or did wrong.

**Comment by fit-alessandro-berti** [comment]
Dear rensl88,

To use a given classifier in PM4Py, you should "apply" the classifier to the log, and then you get an attribute that contains the desidered activity, to be used with any PM4Py algorithm.

Please take a look at the following:

from pm4py.objects.log.importer.xes import importer as xes_importer
from pm4py.objects.log.util import insert_classifier
from pm4py.algo.discovery.inductive import algorithm as inductive_miner
from pm4py.visualization.petrinet import visualizer as pn_visualizer

log = xes_importer.apply("C:/receipt.xes")
log, classifier_attr_key = insert_classifier.search_act_class_attr(log, force_activity_transition_insertion=True)
parameters = {inductive_miner.Variants.IM.value.Parameters.ACTIVITY_KEY: classifier_attr_key}
net, im, fm = inductive_miner.apply(log, parameters=parameters)
gviz = pn_visualizer.apply(net, im, fm)
pn_visualizer.view(gviz)

**Comment by rensl88** [comment]
Dear fit-alessandro-berti, 

Thanks for your fast reply! 
Your code is very helpful, thank you. 
However, I think the problem is that I am using a csv file which I converted into a log. Therefore, my file does not contain a classifier atribute. To deal with this I found the following code on the pm4py site (https://pm4py.fit.fraunhofer.de/documentation):

```
for trace in log:
 for event in trace:
  event["customClassifier"] = event["concept:name"] + event["lifecycle:transition"]
```
This however doesn't add a classifier when I check `log.classifiers`.
Am I missing a step?

**Comment by fit-alessandro-berti** [comment]
Dear rensl88,

You can do that with:
log.classifiers["Standard Classifier"] = ["concept:name", "lifecycle:transition"]

Sincerely
Alessandro

**Comment by rensl88** [comment]
Dear Alessandro,

Thanks a lot, that worked!
Maybe I am now moving away  a little bit from my initial question, but I was wondering whether it is possible to have pm4py recognize the start and end date of an activity, without showing the lifecycle status. I feel I am a bit unclear with this question, so let me show this with an example using ProM, I hope you are familiar with this tool. 

In ProM, I used a csv log containing the following columns: Case_id, activity_id, timestamp_start and timestamp_end. This was converted into a XES file succesfully. Here the timestamp columns were converted into a lifecycle:transition column, and one single time:timestamp column. 
When I used this xes file to visualize the log with the "inductive visual miner" it shows the following process map:

![inductive_miner_f](https://user-images.githubusercontent.com/49025633/104204355-7bab0880-542d-11eb-8397-9c392f0136aa.png)

This way of visualizing is very helpful for me, because it shows that the activities are concurrent/simultanuous. 

However, when I use the same setup in pm4py, (using the code you suggested) with the same data, the petri net shows the lifecycle:transition stages included in the net. This looks like this:

![image](https://user-images.githubusercontent.com/49025633/104206373-bb72ef80-542f-11eb-9fd8-f38c94bae8b5.png)


Is there an implementation in pm4py which uses the same approach as the inductive visual miner tool from proM? The algorithm used in that tool is the inductive infrequent miner. Which makes me think it has to be possible like this in pm4py, because the package supports this inductive miner algorithm. 

Hope my question is clear to you!

Sincerely,
Rens

**EDIT: inserted second image**

**Comment by fit-alessandro-berti** [comment]
Not yet!

You can do it with DFGs. Indeed, you could convert the "lifecycle" log to an "interval" log as described in the documentation. Then, performing the DFG performance visualization, you can get also the throughput time of an activity.
