### ISSUE TITLE
Concurrent Activities - Events with no transition time are not concurrent

### ISSUE THREAD

**Issue by colodenn** [process-intelligence-solutions/pm4py#201]
Events with no transition time are returned as concurrent activities.
I think adding an optional parameter to change this behaviour would be appreciated.

**Comment by fit-alessandro-berti** [comment]
Good afternoon. If I understand you correctly, you would like to have the option to disable events having only a completion timestamp and the same completion timestamp to be detected as concurrent

**Comment by colodenn** [comment]
Yes. 
I've got an activty A starting 2021-01-01 12:00:00 and ending 2021-01-01 13:00:00 and activity B starting 2021-01-01 13:00:00 and ending 2021-01-01 14:00:00.
Concurrent activites will return activity A and B as concurrent but I think they are not concurrent.

**Comment by fit-alessandro-berti** [comment]
Thanks. Yes, at the moment the method returns that the activities are concurrent whenever there is a non-empty intersection between the intervals. We will propose a solution for this presumably in the next release

**Comment by s-j-v-zelst** [comment]
Hi @colodenn This depends a bit on the assumption(s) on the start and end times of the activities.
Let s be 'start', let e be 'end' and let t(a) denote the actual time-range of the activity.
If you assume s < t(a) < e, you are right, i.e., they do not overlap.
However, if you assume s<= t(a) <= e, you could argue that the two activities overlap at time point 13:00:00; hence, could be seen as concurrent.

As indicated by @fit-alessandro-berti, we will discuss a solution for this.

**Comment by fit-alessandro-berti** [comment]
Dear colodenn, in the version 2.2.0 we introduced a parameter (Parameter.STRICT) on both log/dataframe statistics, that returns as concurrent the events with time intersection with (interval) length > 0.
