### ISSUE TITLE
cannot import name 'factory' 

### ISSUE THREAD

**Issue by PMarincola** [process-intelligence-solutions/pm4py#206]
**Describe the bug**
Dear team,
I'm trying to produce a DFG algorithm using this simply code found in the documentation:
_from pm4py.algo.discovery.dfg import factory as dfg_factory
dfg = dfg_factory.apply(event_log)_

this is the issue:

ImportError Traceback (most recent call last)
in
----> 1 from pm4py.algo.discovery.dfg import factory as dfg_factory
2 dfg = dfg_factory.apply(event_log)

ImportError: cannot import name 'factory' from 'pm4py.algo.discovery.dfg' (C:\Users\xxxxxx\Anaconda3\lib\site-packages\pm4py\algo\discovery\dfg_init_.py)

**Expected behavior**
Editing the init.py in the specified folder path there's nothing related to "factory"

**My Platform**
Anaconda environment
pm4py 2.2.0

Any suggestion about how to solve it ?

Thank you

**Comment by fit-alessandro-berti** [comment]
Dear PMarincola,

The documentation you are looking at is outdated.

Please look at http://www.pm4py.org/ for the updated documentation

Thanks and have a nice day
