### ISSUE TITLE
DFG Performance graph seems incorrect

### ISSUE THREAD

**Issue by Brinkhuis** [process-intelligence-solutions/pm4py#209]
The DFG Performance graph seems to output the values of the DFG Frequency graph in seconds. I found this to be the case for version 2.1.4.1 as well as for version 2.2.0.

```python
import pandas as pd
import pm4py
from pm4py.objects.log.exporter.xes import exporter as xes_exporter
from pm4py.objects.log.importer.xes import importer as xes_importer
from pm4py.algo.discovery.dfg import algorithm as dfg_discovery
from pm4py.visualization.dfg import visualizer as dfg_visualization

log_csv = pd.read_csv('https://raw.githubusercontent.com/pm4py/pm4py-core/release/tests/input_data/running-example.csv')
event_log = pm4py.format_dataframe(log_csv, case_id = 'case:concept:name', activity_key = 'concept:name', timestamp_key = 'time:timestamp', timest_format = '%Y-%m-%d %H:%M:%S%z')

xes_exporter.apply(event_log, 'running-example.xes')
log = xes_importer.apply('running-example.xes')

dfg_perf = dfg_discovery.apply(log)
gviz_perf = dfg_visualization.apply(dfg_perf, log=log, variant=dfg_visualization.Variants.PERFORMANCE)
dfg_visualization.view(gviz_perf)

dfg_freq = dfg_discovery.apply(log)
gviz_freq = dfg_visualization.apply(dfg_freq, log=log, variant=dfg_visualization.Variants.FREQUENCY)
dfg_visualization.view(gviz_freq)
```
![image](https://user-images.githubusercontent.com/3044985/107210550-952b7a00-6a04-11eb-89da-fff59dd06e8b.png)

![image](https://user-images.githubusercontent.com/3044985/107210509-847b0400-6a04-11eb-9979-94991faf27f7.png)

**Comment by fit-alessandro-berti** [comment]
Dear Brinkhuis,

The discovery operation should be done specifying the performance variant, like in the following example:

import pm4py
from pm4py.algo.discovery.dfg import algorithm as dfg_discovery
from pm4py.visualization.dfg import visualizer as dfg_visualizer

log = pm4py.read_xes("C:/running-example.xes")
dfg_frequency = dfg_discovery.apply(log)
dfg_performance = dfg_discovery.apply(log, variant=dfg_discovery.Variants.PERFORMANCE)
print(dfg_frequency)
print(dfg_performance)
gviz1 = dfg_visualizer.apply(dfg_frequency)
dfg_visualizer.view(gviz1)
gviz2 = dfg_visualizer.apply(dfg_performance)
dfg_visualizer.view(gviz2)

In this case the graphs are clearly different:

![image](https://user-images.githubusercontent.com/56342194/107213158-4c75c000-6a08-11eb-8699-18f6397c2cd7.png)
![image](https://user-images.githubusercontent.com/56342194/107213192-57305500-6a08-11eb-8333-f193c474bf7e.png)

**Comment by Brinkhuis** [comment]
Thanks for the explanation. If I understand correctly for the other miners (like Alpha Miner and Inductive Miner) it is not necessary to specify the "decoration variant" in the miner (discovery) itself, only when creating the vizualisation, right? (code below works fine for me) So it the DFG miner an exception?  For the other miners I use the variants to specify the mining variant (like `variant=inductive_miner.IMf` or `variant=variants.classic`. 

```python
import pandas as pd
import pm4py
from pm4py.objects.log.exporter.xes import exporter as xes_exporter
from pm4py.objects.log.importer.xes import importer as xes_importer
from pm4py.algo.discovery.alpha import variants
from pm4py.algo.discovery.alpha import algorithm as alpha_miner
from pm4py.visualization.petrinet import visualizer as pn_visualizer

# Event Log
log_csv = pd.read_csv('https://raw.githubusercontent.com/pm4py/pm4py-core/release/tests/input_data/running-example.csv')
event_log = pm4py.format_dataframe(log_csv, case_id = 'case:concept:name', activity_key = 'concept:name', timestamp_key = 'time:timestamp', timest_format = '%Y-%m-%d %H:%M:%S%z')
xes_exporter.apply(event_log, 'running-example.xes')
log = xes_importer.apply('running-example.xes')

# Alpha Minder
petri_net, initial_marking, final_marking = alpha_miner.apply(log, variant=variants.classic)

# View Performance
gviz = pn_visualizer.apply(petri_net, initial_marking, final_marking, variant=pn_visualizer.Variants.PERFORMANCE, log=log)
pn_visualizer.view(gviz)

# View Frequency
gviz = pn_visualizer.apply(petri_net, initial_marking, final_marking, variant=pn_visualizer.Variants.FREQUENCY, log=log)
pn_visualizer.view(gviz)
```

**Comment by Brinkhuis** [comment]
Hi @fit-alessandro-berti ,

Thanks for the explanation. If I understand correctly, for the other miners (like Alpha Miner and Inductive Miner) it is not necessary to specify the "decoration variant" in the miner (discovery) itself, only when creating the vizualisation, right? (code below works fine for me) So is the DFG miner an exception?  For the other miners I use the variant argument to specify the mining variant (like `variant=inductive_miner.IMf` or `variant=variants.classic`. 

```python
import pandas as pd
import pm4py
from pm4py.objects.log.exporter.xes import exporter as xes_exporter
from pm4py.objects.log.importer.xes import importer as xes_importer
from pm4py.algo.discovery.alpha import variants
from pm4py.algo.discovery.alpha import algorithm as alpha_miner
from pm4py.visualization.petrinet import visualizer as pn_visualizer

log_csv = pd.read_csv('https://raw.githubusercontent.com/pm4py/pm4py-core/release/tests/input_data/running-example.csv')
event_log = pm4py.format_dataframe(log_csv, case_id = 'case:concept:name', activity_key = 'concept:name', timestamp_key = 'time:timestamp', timest_format = '%Y-%m-%d %H:%M:%S%z')
xes_exporter.apply(event_log, 'running-example.xes')
log = xes_importer.apply('running-example.xes')

petri_net, initial_marking, final_marking = alpha_miner.apply(log, variant=variants.classic)
gviz = pn_visualizer.apply(petri_net, initial_marking, final_marking, variant=pn_visualizer.Variants.PERFORMANCE, log=log)
pn_visualizer.view(gviz)
```
![image](https://user-images.githubusercontent.com/3044985/107354663-b9ec2400-6ace-11eb-9092-810bdf879b90.png)
