### ISSUE TITLE
Precision of timestamp value

### ISSUE THREAD

**Issue by PMarincola** [process-intelligence-solutions/pm4py#211]
Dear team,
I'm trying to evaluate the result model of inductive miner algorithm applied on event log.
I noticed a lot of parallel activities that looking the original dataset doesn't exist. I think this happened because the dataset have timestamp like this 2020-03-10 15:40:54.088249088 , with some decimal as precision after second. Do you know if it is possible to read timestamp with much more precision in order to evaluate the correct sequence of activities ?

or exist any workaround to perform the same (probably converting timestamp value) ?

many thanks
Pietro

**Comment by s-j-v-zelst** [comment]
Hi Pietro,

To answer your question, it might be useful if you share a small sample (anonymized) of your data with us (you can contact us via pm4py@fit.fraunhofer.de)
For time representation we use native timestamps in python, it could be that this causes problems, however, we should investigate this in detail.

In general, the fact that the inductive miner shows concurrent behavior can have a lot of alternative underlying explanations as well.

kind regards,

Bas.

**Comment by s-j-v-zelst** [comment]
you can also try to sort the data when you load it in pm4py on a single trace, to see if pm4py would manipulate the correct ordering in any way.
