### ISSUE TITLE
Heuristic Miner doesn't take into account MIN_DFG_OCCURRENCES parameter

### ISSUE THREAD

**Issue by yellowananas** [process-intelligence-solutions/pm4py#217]
Hello,

I'm using Heuristic miner with MIN_DFG_OCCURRENCES equal to 50, but in resulting model I get many edges with occurrence less than 50. Is it a bug or maybe I don't understand something :)

`heu_net = heuristics_miner.apply_heu(log, parameters={
    heuristics_miner.Variants.CLASSIC.value.Parameters.MIN_DFG_OCCURRENCES: 50,
    heuristics_miner.Variants.CLASSIC.value.Parameters.MIN_ACT_COUNT: 50,
    heuristics_miner.Variants.CLASSIC.value.Parameters.DFG_PRE_CLEANING_NOISE_THRESH: 0.3,
    heuristics_miner.Variants.CLASSIC.value.Parameters.DEPENDENCY_THRESH: 0.7})`

`gviz = hn_visualizer.apply(heu_net)
hn_visualizer.view(gviz)`
 

![image](https://user-images.githubusercontent.com/10802397/114530767-ee599900-9c53-11eb-9b8a-5756e23d171c.png)

**Comment by fit-alessandro-berti** [comment]
Dear Anastasia,

The start/end edges of the diagram are currently excepted from the effect of the MIN_DFG_OCCURRENCES parameter

We may revise the mechanism in one of the next releases

**Comment by fit-alessandro-berti** [comment]
Dear Anastasia,

We have worked on your issue and will release the fix in the next release of PM4Py

Thanks and have a nice day

**Comment by yellowananas** [comment]
the issue is solved, thank you!
