### ISSUE TITLE
Question: Why do I need to provide start and end of an activity in one timestamp column with two rows?

### ISSUE THREAD

**Issue by derChristopher** [process-intelligence-solutions/pm4py#221]
Hello everybody, 

Why is it necessary to provide the event data in the following format: 

case | activity                        | timestamp         
0001| cutting machine **start** | 20200422T0455 
0001| cutting machine **end**  | 20200422T0700 

Is it also possible to provide the event data with two timestamp columns for one activity? 

case  | activity                       | timestamp_**start**  | timestamp_**end**
0001 | cutting machine        | 20200422T0455   | 20200422T0700 

Kind regards
Christopher

**Comment by fit-alessandro-berti** [comment]
Dear Christopher,

Mainstream process mining techniques (such as the Alpha Miner, the Inductive Miner, token-based replay, alignments ...) consider events that are atomic. These are distinguished by a case identifier, an activity, their execution timestamp, and the specification of the lifecycle.

Other process mining techniques consider "interval" events. These include, in the current version of PM4Py, the Heuristics Miner ++, the computation of sojourn time, concurrent activities.

We offer support for the conversion between lifecycle and interval logs, with the following class:
from pm4py.objects.log.util import interval_lifecycle

The class provides two methods, a method to_interval that converts a lifecycle log to an interval log; and a method to_lifecycle that converts an interval log to a lifecycle log.
