### ISSUE TITLE
Dependencies in Dockerfile seem to be incorrect

### ISSUE THREAD

**Issue by sven-klinkhamer** [process-intelligence-solutions/pm4py#222]
When I am trying to build a Docker image from the Dockerfile it does not work because of a dependency problem:

```
#19 1115.3 ERROR: Cannot install decorator==5.0.7, ipython==7.22.0 and networkx==2.5.1 because these package versions have conflicting dependencies.
#19 1115.3 The conflict is caused by:
#19 1115.3     The user requested decorator==5.0.7
#19 1115.3     ipython 7.22.0 depends on decorator
#19 1115.3     networkx 2.5.1 depends on decorator<5 and >=4.3
```

**Comment by fit-alessandro-berti** [comment]
Dear Sven

Thanks for signaling, we will fix the Dockerfile in the repository during the next release

By the way, we generated the docker image of PM4Py 2.2.7, that you can use through: docker pull javert899/pm4py

**Comment by sven-klinkhamer** [comment]
Thanks! Just found it on docker hub indeed!
