### ISSUE TITLE
Request for information: Background info on sequence cut implementation in IMd

### ISSUE THREAD

**Issue by smillies** [process-intelligence-solutions/pm4py#224]
Hello there,

The sequence cut implementation of the "Inductive Miner directly follows" in pm4py is interesting. It seems to find all possible such cuts on the same level at once. It seems to do that by avoiding to merge _all_ mutually unreachable strongly connected components into one (as mandated by Sander Leemans' Ph. D. thesis), but only some of them. One advantage may be efficiency. Another definitely is that pm4py sometimes finds a sequence cut where ProM only finds a flower model. As a downside, pm4py often misses "long-distance dependencies" between tasks, where it creates sequences of alternatives rather than alternatives of sequences. So in pm4py "Inductive Miner directly follows" behaves quite differently from the same miner in ProM.

I'd like to know if there's a paper about this, perhaps with a comparative evaluation of the pro's and con's of these approaches? Can anyone point me anywhere? The only paper specifically on pm4py that I have been able to find is Timo Pohl's Bachelor thesis, which regarding the sequence cut appears not to describe the implementation in the current version of pm4py (2.2.7.1).

Best Regards,
Sebastian

PS: Is there a better channel to discuss this kind of thing than a GitHub issue? A forum or such like?

**Comment by fit-alessandro-berti** [comment]
Dear smillies,

We found that the current implementation of IMd differs from the original implementation.

We have worked on a new implementation of IM (vanilla), that you could find in the current release, but still have to apply the same refactoring to the directly-follows based version.

If you want to contact us, you could use also the contact module at the website www.pm4py.org
