### ISSUE TITLE
Add new place and arcs to mined petri net.

### ISSUE THREAD

**Issue by JeffryCA** [process-intelligence-solutions/pm4py#225]
Hi,

I was wondering if it is possible to add new places and arcs to transitions in a petri net that was mined.
Or alternatively: Is it possible to get the transition object from the petri net?

Thanks for the support!

**Comment by fit-alessandro-berti** [comment]
Dear JeffryCA,

For sure, consider the following example:

import pm4py

log = pm4py.read_xes("C:/running-example.xes")
net, im, fm = pm4py.discover_petri_net_alpha(log)

# adding places and transitions
from pm4py.objects.petri_net.obj import PetriNet
new_place_1 = PetriNet.Place(name="new_place_1")
net.places.add(new_place_1)

new_place_2 = PetriNet.Place(name="new_place_2")
net.places.add(new_place_2)

new_trans = PetriNet.Transition(name="new_trans_1", label="new_trans_1")
net.transitions.add(new_trans)

# adding arcs connecting new_place_1 and new_trans, and new_trans to new_place_2
from pm4py.objects.petri_net.utils import petri_utils
petri_utils.add_arc_from_to(new_place_1, new_trans, net)
petri_utils.add_arc_from_to(new_trans, new_place_2, net)

pm4py.view_petri_net(net, im, fm, format="svg")

**Comment by JeffryCA** [comment]
Hi fit-alessandro-berti,

thanks for answering, but maybe I did not make myself very clear. I understand that I can add new places and transitions to a petri net but what is unclear to me is how to add arcs from the new places to the transitions already in the net (since I don't have the Transition object). 

Is there a way to do that?

**Comment by fit-alessandro-berti** [comment]
Dear JeffryCA,

You can identify the transition(s) having a given name/label as in the following example (here, the first transition in the net having as label "register request" is retrieved)

import pm4py

log = pm4py.read_xes("C:/running-example.xes")
net, im, fm = pm4py.discover_petri_net_alpha(log)
trans_register_request = [x for x in net.transitions if x.label == "register request"][0]
print(trans_register_request)
