### ISSUE TITLE
About the format of input log data?

### ISSUE THREAD

**Issue by 040840308** [process-intelligence-solutions/pm4py#228]
Hi, everyone
     
      Fortunately, I saw this amazing library. I tried some test example code. Now I want to solve some problem. A question here is: Could pm4py process a event sequence, which includes only event id or key, no timestamp and states, etc, then build a process model?
      
      Is there someone tell me whether PM4PY can solve this case?
      Thanks a lot.

**Comment by fit-alessandro-berti** [comment]
Dear 040840308,

Could you provide an example of the aforementioned data?

**Comment by 040840308** [comment]
> Dear 040840308,
> 
> Could you provide an example of the aforementioned data?

YES, here it is.

5 5 5 22 11 9 11 9 11 9 26 26 26 23 23 23 21 21 21 
22 5 5 5 11 9 11 9 11 9 26 26 26 
22 5 5 5 26 26 26 11 9 11 9 11 9 2 3 23 23 23 21 21 21 
22 5 5 5 11 9 11 9 11 9 26 26 26 
22 5 5 5 26 26 26 11 9 11 9 11 9 4 3 3 3 4 3 4 3 3 4 3 3 23 23 23 21 21 21 
22 5 5 5 26 26 26 11 9 11 9 11 9 3 3 4 3 4 3 3 3 4 4 3 3 23 23 23 21 21 21 
5 22 5 5 26 26 11 9 11 9 11 9 26 23 23 23 21 21 21 
22 5 5 5 26 26 26 11 9 11 9 11 9 4 4 3 2 23 23 23 21 21 21 
5 22 5 5 11 9 11 9 11 9 26 26 26 23 23 23 21 21 21 
5 5 5 22 11 9 11 9 11 9 26 26 26 23 23 23 21 21 21 

As the sequences above, there only the event ID without caseid, taskid, timestamp, is it possible for PM4PY to handle it and build process models? And how?

Thanks

**Comment by fit-alessandro-berti** [comment]
Dear,

You can use something like this to build the event log object. Then you can use any PM4Py algorithm on top of it (for example the discovery of a DFG):

import pm4py
from pm4py.objects.log.obj import EventLog, Trace, Event
from pm4py.util import xes_constants


F = open("input.txt", "r")
lines = F.readlines()
F.close()
log = EventLog()
for line in lines:
    trace = Trace()
    for step in line.strip().split(" "):
        event = Event({xes_constants.DEFAULT_NAME_KEY: str(step)})
        trace.append(event)
    log.append(trace)
dfg, sa, ea = pm4py.discover_dfg(log)
print(dfg)
print(sa)
print(ea)

**Comment by 040840308** [comment]
> Dear,
> 
> You can use something like this to build the event log object. Then you can use any PM4Py algorithm on top of it (for example the discovery of a DFG):
> 
> import pm4py
> from pm4py.objects.log.obj import EventLog, Trace, Event
> from pm4py.util import xes_constants
> 
> F = open("input.txt", "r")
> lines = F.readlines()
> F.close()
> log = EventLog()
> for line in lines:
> trace = Trace()
> for step in line.strip().split(" "):
> event = Event({xes_constants.DEFAULT_NAME_KEY: str(step)})
> trace.append(event)
> log.append(trace)
> dfg, sa, ea = pm4py.discover_dfg(log)
> print(dfg)
> print(sa)
> print(ea)

Nice, I have tried, it works well. 
Thanks a  lot.
Best
