### ISSUE TITLE
Visualize the conformance alignments?

### ISSUE THREAD

**Issue by 040840308** [process-intelligence-solutions/pm4py#229]
Hi, 

     I saw a API named conformance_diagnostics_alignments() in the example, it returns aligned_traces. A question comes to me: is it possible to visualize the alignments on the petri net graph? or pm4py has supported this?

    Thanks

**Comment by fit-alessandro-berti** [comment]
Dear 040840308,

I invite you to take a look at the following example:

import pm4py
from pm4py.visualization.petri_net.util import alignments_decoration
from pm4py.visualization.petri_net import visualizer

log = pm4py.read_xes("C:/receipt.xes")
net, im, fm = pm4py.discover_petri_net_inductive(log, noise_threshold=0.2)
aggregated_statistics = alignments_decoration.get_alignments_decoration(net, im, fm, log=log)
gviz = visualizer.apply(net, im, fm, aggregated_statistics=aggregated_statistics, variant=visualizer.Variants.ALIGNMENTS)
visualizer.view(gviz)

**Comment by 040840308** [comment]
> import pm4py
> from pm4py.visualization.petri_net.util import alignments_decoration
> from pm4py.visualization.petri_net import visualizer
> 
> log = pm4py.read_xes("C:/receipt.xes")
> net, im, fm = pm4py.discover_petri_net_inductive(log, noise_threshold=0.2)
> aggregated_statistics = alignments_decoration.get_alignments_decoration(net, im, fm, log=log)
> gviz = visualizer.apply(net, im, fm, aggregated_statistics=aggregated_statistics, variant=visualizer.Variants.ALIGNMENTS)
> visualizer.view(gviz)

Thanks, let me have a look.
Best

**Comment by 040840308** [comment]
> Dear 040840308,
> 
> I invite you to take a look at the following example:
> 
> import pm4py
> from pm4py.visualization.petri_net.util import alignments_decoration
> from pm4py.visualization.petri_net import visualizer
> 
> log = pm4py.read_xes("C:/receipt.xes")
> net, im, fm = pm4py.discover_petri_net_inductive(log, noise_threshold=0.2)
> aggregated_statistics = alignments_decoration.get_alignments_decoration(net, im, fm, log=log)
> gviz = visualizer.apply(net, im, fm, aggregated_statistics=aggregated_statistics, variant=visualizer.Variants.ALIGNMENTS)
> visualizer.view(gviz)

Hi, 
      Thanks for your advice. Nice pm4py!
      Sorry, here comes another question. I noticed that pm4py supports to convert the DFG(Directly Follow Graph) into a workflow net that perfectly mimic the DFG. However, I didn't find the example about how to covert from Petri Nets to DFG. Is this possible?
      Best

**Comment by fit-alessandro-berti** [comment]
Ehi, no, it's not possible to convert Petri net to directly-follows graphs :)
