### ISSUE TITLE
Discover Petri Net

### ISSUE THREAD

**Issue by stamik1** [process-intelligence-solutions/pm4py#230]
Hi everyone,
I am trying to learn how to use this library. I created this dataset that represents a sequence of daily tasks that a machine has to perform. From here I want to derive the Petri net. 
In the picture the output derived using the heuristic miner. I would like to know if the Petri net obtained is correct because I have doubts about its correctness.
In addition, then I would like to know how I can evaluate different sequences of daily activities if they conform to the model derived.
Any guidance or useful examples to fully understand the use of this library would be helpful.
I thank you in advance.

![1](https://user-images.githubusercontent.com/70598711/124723826-b937ac80-df0b-11eb-8e20-be15559ba3ae.png)

from pm4py.algo.discovery.heuristics import algorithm as heuristics_miner
net, im, fm = heuristics_miner.apply(log, parameters={heuristics_miner.Variants.CLASSIC.value.Parameters.DEPENDENCY_THRESH: 0.3})
from pm4py.visualization.petri_net import visualizer as pn_visualizer
gviz = pn_visualizer.apply(net, im, fm)
pn_visualizer.view(gviz)

![2](https://user-images.githubusercontent.com/70598711/124723846-bdfc6080-df0b-11eb-83f2-dab8cc3cefb3.png)

**Comment by fit-alessandro-berti** [comment]
Dear stamik1,

The heuristics nets converted to Petri nets do not provide models with perfect fitness usually, and you are not ensured to avoid deadlocks.

I suggest you to use the inductive miner, to get a fit model, and observe if you can get a good model with that. Another miner that you could use is the alpha miner.

Ale

**Comment by stamik1** [comment]
Dear Ale,
thank you for your reply.
I tried to use the inductive miner but I get this Petri net.

from pm4py.algo.discovery.inductive import algorithm as inductive_miner
net, initial_marking, final_marking = inductive_miner.apply(log, variant=inductive_miner.IM)

from pm4py.algo.discovery.inductive import algorithm as inductive_miner
from pm4py.visualization.process_tree import visualizer as pt_visualizer
tree = inductive_miner.apply_tree(log)

gviz = pt_visualizer.apply(tree)
pt_visualizer.view(gviz)

from pm4py.objects.conversion.process_tree import converter as pt_converter
net, initial_marking, final_marking = pt_converter.apply(tree, variant=pt_converter.Variants.TO_PETRI_NET)
gviz = pn_visualizer.apply(net, initial_marking, final_marking)
pn_visualizer.view(gviz)
![image](https://user-images.githubusercontent.com/70598711/124791454-5adeee00-df4c-11eb-9774-94a4a00e9b70.png)

I think after activity 1 the network crashes because it won't be able to perform activity 2, right?

I would like to know if this problem of the complex Petri net is due to the complexity of the sequence of tasks it has to perform, or a problem of the process discovery not being able to find the correct Petri net? Alternatively, do you think it is useful to use the library feature that allows me to create the Petri net by hand, or is it always better to use process discovery algorithms to derive the Petri net?

I thank you in advance for your response.

**Comment by fit-alessandro-berti** [comment]
Dear stamik,

Often a handmade model is more understandable. However, it may reflect bad the real behavior recorded in the log. When you have that, I invite you to evaluate the conformance of the log against the model. You may find that only a minority of cases follow the de-jure model :)

For the assertion on activity1 and activity2, I see no problem. 7, 2, and 1 are enabled concurrently. Which means any execution order between them is allowed. The complexity of the net is probably due to the complexity of the underlying data. To remedy that, you could keep only the most common variants of the log (see the documentation), or filter on the allowed endpoints (see also the documentation).

**Comment by stamik1** [comment]
Dear Ale,
thank you for your helpful reply.
I would like to ask you one last thing, since the event log I have taken into consideration must repeat every day, and some activities must repeat both in the morning and in the evening like activity 1 or activity 5, do you think it is better to distinguish these activities over the day, modifying the log for example activity 1_morning, 1_evening, and so on, so as to have a linear Petri net?

As a further step I would like to perform conformance checking on several logs from different days to see if they conform to the model found. Could you please give me some advice on this?Which parameters could be useful to evaluate the different behaviours recorded.
 

If you have examples or other material besides the documentation on the site, to better study the concepts of conformance checking and process discovery on the various algorithms, it would be very helpful.

Thank you for your time.

**Comment by fit-alessandro-berti** [comment]
Dear stamik,

For your first question, it really depends if activities repeat only once in a particular timeframe or could repeat twice in the morning (as example).

You can use any of the provided conformance checking methods (footprints, TBR, alignments). The most immediate measures are the percentage of fit traces and the fitness (which are provided by the three methods). More advanced conclusions can be given from the outputs, but for this you should investigate the single outputs as in the documentation

**Comment by stamik1** [comment]
Dear Ale,
thank you for your reply.
Some activities are performed both in the morning and in the evening, for example activity 1 has to be performed both in the morning, in the middle of the day and in the evening, as well as activity 4 and 5 and 6, this is to describe a routine to follow. My idea is to change the name of the activity by adding a specification of the time axis in which it is performed, such as morning, noon and evening, in order to have a more linear Petri net as I would have several transitions given the different name for the same activity to be repeated at different times of the day. 
Given this description of the log, do you think it is appropriate to do this pre-processing or is it better to use the log in this way? Because I don't know if the Petri net generated with the original log really represents the real model I want to describe, while dividing the activities in the various time periods I have new transitions of the same activity that is performed at different times of the day.

Thank you for your time and I apologise for the disturbance.

**Comment by fit-alessandro-berti** [comment]
Dear stamik,

Just give a try to this preprocessing. If it does not work like you intend, you can always revert to the old log ;)

**Comment by stamik1** [comment]
Perfect, thank you so much.
