### ISSUE TITLE
Question : Is there a implementation for creating a XES alignment log ?

### ISSUE THREAD

**Issue by AdamBanham** [process-intelligence-solutions/pm4py#236]
I am currently revisiting the documentation and the new changes, great work by the way.

However, I was wondering if there was an implementation to convert the list output from : 
`from pm4py.algo.conformance.alignments.petri_net import algorithm as alignments`
 (or similar)
 into an event log object with XES alignment extensions and notations ? 
`from pm4py.objects.log.log import EventLog`

The biggest difference being that events in the new traces, make reference to the transition id of the model via a projection of the alignment moves, instead of the alignment moves.

Perhaps something like the following?
```
from pm4py.objects.log.log import EventLog
from pm4py.algo.discovery.inductive import algorithm as inductive_miner
from pm4py.algo.conformance.alignments.petri_net import algorithm as alignments

log = pm4py.read_xes("BPIC12.xes")
net, init, final = inductive_miner.apply(log,variant=inductive_miner.Variants.IM_CLEAN)
aligned_traces = alignments.apply_log(log, net, init, final)
updated_log = aligned_traces.to_eventlog(log)
assert( type(updated_log) == EventLog )
updated_log.export("aligned_BPIC12.xes")
```

Also is there any development available (or want) to make multi-perspective conformance checking [1] available ? If so I would like to help.

Refs : 
[1] F. Mannhardt, M. de Leoni, H. A. Reijers, and W. M. P. van der Aalst, “Balanced multi-perspective checking of process conformance,” Computing, vol. 98, no. 4, Art. no. 4, Feb. 2015, doi: 10.1007/s00607-015-0441-1.

**Comment by fit-alessandro-berti** [comment]
Dear Adam,

Multi-perspective conformance checking is still missing from our software, even if we could consider implementing data Petri nets in the library

For the first question, we will consider implementing the feature (adding the transition ID to the corresponding event) that you suggested ;)

**Comment by AdamBanham** [comment]
Cool, ill keep an eye on the changelog for new version then.

So both multi-perspective conformance checking and petri net with data are not currently implemented, but might be in the future ? 

Not sure if you contributor guide, but I might have some time over the weekends to help with the petri nets with data implementation. What would be the best way to make a pull request?

Create a new issue with the general idea, then get an okay from POs,  then make a PR ?

**Comment by fit-alessandro-berti** [comment]
Dear Adam,

We are discussing internally about the integration of data Petri nets in our core. But haven't discussed about multi perspective conformance checking yet (e.g. balanced alignments)

**Comment by fit-alessandro-berti** [comment]
Dear Adam,

We confirm that in the current release, we released both support to data Petri nets,

and added an utility to enrich the log with the alignment. You can find an example application of the utility on the example script examples/enrich_log_with_align.py

**Comment by AdamBanham** [comment]
@fit-alessandro-berti Awesome, thanks for adding support.
