### ISSUE TITLE
Error: string indices must be integers

### ISSUE THREAD

**Issue by stamik1** [process-intelligence-solutions/pm4py#237]
Hi everyone,

I am trying to calculate alignments on an example log. 
The two lines of code produce the error "**_string indices must be integers_**". 
Could someone kindly help me understand how to solve this and how to calculate the alignments?

_aligned_traces = alignments.apply_log(modello, net_in_modello, initial_marking_in_modello, final_marking_in_modello)
print(aligned_traces)_

**Comment by fit-alessandro-berti** [comment]
Dear stamik1,

I hope the following example helps you:

import pm4py

# read an event log
log = pm4py.read_xes("C:/running-example.xes")
# discover a model ...
net, im, fm = pm4py.discover_petri_net_inductive(log)
# ... OR read it from a file
net, im, fm = pm4py.read_pnml("C:/running-example.pnml")
# apply alignments
aligned_traces = pm4py.conformance_diagnostics_alignments(log, net, im, fm)
print(aligned_traces)

**Comment by stamik1** [comment]
Hi Alessandro,
thank you for your reply.

**1.** I would like to ask you if there is a difference between _alignments.apply_log_ and _pm4py.conformance_diagnostics_alignments_ ?


**2.** Another thing I would like to ask you is whether after reading a log from a csv file, I have to use _format_dataframe_ to transform the column names? Should I then do _log_converter.apply(log)_ or is it unnecessary to do so?
log= pm4py.format_dataframe(log, case_id='id', activity_key='activity', timestamp_key='timeStamp')
log= log_converter.apply(log)


Thank you very much for your help.

**Comment by fit-alessandro-berti** [comment]
Dear stamik1,

1) no, no difference, just a simpler entrypoint
2) yes, the format_dataframe function shall be called on top of the dataframe and then the conversion applied (it is the safer method)

Have a nice day

**Comment by stamik1** [comment]
Hi Alessandro,
thank you very much for your reply.

I would just like to ask you one more thing about alignments. I saw in the library documentation that it is possible to modify the cost function but I didn't understand how to do it. Is it possible to assign a different cost for each transition in order to differentiate the fitness based on which activities are not carried out, so let's say to give a sort of different weight to the transitions in order to have a difference between the various logs and between the various events?

Thank you very much.

**Comment by fit-alessandro-berti** [comment]
Dear stamik1,

Please take a look to the "examples/alignment_test.py" file.
