### ISSUE TITLE
Petri net visualization with variant=Variants.FREQUENCY not working

### ISSUE THREAD

**Issue by jdavidleo** [process-intelligence-solutions/pm4py#241]
Hi,

I am new to pm4py and I am trying to visualize a Petri net with the frequency decoration because I am interested in seeing which are the most common activities in my process by encoding  the frequency  with the  saturation of the color of the box in the petri net and also I would like to see the number of events following a path. 

what I do is first to generate the event log by using the function 

`log = pm4py.format_dataframe(df, case_id='CaseIdCol',  activity_key = 'ActivityCol', timestamp_key='timestampCol')`

then I apply the heuristic miner over the log to find the model.

```
from pm4py.algo.discovery.heuristics import algorithm as heuristics_miner
net, initial_marking, final_marking = heuristics_miner.apply(log)
```

finally I apply a petri net visualizer to view my model

```
from pm4py.visualization.petri_net import visualizer as pn_visualizer
gviz = pn_visualizer.apply(net, initial_marking, final_marking, variant=pn_visualizer.Variants.FREQUENCY)
```
I get a petri net with my model but without the frequency decorations and color coding.

I am not sure if I am doing something wrong. I'd appreciate your support. 

thank you.

**Comment by fit-alessandro-berti** [comment]
Dear jdavidleo,

For the visualization of the frequency / performance obtained using token-based replay, you need to provide the parameter log=log to the visualization

Thanks and have a nice day
Alessandro

**Comment by jdavidleo** [comment]
aaand that was my mistake,

thank you very much Alessandro.

have a nice day you too.
