### ISSUE TITLE
Nodes positioning when exporting to BPMN 2.0

### ISSUE THREAD

**Issue by mxaviersmp** [process-intelligence-solutions/pm4py#244]
Hello. I'm having a problem when I try to export a `BPMN graph` to the `BPMN 2.0 xml` file.
When the `BPMN graph` is created from a `DFG`, the nodes appear to be all positioned on `x = 0` and `y = 0`.
When using `graphviz` to visualize the graph, it handles the nodes positioning, but the same doesn't happen when exporting to `BPMN 2.0`, which makes it not possible to visualize using a library like `bpmn.io`. 

I'm putting an example below to demonstrate what happens, so maybe you can point out something that I'm doing wrong if the problem is in my end. Thank you.

```python
from pm4py.algo.discovery.inductive import algorithm as inductive_miner
from pm4py.objects.conversion.wf_net import converter as wf_converter
from pm4py.visualization.bpmn import visualizer as bpmn_visualizer
from pm4py.objects.bpmn.exporter.exporter import apply

dfg_dict = {
    ('situation 0', 'situation 1'): 1,
    ('situation 1', 'situation 2'): 1,
    ('situation 2', 'situation 2'): 27,
    ('situation 2', 'situation 3'): 2,
    ('situation 3', 'situation 3'): 4,
    ('situation 3', 'situation 15'): 1,
}

net, initial_marking, final_marking = inductive_miner.apply_dfg(dfg_dict)
net_graph = wf_converter.apply(
    net, initial_marking, final_marking, variant=wf_converter.Variants.TO_BPMN
)
bpmn_dfg_graph = bpmn_visualizer.apply(net_graph)
```
![bpmn-graph](https://user-images.githubusercontent.com/26675637/126904705-3bd9d1b2-5f37-422d-9068-518d879ea997.jpg)
```python
apply(net_graph, 'bpmn.xml')
for e in net_graph.get_nodes():
    print(f'Node id: {e.get_id()} (x: {e.get_x()}, y: {e.get_y()})')
```
```txt
Node id: id5f9093f6-36e0-4ace-89a1-bc5c70bdfd32 (x: 0, y: 0)
Node id: idc56fdb26-5a13-4cc1-affb-991ddcccc401 (x: 0, y: 0)
Node id: id68407d45-6d22-4785-96c3-465783e65056 (x: 0, y: 0)
Node id: id1360bec7-c7b8-4f7d-bc6f-9f37931cf427 (x: 0, y: 0)
Node id: id1d380a36-bcd9-4bb9-8448-b6851a5939d1 (x: 0, y: 0)
Node id: id60c7d85f-2dc2-45c1-9cee-9c468b14ed63 (x: 0, y: 0)
Node id: idf7ddc5d6-a506-4751-8f6d-5301ee3c39b1 (x: 0, y: 0)
Node id: idf06e9518-1c71-4c4a-8ba4-31b34df5dde6 (x: 0, y: 0)
Node id: id092882b4-fac8-4971-8449-8c174ebeabcc (x: 0, y: 0)
Node id: ided99ae3c-3cf3-4ea0-8133-695051f0743f (x: 0, y: 0)
Node id: ide82731cc-2967-4cef-84a6-4b477e9567cf (x: 0, y: 0)
```
![bpmn-xml](https://user-images.githubusercontent.com/26675637/126904730-ee5cc369-3edb-4639-ada8-f59a3e506401.png)

**Comment by fit-alessandro-berti** [comment]
Dear flych3r,

I would invite you to use the pm4py.write_bpmn(bpmn_graph, output_file_path) command.

This command enables the automatic layouting of the graph. Hence, the output would look positioned in a similar way to Graphviz

Have a nice day

**Comment by mxaviersmp** [comment]
Thanks for the response alessandro, replaced the `apply(net_graph, 'bpmn.xml')` with `pm4py.write_bpmn(net_graph, 'bpmn.xml')` worked nicely.
