### ISSUE TITLE
XMLSyntaxError: Specification mandates value for attribute crossorigin, line 15, column 76

### ISSUE THREAD

**Issue by Villelmo** [process-intelligence-solutions/pm4py#247]
```
#data 
import pandas as pd 
from pm4py.objects.conversion.log import converter as log_converter
from pm4py.objects.log.importer.xes import importer as xes_importer
from pm4py.objects.log.util import dataframe_utils
```

```
#xes
log = xes_importer.apply('/home/lulu/running-example.xes')
```

**Comment by s-j-v-zelst** [comment]
Hi Villelmo, 

can you share the full output of your script? This helps us in pinpointing the problem!

**Comment by Villelmo** [comment]
```
  <link rel="preconnect" href="https://github.githubassets.com" crossorigin>
                                                                            ^
XMLSyntaxError: Specification mandates value for attribute crossorigin, line 15, column 76
```

**Comment by Javert899** [comment]
Dear Villelmo,

An XML attribute by specification should always have a value associated.

From what you pasted, it seems you are trying to parse HTML code, which isn't always standard XML.

Sincerely
Alessandro

**Comment by fit-alessandro-berti** [comment]
I think the problem you downloaded the running-example.xes from the current Github browsing window. But at end you downloaded HTML instead of XES (as you can check opening the file)

**Comment by Villelmo** [comment]
Yes, i download the running-example.xes from the current Github browsing 

Is the right the following file?

https://github.com/pm4py/pm4py-core/blob/release/tests/input_data/running-example.xes

**Comment by fit-alessandro-berti** [comment]
Dear Villelmo,

You shall never try to download files from Github from the website. Actually, it saves the entire HTML page of Github rather than the single file ;)

Try to clone the repository using Git and the running-example file will be fully correct and functional

**Comment by Villelmo** [comment]
I was using `wget` from `gnu/linux`. 

Thanks for the suggestion.
