### ISSUE TITLE
Does pm4py has Precedence Matrix functionality?

### ISSUE THREAD

**Issue by veeralakrishna** [process-intelligence-solutions/pm4py#248]
Does pm4py support a precedence matrix that has two axes: antecedent (the event that happens before) and consequent (the event that happens after) plot?

**Comment by s-j-v-zelst** [comment]
Hi Veelralakrishna; The 'directly follows graph' is basically a graph-variant of said matrix.

try pm4py.discover_dfg(log).
It will return such a matrix (as a dict) and also a counter maintaining start and end activities.
