### ISSUE TITLE
No image output of any notation when used in google colabaratory

### ISSUE THREAD

**Issue by resquilleur** [process-intelligence-solutions/pm4py#249]
Hellow, I use google colab to study pm4py, and when I use view, not get image in output. Why?

![image](https://user-images.githubusercontent.com/57857889/129540597-79824f1a-ac91-4873-b428-21bf19bad815.png)

What library used for visualisation?

**Comment by fit-alessandro-berti** [comment]
Dear resquilleur,

Thanks for signaling. We never considered Google Colab in running PM4Py, so we will investigate further

Have a nice day

**Comment by fit-alessandro-berti** [comment]
Dear resquiller, we will release a fix for this issue in the next release

**Comment by fit-sebastiaan-van-zelst** [comment]
I have (temporarily) reopened this issue.
When we have solved it, we will post a solution to the issue here and close it.

**Comment by fit-alessandro-berti** [comment]
Dear resquiller, in the current release (2.2.12) we fixed this problem. Have a nice day
