### ISSUE TITLE
View of graf output and Dark theme JupiterLab

### ISSUE THREAD

**Issue by resquilleur** [process-intelligence-solutions/pm4py#252]
Hellow!

I use Dark Theme in JupiterLab, see screen:
![image](https://user-images.githubusercontent.com/57857889/129879824-78928376-7e7a-406c-9f77-3c64d263218d.png)

The background of the picture is not white, but darkened, in other libraries there is no such problem. If I turn on a light theme all is well.

**Comment by fit-alessandro-berti** [comment]
Dear  resquilleur,

We actually force the background to be transparent in our Graphviz visualizations.

We will evaluate to change the behavior inside Jupyter notebooks for the next release.

Thanks

**Comment by fit-sebastiaan-van-zelst** [comment]
I have (temporarily) reopened this issue.
When we have solved it, we will post a solution to the issue here and close it.

**Comment by fit-alessandro-berti** [comment]
Dear resquiller, in the current release (2.2.12) we fixed this problem.

**Comment by fit-alessandro-berti** [comment]
Dear resquilleur,

We release a fix for this issue in the release 2.2.13 .

Essentially, we added a parameter, Parameters.BGCOLOR ("bgcolor"), for the visualizations, that is defaulted to "transparent". If you need a different background, you need to assign explicitly the background color to the parameters dictionary (e.g., "bgcolor": "white").
