### ISSUE TITLE
What is the mean of this variable net, im, fm for generate a petri net?

### ISSUE THREAD

**Issue by Villelmo** [process-intelligence-solutions/pm4py#253]
```
_# heuristics miner
net, im, fm = heuristics_miner.apply(log)

# viz
gviz = pn_visualizer.apply(net, im, fm)
pn_visualizer.view(gviz)_
```

**Comment by felixfuchs17** [comment]
Based on the [source code](https://github.com/pm4py/pm4py-core/blob/c1adc233eee71291f24b804bd934e0b43f00f3d2/pm4py/algo/discovery/heuristics/algorithm.py#L66)
- **net** is the petri network 
- **im** is the initial marking, of **net**
- **fm** is the final marking, of **net**
