### ISSUE TITLE
What is the function of a petri net?

### ISSUE THREAD

**Issue by Villelmo** [process-intelligence-solutions/pm4py#255]
I don't understand the function of a petri net and what are the advantages and profit

**Comment by fit-alessandro-berti** [comment]
Dear Villelmo, one of the main advantages of Petri nets in comparison to directly-follows graph is their support for concurrency.

Also, their execution semantics is really simple, in comparison to other models (for example BPMNs).

**Comment by Villelmo** [comment]
Where can I find more information about petri net?. The Information that was founded in OpenLibrary https://openlibrary.org/search?q=data+mining&mode=ebooks&has_fulltext=true but the results are not expected. Too i found a course about heuristic miner in future learn https://www.futurelearn.com/info/courses/process-mining/0/steps/15639

**Comment by fit-alessandro-berti** [comment]
Dear Villelmo,

I think the best reference can be the book of Prof. Wil van der Aalst, "Process Mining - Data Science in Action (2016)".

Alternatively: http://gkmc.utah.edu/7910F/papers/IEEE%20TKDE%20mining%20workflow.pdf 
https://www.researchgate.net/profile/Lijie-Wen/publication/269698116_Process_Mining_Overview_and_Outlook_of_Petri_Net_Discovery_Algorithms/links/5492e9db0cf2302e1d07466b/Process-Mining-Overview-and-Outlook-of-Petri-Net-Discovery-Algorithms.pdf

**Comment by Villelmo** [comment]
Excelent, thanks!
