### ISSUE TITLE
Is it possible to modify STD_MODEL_LOG_MOVE_COST value?

### ISSUE THREAD

**Issue by KristoR** [process-intelligence-solutions/pm4py#257]
The value of STD_MODEL_LOG_MOVE_COST seems to be hardcoded to 10000:
https://github.com/pm4py/pm4py-core/blob/913951e1a3e318e74185a967e16e5d736f61f90c/pm4py/objects/petri_net/utils/align_utils.py#L29

This value is referenced in several places related to cost functions. Eg for alignments:
https://github.com/pm4py/pm4py-core/blob/2884f58d5535a265868367f3f62bf26f27db4eb5/pm4py/algo/conformance/alignments/petri_net/algorithm.py#L288

What this means is that changing the default cost function leads to wrong fitness values.

Eg when changing the model cost to a value which does not perfectly divide by 10000.
Or when changing the log moves cost to 1.

Am I not doing something correct, or is this something that should be improved?

Example code:
```python
import pm4py
import pandas as pd
from pm4py.objects.petri_net.obj import PetriNet, Marking
from pm4py.objects.petri_net.utils import petri_utils
from pm4py.objects.conversion.log import converter as log_converter
from pm4py.algo.conformance.alignments.petri_net import algorithm as alignments

net = PetriNet("new_petri_net")

# Create places
places_container = {}

source = PetriNet.Place("source")
sink = PetriNet.Place("sink")

net.places.add(source)
net.places.add(sink)
places_container["source"] = source
places_container["sink"] = sink

for i in range(1,10):
    p = "p_"+str(i)
    px = PetriNet.Place(p)
    net.places.add(px)
    places_container[p] = px
	
# Create transitions
transitions_container = {}
tr_list = ["a", "b", "c1", "c2", "d1", "d2", "d3", "e1", "e2", "e3"]
for t in tr_list:
    tx = PetriNet.Transition(t, t)
    net.transitions.add(tx)
    transitions_container[t] = tx
	
# Add arcs

petri_utils.add_arc_from_to(places_container["source"], transitions_container["a"], net)
petri_utils.add_arc_from_to(places_container["source"], transitions_container["b"], net)
petri_utils.add_arc_from_to(transitions_container["a"], places_container["p_1"], net)
petri_utils.add_arc_from_to(transitions_container["a"], places_container["p_2"], net)
petri_utils.add_arc_from_to(transitions_container["b"], places_container["p_1"], net)
petri_utils.add_arc_from_to(transitions_container["b"], places_container["p_3"], net)
petri_utils.add_arc_from_to(places_container["p_1"], transitions_container["c1"], net)
petri_utils.add_arc_from_to(places_container["p_2"], transitions_container["d1"], net)
petri_utils.add_arc_from_to(places_container["p_3"], transitions_container["e1"], net)
petri_utils.add_arc_from_to(transitions_container["c1"], places_container["p_4"], net)
petri_utils.add_arc_from_to(places_container["p_4"], transitions_container["c2"], net)
petri_utils.add_arc_from_to(transitions_container["c2"], places_container["p_5"], net)
petri_utils.add_arc_from_to(places_container["p_5"], transitions_container["d1"], net)
petri_utils.add_arc_from_to(places_container["p_5"], transitions_container["e1"], net)
petri_utils.add_arc_from_to(transitions_container["d1"], places_container["p_6"], net)
petri_utils.add_arc_from_to(places_container["p_6"], transitions_container["d2"], net)
petri_utils.add_arc_from_to(transitions_container["d2"], places_container["p_8"], net)
petri_utils.add_arc_from_to(places_container["p_8"], transitions_container["d3"], net)
petri_utils.add_arc_from_to(transitions_container["d3"], places_container["sink"], net)
petri_utils.add_arc_from_to(transitions_container["e1"], places_container["p_7"], net)
petri_utils.add_arc_from_to(places_container["p_7"], transitions_container["e2"], net)
petri_utils.add_arc_from_to(transitions_container["e2"], places_container["p_9"], net)
petri_utils.add_arc_from_to(places_container["p_9"], transitions_container["e3"], net)
petri_utils.add_arc_from_to(transitions_container["e3"], places_container["sink"], net)

# Adding tokens
initial_marking = Marking()
initial_marking[source] = 1
final_marking = Marking()
final_marking[sink] = 1

# pm4py.view_petri_net(net)

# Create a non-conforming trace
data = {"case:concept:name":"1",
        "concept:name": ["a","c1","c2","e1","e2","e3"],
       }
	   
event_log = log_converter.apply(pd.DataFrame(data))

# ALIGNMENTS

# no params
aligned_traces_noparams = pm4py.conformance_diagnostics_alignments(event_log, net, initial_marking, final_marking)
# cost 20000
# fitness 0.8333333333333334


# custom cost function for model move

model_cost_function = dict()
trace_cost_function = dict()
for t in net.transitions:
    if t.label is not None:
        model_cost_function[t] = 5555
        sync_cost_function[t] = 0
    else:
        model_cost_function[t] = 0

parameters = {}
parameters[alignments.Variants.VERSION_STATE_EQUATION_A_STAR.value.Parameters.PARAM_MODEL_COST_FUNCTION] = model_cost_function
parameters[alignments.Variants.VERSION_STATE_EQUATION_A_STAR.value.Parameters.PARAM_SYNC_COST_FUNCTION] = sync_cost_function

aligned_traces_modelmove = alignments.apply_log(event_log, net, initial_marking, final_marking, parameters=parameters)
# cost 15555
# fitness 0.8888888888888888 # not correct



# custom cost function for assigning both log and model moves a cost of 1

model_cost_function = dict()
sync_cost_function = dict()
for t in net.transitions:
    if t.label is not None:
        model_cost_function[t] = 1
        sync_cost_function[t] = 0
    else:
        model_cost_function[t] = 0

parameters = {}
parameters[alignments.Variants.VERSION_STATE_EQUATION_A_STAR.value.Parameters.PARAM_MODEL_COST_FUNCTION] = model_cost_function
parameters[alignments.Variants.VERSION_STATE_EQUATION_A_STAR.value.Parameters.PARAM_SYNC_COST_FUNCTION] = sync_cost_function
parameters[alignments.Variants.VERSION_STATE_EQUATION_A_STAR.value.Parameters.PARAM_TRACE_COST_FUNCTION] = [1 for x in net.transitions]

aligned_traces_cost1 = alignments.apply_log(event_log, net, initial_marking, final_marking, parameters=parameters)
# cost 2
# fitness 1.0 # not correct
```

**Comment by s-j-v-zelst** [comment]
Hi KristoR,

Thanks for your question.
The cost function is used to define the costs you are anticipating to use for deviations of a certain type.
If you apply a custom cust function, this will be used in the underlying search on the statespace of the synchronous product net of the trace and the model (Let me know if you would nee more background material on that).

The default values in pm4py are: 10.000 for log/model moves, 1 for silent model moves, 0 for synchronous moves.
The reason for this is to avoid infinite loops when having models that contain token generators with invisible transitions.
If you just use sound WF-nets, this never occurs, and, you can also use 1 for log/model moves, 0 for silent model moves / synchronous moves (as often used in theory).

Fitness is calculated by the following formula: 1 - (alignment_costs / alignment_costs_best_of_worst); here, best_of_worst is computed by creating an alignment that has all events as log moves, and, all model moves of the alignment of the empty trace with the model.

Based on your experiments, it seems that in pm4py we do not use the provided cost function for the best of the worst alignment (which explains that costs 2 will yield a fitness value of 1).
We'll investigate and get back to you ASAP.

**Comment by KristoR** [comment]
Hi @s-j-v-zelst ,

Thanks! I believe the best of worst is used, but it is influenced by the hardcoded 10.000 value, like here:
https://github.com/pm4py/pm4py-core/blob/2884f58d5535a265868367f3f62bf26f27db4eb5/pm4py/algo/conformance/alignments/petri_net/variants/state_equation_a_star.py#L103

So eg when mapping the costs to 1 and using the above example, we have cost 2 but the best of worst becomes 0.
2//10000

That in itself is incorrect, but the next step where it miscalculates fitness is here:

https://github.com/pm4py/pm4py-core/blob/2884f58d5535a265868367f3f62bf26f27db4eb5/pm4py/algo/conformance/alignments/petri_net/algorithm.py#L288

It should be
1 - ( (2//1)/12)
But it becomes
1 - ( (2//10000)/6)

So that's why I wanted to check if this 10000 is somewhere modifiable currently or not. Seems to impact several places if one wants to use non-default cost function.

I also have a question on your comment:

> The reason for this is to avoid infinite loops when having models that contain token generators with invisible transitions.

I'm not fully following, what would be an example where this would happen?

**Comment by s-j-v-zelst** [comment]
Hi @KristoR; yep that is clearly where the bug is.
We'll fix that.

w.r.t. the infinite loops:
"Back in the day", the heuristic miner was used to mine Causal Nets (not to be confused with the Petri net notion of Causal Nets), i.e., as described in the book of Wil van der Aalst.
When translating these to regular WF-nets, token generators can be created with invisible transitions (due to improper split/join semantics).
As they, "back in the day", wanted to be able to also check conformance on those models, in good old ProM, the cost function was implemented like this, which we adopted.
However, for process models such as process trees, this is never an issue, i.e., they are sound by design.
(In fact, we have a different replay algorithm in pm4py for process trees, have not been having the time to write a paper about that one to publish it).

**Comment by fit-alessandro-berti** [comment]
Dear KristoR,

In the current release 2.2.13.1, we kept the fitness calculation as it was in the previous releases. Only we collected the code in a more logical place, in the case you want to define another fitness function

Take a look at pm4py.algo.conformance.alignments.petri_net.algorithm.apply_trace   in the current release

Have a nice day

**Comment by KristoR** [comment]
Hi @fit-alessandro-berti,

Thanks for the info. As you mentioned, the fitness calculation seems to be largely the same as previously, so it seems to me the issues above are not solved by this release. If I misunderstood then please correct me.

One note, the refactored calculation in the new version has a potential pitfall in this line:
https://github.com/pm4py/pm4py-core/blob/63bb8d2b993c97ac9c56435d09ea719ceaeb73f3/pm4py/algo/conformance/alignments/petri_net/algorithm.py#L136

If one was to define parameters in a way that e.g. trace and model moves are 1 and sync moves are 0, then the line is likely to get very small value for the variable `ltrace_bwc`, which in turn will lead to `ZeroDivisionError`. 

So it seems to me there remains a need to have a more dynamic value assignment for `align_utils.STD_MODEL_LOG_MOVE_COST`.

**Comment by fit-alessandro-berti** [comment]
Dear KristoR, we did not feel confident to change the current fitness calculation without inficiating results of existing experiments in some way

A way that we proposed in the current refactoring is the one inside the comment of the function. That one should be fine for every cost function, but we lead the decision to the user (if to use that instead of the currently-defined fitness function, or use a different one)

**Comment by KristoR** [comment]
Hi @fit-alessandro-berti,

Thanks for the explanation - I have an additional clarification.
Do I understand correctly, that your proposal is to uncomment these lines:
https://github.com/pm4py/pm4py-core/blob/63bb8d2b993c97ac9c56435d09ea719ceaeb73f3/pm4py/algo/conformance/alignments/petri_net/algorithm.py#L142-L152

If yes, I guess adding some `parameters.USE_CUSTOM_FITNESS` variable would be a nice enhancement for future, so the user(s) wouldn't have to modify source code and worry about future version upgrades. ;-) 

I'd assume if the parameter has default value False and the above comment is wrapped in an if-clause, it would cause no issues for existing experiments.

Have to say I don't know the setup details or historical dependencies of PM4Py package, so of course whichever way you propose is probably the best. :-)

**Comment by fit-alessandro-berti** [comment]
Yes exactly!

Albeit it is a bit unconvenient, it should work in your case

We will think to more systematic solutions for next releases ;)
