### ISSUE TITLE
V. 2.2.11: numpy.datetime64/numpy.timedelta64 problem 

### ISSUE THREAD

**Issue by JDaniloC** [process-intelligence-solutions/pm4py#259]
Because the [71c0919](https://github.com/pm4py/pm4py-core/commit/71c0919fc2ba2613f14564c14f0cef7fdeef3cdb) commit when the DataFrame to Stream conversion is changed [to_event_stream.py](https://github.com/pm4py/pm4py-core/blob/release/pm4py/objects/conversion/log/variants/to_event_stream.py), the numpy.datetime64/timedelta64 columns is causing errors when try to get the timestamp eg:
[get_cases_description()](https://github.com/pm4py/pm4py-core/blob/release/pm4py/statistics/traces/generic/log/case_statistics.py) function uses of datetime.datetime methods, or in [sojourn apply](https://github.com/pm4py/pm4py-core/blob/release/pm4py/statistics/sojourn_time/log/get.py) when get the timestamp.
Beucase the trace keeps the numpy.datetime64 type.
In the previous version was used the DataFrame.to_dict("records") and works well but the time to convert increases  a lot.
I tried to keep the new conversion function and changed this lines:
```py
for c in columns_names:
        value_list = dataframe[c].to_numpy()
        if type(value_list[0]) == np.datetime64:
            value_list = np.array(list(map(pd.to_datetime, value_list)))
        elif type(value_list[0]) == np.timedelta64:
            value_list = np.array(list(map(pd.to_timedelta, value_list)))
        columns_corr.append(value_list)
```
But the time incresed in average from 3s to 100s! 
We need to convert the DataFrame column type before or this is in development yet?
If you want to adapt each call to datetime.datetime methods to pandas.datetime64 methods, I will glad to help :D

**Comment by fit-alessandro-berti** [comment]
Dear JDaniloC,

Try to upgrade Numpy and Pandas to the latest versions (pip install -U numpy pandas). The problems should be gone then

**Comment by JDaniloC** [comment]
I'm using the latest versions of Pandas (1.3.3) and Numpy  (1.21.2), I get it casting datetime columns to object:
```py
dataframe[timestamp_key] = dataframe[timestamp_key].astype("object")
dataframe[start_timestamp_key] = dataframe[start_timestamp_key].astype("object")
```

Try it:
```py
from pm4py.objects.conversion.log import converter as log_converter
from pm4py.statistics.sojourn_time.log import get as soj_time_get
from datetime import datetime
import pandas

case_id = "Case"
activity_key = "ActivityCode"
start_timestamp_key = "Start"
timestamp_key = "End"

dataframe = pandas.DataFrame([
    { 
        case_id: 657797, 
        activity_key: "A1", 
        start_timestamp_key: datetime(2016, 6, 1, 7, 25, 9), 
        timestamp_key: "2016/06/01 07:53:49.000" 
    },
    {
        case_id: 657797, 
        activity_key: "A2", 
        start_timestamp_key: datetime(2016, 6, 1, 7, 53, 50), 
        timestamp_key: "2016/06/01 07:55:29.000"
    }
])

formated_dataframe = pm4py.format_dataframe(dataframe, case_id, 
    activity_key, timestamp_key, start_timestamp_key)
eventlog = log_converter.apply(formated_dataframe)

soj_time_get.apply(eventlog, parameters = {
    soj_time_get.Parameters.START_TIMESTAMP_KEY: start_timestamp_key
})
```
The start timestamp column will be a numpy.datetime64 type so will raise an error when run sojourn_time apply function

**Comment by fit-alessandro-berti** [comment]
Dear JDaniloC,

We reverted the change that we performed in the current release PM4Py 2.2.13.1

Now the conversion should be slightly slower than before in the mainstream cases, but these situations shall be handled

Have a nice day
