### ISSUE TITLE
generalization calculation problem

### ISSUE THREAD

**Issue by irislxxy** [process-intelligence-solutions/pm4py#260]
The generalization formula is 1- avg(sqrt(1.0/(n_occ_replay(t))), but in the code, it is 1.0 / sqrt(trans_occ_map[trans]).
Is this correct?

**Comment by fit-alessandro-berti** [comment]
Dear irislxxy,

The aforementioned term is calculated for every transition. Then the average is done, and subtracted to 1. Therefore, the calculation is eventually equivalent to your first formula
