### ISSUE TITLE
File format when saving visualizations

### ISSUE THREAD

**Issue by hb237** [process-intelligence-solutions/pm4py#265]
When saving a visualization the file format is determined based on the path. I am referring to the methods in _pm4py/vis.py_. If a method retrieves the format from the path I think it would be great to mention it in the method description. I was searching for a option to set the file format for a while, until I read the source code.

**Comment by fit-alessandro-berti** [comment]
Dear hb237,

Thanks for signaling. We'll definitely update that.

**Comment by hb237** [comment]
Thank you!
