### ISSUE TITLE
Parameter value duplicate

### ISSUE THREAD

**Issue by hb237** [process-intelligence-solutions/pm4py#268]
Hello!

After this [fix](https://github.com/pm4py/pm4py-core/commit/6326a8bb80ee6dcc64ab9f4a8a21ef7532461186) I tried again to to use my custom trace identifier as shown in #264.

My code looks now like this:
```
self.pm4py_log = attributes_filter.apply_numeric(log, self.start_block, self.end_block,
                                                         parameters={Parameters.CASE_ATTRIBUTE_PREFIX: '',
                                                                     attributes_filter.Parameters.CASE_ID_KEY: 'ident:piid',
                                                                     attributes_filter.Parameters.PARAMETER_KEY_CASE_GLUE: '',
                                                                     attributes_filter.Parameters.ATTRIBUTE_KEY: 'tx_blocknumber',
                                                                     attributes_filter.Parameters.POSITIVE: True})
```

However I could only get this working after changing the [constants](https://github.com/pm4py/pm4py-core/blob/5155b4147f8fcc1a839daa3e79e15eb9bd878225/pm4py/util/constants.py) in your source code. 

I think you have an issue here:
- In line 21: PARAMETER_CONSTANT_CASEID_KEY = 'case_id_glue'
- In line 36: PARAMETER_KEY_CASE_GLUE = 'case_id_glue'

I changed line 21 to PARAMETER_CONSTANT_CASEID_KEY = 'pm4py:param:case_id_key'
and now it is working for me. Perhaps you might want to change this.

Kind regards,

Hendrik

**Comment by fit-alessandro-berti** [comment]
Dear hb237,

Thanks for the suggestion. We will verify that your fix works well with the other parts of the application and integrate it in next release

**Comment by hb237** [comment]
Thank you!
