### ISSUE TITLE
Fitness Formula

### ISSUE THREAD

**Issue by stamik1** [process-intelligence-solutions/pm4py#270]
Hi @fit-alessandro-berti,
Sorry to disturb you, in the documentation of the fitness replay library you refer to your paper "Reviving Token based Replay: Increasing Speed While Improving Diagnostics". I would like to ask you if you could help me understand the formula used for fitness, as I understood the logic of adding the f counter but could not find the final formula used. 
Thank you

**Comment by fit-alessandro-berti** [comment]
Dear stamik1,

We distinguish two concepts. The trace fitness is calculated for every trace as:

        trace_fitness = 0.5 * (1.0 - float(missing) / float(consumed)) + 0.5 * (
                1.0 - float(remaining) / float(produced))

The log fitness, which is a measure at the log level, is calculated as

        log_fitness = 0.5 * (1 - total_m / total_c) + 0.5 * (1 - total_r / total_p)

Where total_m is the sum of the missing tokens for every trace, total_c is the sum of consumed tokens for every trace ...

A trace fitness of 1.0 indicates that the trace is perfectly fit (according to TBR) to the model.

A log fitness of 1.0 indicates that all the traces are fit.

**Comment by stamik1** [comment]
@fit-alessandro-berti thanks so much.

the library offers two ways to calculate fitness, either with the token based replay or with alignments. I would like to understand let's say the difference between the two approaches and if there is a difference in terms of the formula.

Thank you for your help

**Comment by fit-alessandro-berti** [comment]
Dear stamik1,

The concept is completely different, and the difference is analysed in the paper that you already are considering :)

Expect similar values, but not always and not for a specific reason

**Comment by stamik1** [comment]
Hi @fit-alessandro-berti ,
Yes, I understand that the concept for the calculation of fitness is different. I just wanted to understand if for the TBR I can refer to the formula you wrote previously, because the formula is not clear to me in the paper. I just realized that heuristics are used for invisible transitions and to avoid having too many tokens generated. right?

thank you very much.

**Comment by fit-alessandro-berti** [comment]
Yes you can refer to that :)
