### ISSUE TITLE
human_readable_stat locale

### ISSUE THREAD

**Issue by JDaniloC** [process-intelligence-solutions/pm4py#272]
I'm thinking to do a PR where we can send a  optional dict, replacing the strings in the human_readable_stat function.
Eg. in the Brazil: 

-  "Y" is "A"
- "MO" is "M"

So in the graphviz_visualization function we can pass a "stat_locale" parameter, with the value:
```py
{"year": "A", "month": "M"}
```
Where the human_readable_stat function will try:
```py
year_str = stat_locale.get("year", "Y")
```
And so on. Is it a valid attempt?

**Comment by fit-alessandro-berti** [comment]
Dear JDaniloC, yes of course this is a good attempt.

Ideally it should be retrocompatible, so the parameters dictionary for the human_readable_stat method should be optional, and the values defaulted if not provided.

Note that there are 19 usages of the function in the code. Ideally all this calling methods should accept the stat_locale parameter

**Comment by fit-alessandro-berti** [comment]
If you want, we could implement your suggestion and include it in the next release
