### ISSUE TITLE
Colorize arrows

### ISSUE THREAD

**Issue by JDaniloC** [process-intelligence-solutions/pm4py#274]
It's interesting add arrows in gray scale in the performance DFG when missing the `start_timestamp_key` (consequently not using sojourn)?
Like that:
![Captura de tela 2021-10-19 174048](https://user-images.githubusercontent.com/49529180/137988384-b0381df2-9d45-41e7-bd7e-dd77403b8676.png)

**Comment by fit-alessandro-berti** [comment]
Dear JDaniloC,

Could you provide us the code to replicate this issue? Not the log, just the code

Have a nice day
