### ISSUE TITLE
compiling and running the pm4py project 

### ISSUE THREAD

**Issue by mennaawael** [process-intelligence-solutions/pm4py#277]
can anyone tell me how can I run the project after I download it as a zip file from GitHub?

I have no coding skills so if anyone can explain what I should do step by step and the tools needed for the project I would be grateful.

**Comment by fit-alessandro-berti** [comment]
Dear mennaawael,

I invite you to look at the following two resources:
- Installation tutorial: https://pm4py.fit.fraunhofer.de/install
- Getting started tutorial: https://pm4py.fit.fraunhofer.de/getting-started

In general, you do not need to download the project from Github, but you can install PM4Py with "pip" and then use it in a Python interpreter, for example inside a Jupyter notebook ("pip install jupyter", then "jupyter notebook"). Please check the two aforementioned tutorials

**Comment by mennaawael** [comment]
thank you for the quick reply. I already have the pm4py package and I am using PyCharm for the execution. However, the package have a lot of files, what file specifically should I run in PyCharm  ??

PS: I tried to run the __init__.py file and there were the error" NoModule named "PM4PY"

**Comment by fit-alessandro-berti** [comment]
Dear mennaawael,

If you installed PM4Py correctly with "pip", you should be able to open any Python project in Pycharm, create one Python file (for example called "test1.py", insert the rows:

import pm4py



and execute it. You do not need to open any specific file of the package

**Comment by mennaawael** [comment]
ok, should I open the new python project in Conda environment or Virtualenv or pipenv ( because I have to choose one in PyCharm)??
