### ISSUE TITLE
Object centric petri net 

### ISSUE THREAD

**Issue by mennaawael** [process-intelligence-solutions/pm4py#278]
I want to covert an XES event log into object-centric event log and then generate an object centric petri net from it, and I cannot the documentation for that ( I already installed the pm4py-mdl library) @fit-alessandro-berti

**Comment by fit-alessandro-berti** [comment]
Dear mannaawael,

The package PM4Py-MDL is not supported anymore, and we probably won't integrate object-centric Petri nets inside PM4Py in the near future.

As I am the former mantainer of the package, I would like that we keep the discussion on that by my university e-mail. a.berti@pads.rwth-aachen.de
