### ISSUE TITLE
Petri nets vs DFG graphs 

### ISSUE THREAD

**Issue by Mariam223** [process-intelligence-solutions/pm4py#280]
I want to ask what is the use case for a Petri net vs the DFG ? what is the difference and when to use each one of them ?
Also, I want to know the difference between the OC-Petri net and the OC-DFG.

Thanks.

**Comment by fit-alessandro-berti** [comment]
Dear Mariam223, one of the main advantages of Petri nets in comparison to directly-follows graph is their support for concurrency.

Also, their execution semantics is really simple, in comparison to other models (for example BPMNs).

OC-Petri net and OC-DFG are not yet supported by PM4Py, although there will be interesting developments in the future.
