### ISSUE TITLE
Parameter no_model unused in PTandLogGenerator

### ISSUE THREAD

**Issue by sarahsporck** [process-intelligence-solutions/pm4py#286]
It seems that the parameter no_model in the tree generator is not used at all, oposed to the original implementation https://github.com/tjouck/PTandLogGenerator/blob/b0a96060a061d5fee13f458d5c6a6bce9601ddcb/plugins/generate_newick_trees.py#L103

**Comment by fit-alessandro-berti** [comment]
Dear Taggotty, thanks for signaling. We will release a fix for this in the next release. Have a nice day.

**Comment by fit-sebastiaan-van-zelst** [comment]
This issue is fixed in https://github.com/pm4py/pm4py-core/releases/tag/2.2.17
