### ISSUE TITLE
 Revert "initial marking unicode circle including numbers" #284 

### ISSUE THREAD

**Issue by phi1-h** [process-intelligence-solutions/pm4py#287]
PR: #283 

Currently the initial markings do not differentiate between different number of markings.
Two Markings look the same as one.
This changes the unicode to a circle with a digit inside.
This works until 10.

--
Why was this reverted?
Is there another way we can continue to display how many markings are on the initial marking?

**Comment by fit-alessandro-berti** [comment]
Dear phi1-h,

Thanks for the question. While the number was showing correctly in .SVG diagrams, it produced very ugly .PNG diagrams.

The priority for us is to keep the .PNG format looking decent, because many researchers are using that when publishing a paper.

We need to find other ideas for that
