### ISSUE TITLE
Dotted chart doesn't work

### ISSUE THREAD

**Issue by vagalvez** [process-intelligence-solutions/pm4py#288]
Hi there,

When I run the following code to import the dotted chart visualizer:

`from pm4py.visualization.dotted_chart import visualizer as dotted_chart_visualizer`

I get a ModuleNotFoundError:

`ModuleNotFoundError: No module named 'pm4py.visualization.dotted_chart'`

Tried to solve it finding possible new names for the visualization file in the repository (such as writing 'petri' instead of 'petri_net' in the code to create petri nets), but I couldn't.

Any help?

Thanks!

**Comment by fit-alessandro-berti** [comment]
Dear vagalvez,

Please update your PM4Py version with the command: pip install -U pm4py
If you are working with Conda / Pycharm environments, please check if they are also updated to latest version of PM4Py.

Then it should be working

**Comment by vagalvez** [comment]
Dear Alessandro,

Now it works! thanks for the help 😁
