### ISSUE TITLE
Parameters min, mode, max do not match output of PTandLogGenerator

### ISSUE THREAD

**Issue by gregvanhoudt** [process-intelligence-solutions/pm4py#290]
### Brief Description
When constructing a process tree via the PTandLogGenerator, the parameters `min`, `mode` and `max` are not taken into account correctly. To illustrate, I have generated 5000 trees for two different distributions. The plots are shown below.

![(10, 20, 30) - 5000 runs](https://user-images.githubusercontent.com/55534825/144040590-49b4f816-698f-4399-bd65-38c00b254071.png)

![(100, 200, 300) - 5000 runs](https://user-images.githubusercontent.com/55534825/144040597-0eed9cad-a085-4e00-877a-899ac70cadd5.png)

As you can see, the observations do not match the inputs: trees are generated with fewer leaves than the minimum amount requested.

### Recreating the issue
```
from pm4py.algo.simulation.tree_generator import algorithm as pt_gen
from pm4py.objects.process_tree.obj import ProcessTree

import random
import matplotlib.pyplot as pyplot

def gen_tree(min, mode, max) -> ProcessTree:
    sequence = round(random.uniform(0.3, 0.6), 2)
    parallel = round(random.uniform(0.1, 0.3), 2)
    choice = round(1 - sequence - parallel, 2)

    parameters = {}
    parameters['min'] = min
    parameters['mode'] = mode
    parameters['max'] = max
    parameters['no_models'] = 1 
    parameters['sequence'] = sequence
    parameters['choice'] = parallel
    parameters['parallel'] = choice
    parameters['loop'] = 0
    parameters['or'] = 0
    parameters['silent'] = 0
    parameters['duplicate'] = 0
    parameters['lt_depencency'] = 0
    parameters['infrequent'] = 0
    parameters['unfold'] = 0
    parameters['max_repeat'] = 0

    tree = pt_gen.apply(parameters=parameters)
    return tree

def plot_output(set, size, n):
    pyplot.hist(set)
    pyplot.xlabel("Number of leaves in the tree")
    pyplot.ylabel("# Occurrences")
    pyplot.title(f"Tree size set to {size} - {n} runs")
    pyplot.savefig(f"{size} - {n} runs.png")
    pyplot.close()


def experiment(size, n):
    set = []
    for i in range(n):
        tree = gen_tree(*size)
        leaves = tree._get_leaves()
        set.append(len(leaves))

    plot_output(set, size, n)


if __name__ == "__main__":
    experiment((10, 20, 30), 5000)
    experiment((100, 200, 300), 5000)
```

**Comment by fit-alessandro-berti** [comment]
Dear greg,
The min, mode and max in the current implementation are referring to the number of nodes in the tree (including the operators), not the number of leaves

**Comment by gregvanhoudt** [comment]
Hi Allessandro

Given the nature of my research project, do you think it would be feasible to add parameters to fix the number of leaves instead of the number of operators?

Regards
Greg

**Comment by fit-alessandro-berti** [comment]
Dear greg, unfortunately I cannot promise anything on this. You could operate the change to the code for your purposes, then if you want to push a PR we can discuss about it
