### ISSUE TITLE
Amount of activtities in PTandLogGenerator

### ISSUE THREAD

**Issue by jaripeeperkorn** [process-intelligence-solutions/pm4py#291]
The number of activities in the generated tree is always lower than the number you would expect from the triangular distribution. I think the tree also counts the sequence/choice/... nodes as "activity node".

**Comment by gregvanhoudt** [comment]
Hi Jari

Yes, you are correct. See this recent issue #290 from me.

Regards
Greg

**Comment by s-j-v-zelst** [comment]
Hi Guys,

Thanks, we will look into this and get back to you.

**Comment by fit-sebastiaan-van-zelst** [comment]
This issue is fixed in https://github.com/pm4py/pm4py-core/releases/tag/2.2.17
