### ISSUE TITLE
log_to_feature: Export features on case level to pandas df

### ISSUE THREAD

**Issue by darjooling86** [process-intelligence-solutions/pm4py#292]
Hi,

first of all thank you for the great work!

I would like to use pm4py to extract relevant features on a case level for further usage. Therefore, I need the output of the function log_to_features.apply() together with the case id (e.g. 'case:concept:name'). Is there a way to extract the processed features together with the case id?

Thank you!

**Comment by fit-alessandro-berti** [comment]
Dear darjooling86,

At the moment we are offering two types of feature extraction: classic event logs and Pandas dataframes.
See https://pm4py.fit.fraunhofer.de/documentation#item-7-5

The Pandas dataframe one generates a feature table where the case ID is by default included in the columns, while the log-based one no.

We'll try to provide this possibility for the log-based one in the upcoming releases

**Comment by darjooling86** [comment]
Thank you for your reply! So this means, currently it is not possible to extract e.g. the feature 'workload' (ENABLE_RESOURCE_WORKLOAD) together with the case id? Correct?

**Comment by fit-alessandro-berti** [comment]
Unfortunately not there! We have such feature, but the case identifier column is never going to be included in the feature table starting from an EventLog

**Comment by darjooling86** [comment]
Thank you. Such a functionality would be quite nice and helpful! ;)

**Comment by fit-sebastiaan-van-zelst** [comment]
This issue is covered by https://github.com/pm4py/pm4py-core/releases/tag/2.2.17
