### ISSUE TITLE
Bug in organizational mining setting Activity Key

### ISSUE THREAD

**Issue by Th0m4sR** [process-intelligence-solutions/pm4py#295]
Hi,

when trying to apply organizational mining on my data set I realized a different behavior than I had with the example data sets of the documentation, i.e. it took my resources key as key for the activities instead of the parameter that I actually passed as key for the activities at a certain point.
Looking into `pm4py/algo/organizational_mining/util.py` I saw in the function `get_groups_from_log` in line 58 it sets:

`activity_key = exec_utils.get_param_value(Parameters.RESOURCE_KEY, parameters, xes_constants.DEFAULT_NAME_KEY)`

So the activity key is actually set to the resource key what causes the error.
It may be easily fixed by changing line 58 of  `pm4py/algo/organizational_mining/util.py`  to:

`activity_key = exec_utils.get_param_value(Parameters.ACTIVITY_KEY, parameters, xes_constants.DEFAULT_NAME_KEY)`

Kind regards

**Comment by fit-alessandro-berti** [comment]
Dear Th0m4sR,

Very thanks for spotting this :)

We'll release a fix in the upcoming release

**Comment by fit-sebastiaan-van-zelst** [comment]
This issue is fixed in https://github.com/pm4py/pm4py-core/releases/tag/2.2.17
