### ISSUE TITLE
Token replay considers model fit when there is a direct flow from startplace -> start activity transition -> endplace

### ISSUE THREAD

**Issue by pastra98** [process-intelligence-solutions/pm4py#301]
Hi,
First of all, thank you for creating this awesome library. I'm using it for my bachelors thesis where I'm trying to create a genetic algorithm that evolves Petri Nets. My problem is that the GA has once again found a trick to achieve high fitness scores without actually evolving a useful model.

I'm working with the [running example log](https://github.com/pm4py/pm4py-core/blob/release/notebooks/data/running_example.xes), and the ga constantly evolves this model:

![model](https://i.imgur.com/N4DiCwv.png)
(The arc numbers here are only relevant to my ga)
Which of course is simple (thus scoring high in my ga), but surprisingly it also gets 100% fit traces.

Heres some sample code to get the exact same model:

```python
from pm4py.algo.evaluation.replay_fitness import algorithm as replay_fitness_evaluator
from pm4py.objects.petri_net.obj import PetriNet, Marking
from pm4py.objects.petri_net.utils.petri_utils import add_arc_from_to
from pm4py.objects.log.importer.xes import importer as xes_importer

# load running example log
lp = "pm_data/running_example.xes"
log = xes_importer.apply(lp)

net = PetriNet("TestPetri")
# add start and end places
start = PetriNet.Place("start")
net.places.add(start)
end = PetriNet.Place("end")
net.places.add(end)
# add register request transition (first trans that appears in every trace)
trans = PetriNet.Transition("register request", label="register request")
net.transitions.add(trans)
add_arc_from_to(start, trans, net)
add_arc_from_to(trans, end, net)
# initial marking
im = Marking()
im[start] = 1
# final marking
fm = Marking()
fm[end] = 1


fit = replay_fitness_evaluator.apply(
    log, net, im, fm,
    variant=replay_fitness_evaluator.Variants.TOKEN_BASED
)

print(fit)
```

If there are any other tasks in the model, the fitness is reduced as the token replayer tries to execute these tasks as well and deems the traces unfit. This issue only occurs with the starting activity in the log, but my ga finds this model everytime.

I have read through your great paper on token replay, and stepped through the pm4py code, but I'm a bit stumped at the moment. Do I have a fundamental misunderstanding about how token replay works?

All I really need is a percentage of traces in the log that fit the model.

Best wishes,

Paul

**Comment by fit-alessandro-berti** [comment]
Dear pastra, if the log contains activities that do not appear in the process model, these cannot contribute to the four fundamental quantities of token-based replay (P=produced tokens, C=consumed tokens, M=missing tokens, R=remaining tokens). In essence, they cannot have any effect on the fitness result.

This is different from alignments, where the activities would have been signaled as "move on log"

**Comment by pastra98** [comment]
> Dear pastra, if the log contains activities that do not appear in the process model, these cannot contribute to the four fundamental quantities of token-based replay (P=produced tokens, C=consumed tokens, M=missing tokens, R=remaining tokens). In essence, they cannot have any effect on the fitness result.
> 
> This is different from alignments, where the activities would have been signaled as "move on log"

Wow thx for reaching back so quickly. I was thinking something along those lines might be going on.

I'm using token replay because it is so fast and I need to evaluate a ton of models quickly, and I would love to continue using it.

But if alignements are the best approach, what would be the best way to get the %perc_fitting_traces using alignements? I don't need all the extra diagnostics.

**Comment by fit-alessandro-berti** [comment]
Dear pastra, you could use pm4py.fitness_alignments(log, net, im, fm). This will return you the percentage of fitting traces, the log fitness and the average of trace fitness.

**Comment by pastra98** [comment]
Thanks again for your pointers alessandro. I'm currently running the alignements method in my ga, and I remember again why I decided against using it at the start of my project. It can't cope with unsound models... Which is not a total showstopper because I can just assign zero fitness or kill off unsound models right at the start (would love a more gradual measure though).

But after running it several generations, it seems to be stuck forever on some model. I guess I'll need to dive into the profiler again, or (more likely) use a timeout to assign fitness 0 for models that take too long.

One more thing, with the token replay I monkey-patched the `get_aligned_traces()` method which is used by `get_replay_fitness()` to include the SHOW_PROGRESS_BAR param, because it got lost on the way there. Is this also necessary with the alignment methods? I noticed that `pm4py.fitness_alignments` is basically just a wrapper, and I tried the following to get alignements parameters, but it still showed a progress bar:

```python
from pm4py.algo.conformance.alignments.petri_net import algorithm as alignments

p = {alignments.Parameters.SHOW_PROGRESS_BAR: False}

fit = replay_fitness.apply(
    log, net, im, fm,
    variant=replay_fitness.Variants.ALIGNMENT_BASED,
    parameters=p)

print(fit)
```
Is there a way to make it disappear without a ton of "hacks"?

Anyways, the alignment approach does not seem ideal, do you have any ideas for simple fitness measures that can operate on incomplete (and potentially unsound) models and still indicate how well they fit the log?

Thanks for taking your time,
Best wishes from Vienna,
Paul

EDIT: copied the wrong import before, thats how it looks in my code

**Comment by pastra98** [comment]
If this is starting to go out of the scope of this issue, I would also love to discuss this with you via email if thats okay with you. I'm just a bit lost at the moment because my thesis hinges on a decent fitness function that I can use, and I figure you would be the best person to talk to about this

**Comment by fit-alessandro-berti** [comment]
Sure! If you drop me an email to alessandro.berti@fit.fraunhofer.de I will come back with the answers for those questions and others that you wish! Have a nice day

**Comment by pastra98** [comment]
Thx! Have a great weekend!
