### ISSUE TITLE
Publishing pm4py library on conda-forge

### ISSUE THREAD

**Issue by easygold** [process-intelligence-solutions/pm4py#302]
Hi,

First of all I would like to thank you for your open source library and the great work you are doing.

I noticed that your pm4py library is not available in the "conda-forge" channel, and because of Platform constraints where I am working, I cannot use your package directly from pip.

I would like to ask you whether it is possible to publish your lib on "conda-forge" channel as well.

Thanks in advance

**Comment by fit-alessandro-berti** [comment]
Good afternoon. Thanks for the request.

We will start the process as soon as we could. We will let you know if and when it's completed

**Comment by fit-alessandro-berti** [comment]
Dear easygold,

The Conda-forge team still did not accept our library in their ecosystem.
I am afraid I need to turn off this issue.

If there are positive news (from the Conda-forge team) I will contact you back.
