### ISSUE TITLE
Visualize arc-weights smaller than one in PetriNet

### ISSUE THREAD

**Issue by LordHeImchen** [process-intelligence-solutions/pm4py#303]
Hey guys,
first of all, big up this library! It's really neat.
Currently I am using pm4py to build a PetriNet from a custom graph-dictionary and simulate it to create event logs.
I am visualizing it using `gviz = pn_visualizer.apply(net, initial_marking)` and `pn_visualizer.view(gviz)`, where `pn_visualizer` is obtained by calling `from pm4py.visualization.petri_net import visualizer`.

Unfortunately, my petrinet from the graph-dictionary has probabilities instead of weights for the arcs, so i kind of refactored your code a bit to suit my needs. However, the `pn_visualizer` seems to only print labels on arcs when the weight is bigger than "1". Since my probabilities are 1 or below, they are not visualized.
Is there any way to tell the function to also show arc-weights as labels which are below one?
Or is there any other way to achieve this?

Any help is appreciated!
Thanks in advance

**Comment by fit-alessandro-berti** [comment]
Dear LordHelmchen,

Thanks for signaling. We'll tackle the issue in one of the upcoming releases.

Have a nice day

**Comment by fit-sebastiaan-van-zelst** [comment]
This issue was resolved in pm4py 2.2.18 (https://github.com/pm4py/pm4py-core/releases/tag/2.2.18)
