### ISSUE TITLE
Playout of a Petri Net

### ISSUE THREAD

**Issue by lll-lin** [process-intelligence-solutions/pm4py#304]
Hi,
Wow, PM4PY is very nice project, which will certainly promote the development of process mining. I would like to thank you for the great work you are doing.
I have some questions about **“Simulation”** in **“Playout of a Petri Net”**:
(1)	The generated logs from petri nets are **local completeness or global completeness**?
(2)	I input a Petri net (named example.pnml, has 12 activities) to generated an global completeness log by using “Variants.EXTENSIVE” , but report a error by **” parameters={simulator.Variants.EXTENSIVE.value.Parameters. MAX_TRACE_ LENGTH: 200})-in apply MemoryError”**
I would like to ask you whether PM4PY don’t support short loop? Because the file, example.pnml, has short loop in the exclusive branch. In addition, if the file of petri net has non-free choice, can PM4PY generate a global completeness log?

Thanks in advance

**Comment by fit-alessandro-berti** [comment]
Dear Ill-lin,

Thanks for the questions.

1) The generated logs have the property of global completeness
2) The problem is related to the huge number of traces that are possible according to your model. Seemingly the states cannot be hold entirely in memory and therefore a memory error is launched.
