### ISSUE TITLE
Extensive Playout of a Generated Process Tree 

### ISSUE THREAD

**Issue by jaripeeperkorn** [process-intelligence-solutions/pm4py#305]
I seem to generate some errors when trying to do an extensive playout of a generated process tree, generated with the build in generator.

_from pm4py.algo.simulation.tree_generator import algorithm  as tree_gen
from pm4py.algo.simulation.playout.process_tree import algorithm as tree_playout
tree = tree_gen.apply()
playout_variant = tree_playout.Variants.EXTENSIVE
param = tree_playout.Variants.EXTENSIVE.value.Parameters
simulated_log = tree_playout.apply(tree, variant=playout_variant, parameters={param.MAX_TRACE_LENGTH: 200, param.MAX_LOOP_OCC: 3, param.MAX_LIMIT_NUM_TRACES: 1000})_

The error occurs when executing the get_playout function in the algorithm and has KeyError: 'traces'. I have also played with the different parameters of the playout function and the error seems to occurs for all kinds of operators.

KR,

Jari Peeperkorn

**Comment by fit-alessandro-berti** [comment]
Dear jari,

Thanks for signaling. We'll release a fix for this in one upcoming release.

Have a nice day

**Comment by fit-sebastiaan-van-zelst** [comment]
This issue was resolved in pm4py 2.2.18 (https://github.com/pm4py/pm4py-core/releases/tag/2.2.18)
