### ISSUE TITLE
Getting heuristic_net (and others) visualizer DOT source

### ISSUE THREAD

**Issue by joaocmd** [process-intelligence-solutions/pm4py#306]
Not sure if this is a proper issue as it might consist of mostly questions.

Looking at this one in specific, but should apply to others: https://github.com/pm4py/pm4py-core/blob/release/pm4py/visualization/heuristics_net/variants/pydotplus.py#L282

I wanted to get the graph in a raw format so that I could tweak the graph's look. However, that function returns a TempFile, which I find weird as the file has already been closed by the time the return is performed which, according to [Python's docs](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile), should delete the file.
I suppose that the `write` that follows the `close` recreates the file, but is it safe to return a file object which had been closed?

Is there any way to get the `graph` object itself?

Edit: This does work
```python
gviz = visualizer.apply(heu, parameters={"format": "raw"})
visualizer.save(gviz, path)
```

But, you do not mind explaining, why return a closed file descriptor?

**Comment by fit-alessandro-berti** [comment]
Dear joaocmd,

Thanks for your questions

The closed file descriptor is related to a design choice (arguable) that was done at beginning. Probably the behavior will be changed in a future release.

In a near-future release, we will add a method to retrieve the DOT out of the HeuristicsNet graph object (which could be obtained at the moment inside the "apply" method by doing "print(graph.create_dot().decode("utf-8"))")

Have a nice day

**Comment by fit-alessandro-berti** [comment]
Dear joaocmd, we added a specific method for the retrieval of the DOT object in the current release 2.2.19

**Comment by fit-alessandro-berti** [comment]
In particular, you could call the retrieval of the Dot object using the method: pm4py.visualization.heuristics_net.visualizer.get_graph(heu_net)
