### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by Erinaceida** [process-intelligence-solutions/pm4py#307]
Hi all, 

pm4py seems like a great package, but the out of date documentation makes it so much less useful. 
Is this the way to get the most recent version of the documentation? https://pm4py.fit.fraunhofer.de/documentation#importing

If not, could you let us know where we should look for an up to date version? if such doesn't exist, when/if can we expect the docs to be updated? 

Thank you!

**Comment by fit-alessandro-berti** [comment]
Good morning!

Thanks for signaling.
Despite the documentation is still not based on the new simplified API, I would expect all the commands provided in the current version to be still completely working (we do not have intention to drop them at the moment).

If you find any functional problem (examples that do not work anymore in the current version), please let us know for an immediate fix.

**Comment by fit-sebastiaan-van-zelst** [comment]
Dear @Erinaceida ,

We are planning to significantly update/change our library and corresponding documentation (i.e., migrating to sphinx).
Please stay tuned for updates.

In the meanwhile, as @fit-alessandro-berti mentioned, the current documentation is largely in sync with our code base.
