### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by tzepterbvv** [process-intelligence-solutions/pm4py#308]
Because I plan to use your image in production environment I checked it with trivy for vulnerabilities ("trivy --exit-code 1 --ignore-unfixed pm4py/pm4py-core:latest"). The result was that:
[temp.txt](https://github.com/pm4py/pm4py-core/files/7923610/temp.txt)

In summary:
2022-01-24T08:41:14.004+0100    INFO    Detected OS: debian
2022-01-24T08:41:14.004+0100    INFO    Detecting Debian vulnerabilities...
2022-01-24T08:41:14.140+0100    INFO    Number of language-specific files: 1
2022-01-24T08:41:14.140+0100    INFO    Detecting python-pkg vulnerabilities...

pm4py/pm4py-core:latest (debian 11.1)
=====================================
Total: 54 (UNKNOWN: 0, LOW: 4, MEDIUM: 25, HIGH: 24, CRITICAL: 1)

Could you fix it?
Thx, Tobi

**Comment by fit-alessandro-berti** [comment]
Dear tzepterbvv,

Thanks for signaling. We'll take care of it in the upcoming release

Have a nice day
Ale

**Comment by fit-alessandro-berti** [comment]
Dear tzepterbvv,

We have updated the Docker image on the Docker hub.

pm4py/pm4py-core:latest (debian 11.2)
=====================================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

**Comment by fit-sebastiaan-van-zelst** [comment]
Dear @tzepterbvv,

Hopefully, the recent update of the Docker image on Docker hub is suitable for your project.
We would like to point out that pm4py is licensed under GPL, and, we expect that you comply to the license.
If this is not the case, i.e., you would like to use pm4py in a closed-source environment, please contact us via pm4py@fit.fraunhofer.de
