### ISSUE TITLE
Strange behavior when importing a petri net from the PDC 2020

### ISSUE THREAD

**Issue by joLahann** [process-intelligence-solutions/pm4py#311]
Hi,

I did some experiments with the data from the PDC 2020. In particular, I replayed a log against a petri net and tried to reproduce the classification in the ground truth log. However, I examined a strange behavior. If I load the petri net multiple times and replay it against the same case of the log, sometimes this case is marked as fitting and sometimes as non-fitting. I added the link to the experiment below. It would be very helpful if you could have a look at it and tell me if I missed something or if I found a bug in the PNML-Importer.

https://colab.research.google.com/drive/1t0HE0kMe_v3K89h3ilv8i0VvqjPImBYf?usp=sharing#scrollTo=pNJuzWnA-VRd

Thanks in advance.

**Comment by fit-alessandro-berti** [comment]
Dear joLahann, the models of PDC 2020 contains duplicate transitions, which are currently not managed by the heuristics of TBR. We therefore invite you to use the conformance / fitness / precision methods offered by alignments.

In particular, the following models of PDC 2020 contains duplicates:

pdc_2020_0000010.pnml {'t35': 2, 't62': 2}
pdc_2020_0000110.pnml {'t35': 2, 't62': 2}
pdc_2020_0001010.pnml {'t35': 2, 't62': 2}
pdc_2020_0001110.pnml {'t35': 2, 't62': 2}
pdc_2020_0010000.pnml {'t91': 3, 't11': 3}
pdc_2020_0010010.pnml {'t35': 2, 't91': 3, 't11': 3, 't62': 2}
pdc_2020_0010100.pnml {'t91': 3, 't11': 3}
pdc_2020_0010110.pnml {'t35': 2, 't11': 3, 't62': 2, 't91': 3}
pdc_2020_0011010.pnml {'t35': 2, 't62': 2}
pdc_2020_0011110.pnml {'t35': 2, 't62': 2}
pdc_2020_0100010.pnml {'t42': 2, 't35': 2, 't62': 2}
pdc_2020_0100110.pnml {'t62': 2, 't42': 2, 't35': 2}
pdc_2020_0101010.pnml {'t35': 2, 't62': 2}
pdc_2020_0101110.pnml {'t62': 2, 't35': 2}
pdc_2020_0110000.pnml {'t11': 3, 't91': 3}
pdc_2020_0110010.pnml {'t11': 3, 't42': 2, 't91': 3, 't35': 2, 't62': 2}
pdc_2020_0110100.pnml {'t11': 3, 't91': 3}
pdc_2020_0110110.pnml {'t11': 3, 't62': 2, 't42': 2, 't91': 3, 't35': 2}
pdc_2020_0111010.pnml {'t35': 2, 't62': 2}
pdc_2020_0111110.pnml {'t62': 2, 't35': 2}
pdc_2020_0200010.pnml {'t42': 2, 't35': 2, 't62': 2, 't75': 2}
pdc_2020_0200110.pnml {'t42': 2, 't62': 2, 't35': 2, 't75': 2}
pdc_2020_0201010.pnml {'t35': 2, 't62': 2}
pdc_2020_0201110.pnml {'t35': 2, 't62': 2}
pdc_2020_0210000.pnml {'t91': 3, 't11': 3}
pdc_2020_0210010.pnml {'t35': 2, 't75': 2, 't91': 3, 't11': 3, 't42': 2, 't62': 2}
pdc_2020_0210100.pnml {'t91': 3, 't11': 3}
pdc_2020_0210110.pnml {'t35': 2, 't91': 3, 't11': 3, 't75': 2, 't42': 2, 't62': 2}
pdc_2020_0211010.pnml {'t35': 2, 't62': 2}
pdc_2020_0211110.pnml {'t35': 2, 't62': 2}
pdc_2020_1000010.pnml {'t35': 2, 't62': 2}
pdc_2020_1000110.pnml {'t35': 2, 't62': 2}
pdc_2020_1001010.pnml {'t35': 2, 't62': 2}
pdc_2020_1001110.pnml {'t35': 2, 't62': 2}
pdc_2020_1010000.pnml {'t91': 3, 't11': 3}
pdc_2020_1010010.pnml {'t35': 2, 't62': 2, 't11': 3, 't91': 3}
pdc_2020_1010100.pnml {'t91': 3, 't11': 3}
pdc_2020_1010110.pnml {'t35': 2, 't11': 3, 't91': 3, 't62': 2}
pdc_2020_1011010.pnml {'t35': 2, 't62': 2}
pdc_2020_1011110.pnml {'t35': 2, 't62': 2}
pdc_2020_1100010.pnml {'t62': 2, 't35': 2, 't42': 2}
pdc_2020_1100110.pnml {'t35': 2, 't62': 2, 't42': 2}
pdc_2020_1101010.pnml {'t35': 2, 't62': 2}
pdc_2020_1101110.pnml {'t35': 2, 't62': 2}
pdc_2020_1110000.pnml {'t91': 3, 't11': 3}
pdc_2020_1110010.pnml {'t35': 2, 't11': 3, 't42': 2, 't91': 3, 't62': 2}
pdc_2020_1110100.pnml {'t91': 3, 't11': 3}
pdc_2020_1110110.pnml {'t35': 2, 't91': 3, 't62': 2, 't11': 3, 't42': 2}
pdc_2020_1111010.pnml {'t35': 2, 't62': 2}
pdc_2020_1111110.pnml {'t35': 2, 't62': 2}
pdc_2020_1200010.pnml {'t75': 2, 't42': 2, 't35': 2, 't62': 2}
pdc_2020_1200110.pnml {'t35': 2, 't42': 2, 't75': 2, 't62': 2}
pdc_2020_1201010.pnml {'t35': 2, 't62': 2}
pdc_2020_1201110.pnml {'t35': 2, 't62': 2}
pdc_2020_1210000.pnml {'t11': 3, 't91': 3}
pdc_2020_1210010.pnml {'t35': 2, 't91': 3, 't75': 2, 't42': 2, 't11': 3, 't62': 2}
pdc_2020_1210100.pnml {'t11': 3, 't91': 3}
pdc_2020_1210110.pnml {'t35': 2, 't75': 2, 't91': 3, 't62': 2, 't11': 3, 't42': 2}
pdc_2020_1211010.pnml {'t35': 2, 't62': 2}
pdc_2020_1211110.pnml {'t35': 2, 't62': 2}

**Comment by joLahann** [comment]
Ok, thanks a lot. With alignment-based fitness, it works as expected.
