### ISSUE TITLE
Unable to extract additional intra/inter case features

### ISSUE THREAD

**Issue by darjooling86** [process-intelligence-solutions/pm4py#314]
Hi,

I would like to extract features like WIP, resource workload and the case duration together with the case id. The documentation points out to include these features as boolean parameters to the log_to_features.apply() method. Unfortunately, I receive an empty data and feature_names object. Could you please let me know, what I am missing here?

Thank you very much!
Dom

```
from pm4py.objects.log.importer.xes import importer as xes_importer

log = xes_importer.apply("/Users/xxx/PM4Py/tests/input_data/receipt.xes")

from pm4py.algo.transformation.log_to_features import algorithm as log_to_features

data, feature_names = log_to_features.apply(log, parameters={"str_ev_attr": [],
                                                             "str_tr_attr": [], 
                                                             "num_ev_attr": [], 
                                                             "num_tr_attr": [], 
                                                             "str_evsucc_attr": [],
                                                             "ADD_CASE_IDENTIFIER_COLUMN":True, 
                                                             "ENABLE_WORK_IN_PROGRESS":True, 
                                                             "ENABLE_WORK_IN_PROGRESS":True, 
                                                             "ENABLE_CASE_DURATION":True})
```

**Comment by fit-alessandro-berti** [comment]
Dear darjooling86, please consider the following (lower-case the string key of the parameters; the uppercase is for the parameters specification using the log_to_features.Parameters object)

from pm4py.objects.log.importer.xes import importer as xes_importer

log = xes_importer.apply("/Users/xxx/PM4Py/tests/input_data/receipt.xes")

from pm4py.algo.transformation.log_to_features import algorithm as log_to_features

data, feature_names = log_to_features.apply(log, parameters={"str_ev_attr": [],
                                                             "str_tr_attr": [],
                                                             "num_ev_attr": [],
                                                             "num_tr_attr": [],
                                                             "str_evsucc_attr": [],
                                                             "add_case_identifier_column": True,
                                                             "enable_work_in_progress": True,
                                                             "enable_case_duration": True})
print(feature_names)

**Comment by darjooling86** [comment]
Thank you for the quick response!
