### ISSUE TITLE
Filtered event log: Unable to retrieve trace attribute values

### ISSUE THREAD

**Issue by darjooling86** [process-intelligence-solutions/pm4py#315]
Hi,

I experience an unexpected behavior with a filtered event log. After filtering the event log, I cannot retrieve the case IDs (case:concept:name) as an attribute with the method get_attribute_values. It returns an empty dictionary. After converting the log into a pandas dataframe, the get_attribute_values-method returns the expected value. Apparently that happens for alle trace attributes with the prefix "case:". Please the see the screenshot for reproduction.

Thank you
<img width="2195" alt="Bildschirmfoto 2022-02-05 um 14 34 00" src="https://user-images.githubusercontent.com/5329294/152644286-202af2b0-7449-4a6c-a9a5-d5039c520593.png">
.

**Comment by fit-alessandro-berti** [comment]
Dear darjooling86,

In order to retrieve the attributes at the case level in an EventLog, please use the command pm4py.get_trace_attribute_values(log, attribute_name)
