### ISSUE TITLE
More unused Parameters in PTAndLogGenerator

### ISSUE THREAD

**Issue by sarahsporck** [process-intelligence-solutions/pm4py#316]
There are still more parameters that are not yet implemented in the log generator, such as `INFREQUENT` ([reference usage](https://github.com/tjouck/PTandLogGenerator/blob/b0a96060a061d5fee13f458d5c6a6bce9601ddcb/source/generateTree.py#L380)), `UNFOLD`, `LT_DEPENDENCY` and `MAX_REPEAT` ([reference usage](https://github.com/tjouck/PTandLogGenerator/blob/b0a96060a061d5fee13f458d5c6a6bce9601ddcb/source/add_naive_dependencies.py#L222)). Those parameters are very important to genereate event logs with a certain amount of noise. Would it be possible to implement those?
Thanks a lot!

**Comment by fit-alessandro-berti** [comment]
Thank you for signaling. With the current version, we are targeting our ProcessTree object (which is quite standard), without any specific additions (e.g. probabilities).

We would work this issue on a long-term perspective (e.g., modifying our concept of process tree and all related algorithms, for example the playout).

**Comment by jaripeeperkorn** [comment]
The SILENT parameter does not work as well. E.g. putting it at 0.0 still results in silent activities to be generated under choice nodes.

**Comment by fit-alessandro-berti** [comment]
Dear jari, do you have the issue in the last PM4Py (2.2.19.1) ?

**Comment by jaripeeperkorn** [comment]
I think it is ok now.
