### ISSUE TITLE
How to display the Petri Net through the web instead of the svg picture.

### ISSUE THREAD

**Issue by DAAworld** [process-intelligence-solutions/pm4py#317]
We want to use javascript to render the Petri Net generated by PM4Py not svg picture.But I have no idea to convert Petri Net python object to JSON.And is it right way to convert python object to JSON?Could you give me some methods to solve this problem?

**Comment by fit-alessandro-berti** [comment]
Dear DAAworld,

Please consider the usage of the method "serialize" offered by common PM4Py visualizations.
You can provide this as output of the webservice and embed it into a DIV:
<div id="trial"></div><script type="text/javascript">document.getElementById('trial').innerHTML = svgSerializationContent;</script>

import pm4py
from pm4py.visualization.bpmn import visualizer as bpmn_visualizer

log = pm4py.read_xes("C:/running-example.xes")
bpmn_graph = pm4py.discover_bpmn_inductive(log)
gviz = bpmn_visualizer.apply(bpmn_graph, parameters={"format": "svg"})
output = bpmn_visualizer.serialize(gviz)
print(output)

**Comment by aditya11ad** [comment]
hi @DAAworld,
have u converted the nets to json .?

**Comment by DAAworld** [comment]
> hi @DAAworld, have u converted the nets to json .?
No， I used dfg。
