### ISSUE TITLE
Parameter access for reading & writing objects is too limited

### ISSUE THREAD

**Issue by gregvanhoudt** [process-intelligence-solutions/pm4py#318]
## Issue
Functions like `pm4py.read_xes()`, `pm4py.fitness_alignments`, and `pm4py.fitness_alignments` support a number of parameters in their underlying `apply` functions. However, these "shortcuts" don't allow passing parameters to these underlying functions. Therefore, from the moment I, for example, want to hide the progress bars, I need statements like `from pm4py.objects.log.importer.xes.importer import apply as log_importer` to easily do so.

## Expected solution
Add an argument to the pm4py quick functions to customise the parameters in the background, making i.e. `pm4py.read_xes()` more attractive to use.

**Comment by gregvanhoudt** [comment]
## Why can it be important
To illustrate, I am working on the Flemish Supercomputer which redirects prints to the console to a log file automatically. The resulting file then looks like this:
![image](https://user-images.githubusercontent.com/55534825/157432850-94d2ccb1-69bc-41fb-b2d1-5759cba0b11b.png)

Especially when doing parallel computations, important logged messages easily get lost in between the progress bars being printed again and again.

**Comment by fit-alessandro-berti** [comment]
Dear Greg,

We will consider changing the current behavior (i.e., allowing for more parameters in the simplified interface) in a future release. This would indeed be very useful.

Have a nice day
