### ISSUE TITLE
Progress bar seemingly unhideale in token-based precision computations

### ISSUE THREAD

**Issue by gregvanhoudt** [process-intelligence-solutions/pm4py#321]
In the module `pm4py.algo.evaluation.precision.algorithm`, the variants both have a parameter `show_progress_bar`. In the alignment-based variant, this one is considered during execution of the algorithm, however, the token-based ETConformance variant does not feed its value forward. Therefore, setting the `show_progress_bar` parameter to False does not actually hide it.

**Comment by fit-alessandro-berti** [comment]
Dear Greg,

Thanks for signaling. We will release a fix for this in an upcoming release.

Cheers

**Comment by fit-alessandro-berti** [comment]
Dear greg,

The issue is resolved in the current release.

Have a nice day

Sincerely
Alessandro
