### ISSUE TITLE
RuntimeWarning while using petri net playout: invalid value encountered in double_scalars

### ISSUE THREAD

**Issue by Bamboooom** [process-intelligence-solutions/pm4py#325]
Hello all,

first of all, thank you for the great package! 

I would like to ask for help in regard to the module `pm4py.algo.simulation.playout.petri_net.simulator`. 
I wanted to combine heuristic miner with petri net playout to get earth mover distance, but it failed on RuntimeWarning. So I would like to ask if the combinition is possible at all. My code snippet is as follows:
```
def emd_log(log):
    net, im, fm = heuristics_miner.apply(log, parameters={heuristics_miner.Variants.CLASSIC.value.Parameters.DEPENDENCY_THRESH: 0.5})
    language = variants_module.get_language(log)
    simulated_log = simulator.apply(net=net, initial_marking=im, final_marking=fm,
                                   parameters = {simulator.Variants.STOCHASTIC_PLAYOUT.value.Parameters.NO_TRACES: 100,
                                                 simulator.Variants.STOCHASTIC_PLAYOUT.value.Parameters.LOG: log},
                                   variant = simulator.Variants.STOCHASTIC_PLAYOUT)
    model_language = variants_module.get_language(simulated_log)
    emd = emd_evaluator.apply(model_language, language)
    return emd

this_emd = emd_log(log)
```
My issues are:
1. The code above throws the warning below and can't execute
```
RuntimeWarning: invalid value encountered in double_scalars
x = np.asarray((x - loc)/scale, dtype=dtyp) 
```
2. simulator.apply() only works if I specify the log, which I would think should be optional. Maybe I have some misunderstanding here, but shouldn‘t the playout possible based solely on the process model?

I would appraciate any tips on this situation. I am aware that alpha miner works with petri net playout, and pm4py.algo.simulation.montecarlo.simulator also works as an alternative. Just curious if there’s any way to integrate heuristic miner into earth mover distance.

Thank you very much!
Best regards,
Luana

**Comment by fit-alessandro-berti** [comment]
Dear Luana,

The warning is not precluding to the correct execution of the operation.

The playout is going to be stuck in many of the models produced by the heuristics miner (even if they are workflow nets, there are no guarantees for soudness)
