### ISSUE TITLE
Performance improvement for conformance checking

### ISSUE THREAD

**Issue by Bamboooom** [process-intelligence-solutions/pm4py#326]
Hello all,

I would like to ask for advice on how to improve performance, i.e. reduce run time for conformance checking. 

What takes particularly long for me are the modules `pm4py.algo.conformance.alignments.petri_net.algorithm` and `pm4py.algo.simulation.playout.petri_net.algorithm`. I used them for the famous BPIC data for e.g. the year 2012 and 2017, devided into small pieces of 100 cases and 90+ variants. The runtime of the analysis of such a piece easily exceeds 20 mins, and varies a lot from piece to piece of the similar size. And the whole log contains 200 - 300 pieces in total, so it gets really hard to execute.

My device is not high-end, with 
Processor: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
RAM: 8.00 GB

Also tried on device with 16 GB RAM, had visible improvement but still needed often more than 20 mins for a piece.

I would appreciate any tips on performance improvement. If you need more detail on the data/ how I load it etc., please let me know.

Thank you!

Best regards,
Luana

**Comment by fit-alessandro-berti** [comment]
Dear Bamboooom,

Alignments require an extensive search of the state space, this makes them very complicated for big logs / models.

One quick check you could do is about the linear solver that is used to determine the heuristics. This can be obtained by doing print(pm4py.util.lp.solver.DEFAULT_LP_SOLVER_VARIANT). The most efficient solver we have is cvxopt.

Alternatively, you could try the DIJKSTRA_LESS_MEMORY variant of the alignments, which is not active by default but on some models may work more efficiently than the heuristics-based versions.

**Comment by Bamboooom** [comment]
Hi fit-alessandro-berti，

thank you for the timely reply!

Upon check, my default solver was already set to cvxopt, so I tried the DIJKSTRA_LESS_MEMORY variant of the alignments with the following code with an excerpt of BPIC2017 data:
```
aligned_traces = alignments.apply_log(log, net, im, fm,
                                      variant=alignments.Variants.DIJKSTRA_LESS_MEMORY)
```
Then I ran into the following AttributeError:
```
variant=alignments.Variants.DIJKSTRA_LESS_MEMORY)
Traceback (most recent call last):

  File "<ipython-input-20-8722bb6a8e53>", line 2, in <module>
    variant=alignments.Variants.DIJKSTRA_LESS_MEMORY)

  File "C:\Users\lea_i\Anaconda3\lib\enum.py", line 348, in __getattr__
    raise AttributeError(name) from None

AttributeError: DIJKSTRA_LESS_MEMORY
```

I am using the version 2.2.20, installed through pip. Did I miss something else here?

Thanks a lot!
Best regards

**Comment by fit-alessandro-berti** [comment]
I suggested you an incomplete naming of the variant. The following example works:

import pm4py
from pm4py.algo.conformance.alignments import algorithm as alignments

log = pm4py.read_xes("C:/running-example.xes")
net, im, fm = pm4py.discover_petri_net_inductive(log)
aligned_traces = alignments.apply(log, net, im, fm, variant=alignments.Variants.VERSION_DIJKSTRA_LESS_MEMORY)
print(aligned_traces)

**Comment by Bamboooom** [comment]
Ahh right, thanks!

The documentation here also missed the "VERSION_" btw: https://pm4py.fit.fraunhofer.de/documentation#:~:text=Variants.DIJKSTRA_LESS_MEMORY

regards

**Comment by fit-alessandro-berti** [comment]
Dear Bambooooom,

Thanks for signaling. We proceed to correct the documentation in the website.
