### ISSUE TITLE
The problem of eventually follows relationship  

### ISSUE THREAD

**Issue by Ichiruchan** [process-intelligence-solutions/pm4py#327]
I want filter my dataframe according to the order of list [A, B, C ...]. Actually, i could find a lot of functions to realize it. According to the comments in source code, I used `from pm4py.algo.filtering.pandas.ltl.ltl_checker import eventually_follows` and `mode1 = eventually_follows(my_data, ["order", "operation"])`. And the filtered result is strange 
![企业微信截图_b8731fa6-38c4-4393-b8dd-81e84900871f](https://user-images.githubusercontent.com/61850562/163304945-2d4c1a80-3375-4dd1-84cd-a19c056ec6d4.png)

**Comment by fit-alessandro-berti** [comment]
Dear Ichiruchan,

The eventually follows filter has had some problems in the previous releases. Please ensure to use the latest version of PM4Py (pip install -U pm4py).

Then you can use it as follows and it works as expected:

import pm4py
import pandas as pd

dataframe = pd.read_csv("C:/running-example.csv")
dataframe = pm4py.format_dataframe(dataframe)
filtered_log = pm4py.filter_eventually_follows_relation(dataframe, [("register request", "check ticket", "reinitiate request")])

**Comment by Ichiruchan** [comment]
Actually, my version is 
![image](https://user-images.githubusercontent.com/61850562/163366514-94e27bb9-d755-4551-bade-b719d6745813.png). I will try your suggestion. Thank you very much

**Comment by Ichiruchan** [comment]
I executed pip command. (And i think before this time, i have already used the latest version). It still gave me a wrong result .
![image](https://user-images.githubusercontent.com/61850562/163376956-09ba0fb6-ec4d-43a9-8315-81d8c531c656.png)

**Comment by fit-alessandro-berti** [comment]
Thank you for the detailed error description.
We understood your problem.
Before we release the proper fix, I would like to invite you to use the following command before the filter is applied:

dataframe = dataframe.reset_index()

**Comment by Ichiruchan** [comment]
> Thank you for the detailed error description. We understood your problem. Before we release the proper fix, I would like to invite you to use the following command before the filter is applied:
> 
> dataframe = dataframe.reset_index()

Once i reseted index, the function runs correctly. I think the order of index is important for the follow function.  So it is a good habit to sort timestamp with case id and reset index after sorting timestamp. Thanks a lot for your reply.

**Comment by fit-alessandro-berti** [comment]
Thank you for your bug signaling
