### ISSUE TITLE
How to convert general log files into "pm4py/notebooks/data/running_example.csv"

### ISSUE THREAD

**Issue by ghost** [process-intelligence-solutions/pm4py#328]
How to convert general log files into "pm4py/notebooks/data/running_example.csv"

**Comment by fit-alessandro-berti** [comment]
Dear HanamakiX, the following commands can be used to export any log file in PM4Py to a Pandas dataframe, which can be stored in CSV:

import pm4py

dataframe = pm4py.convert_to_dataframe(event_log)
dataframe.to_csv('running-example.csv', index=False)
