### ISSUE TITLE
Frequency Annotation of a Process Tree - Sepsis Event Log

### ISSUE THREAD

**Issue by henrikkirchmann** [process-intelligence-solutions/pm4py#331]
Hello,

I am wondering if the frequency annotation of the process tree works correctly with the Sepsis Event Log, https://data.4tu.nl/articles/dataset/Sepsis_Cases_-_Event_Log/12707639. I have two issues:

**1.** Tau leaf nodes don't have any frequency information. In one exception, the first tau node you encounter in a breadth-first search from the root. It has presumably the event frequency of all tau nodes in the tree. I think this is a result of line ​​55 in [pm4py/algo/conformance/alignments/process_tree/util/search_graph_pt_frequency_annotation.py](https://github.com/pm4py/pm4py-core/blob/release/pm4py/algo/conformance/alignments/process_tree/util/search_graph_pt_frequency_annotation.py):

`bottomup_nodes = bottomup.get_bottomup_nodes(pt, parameters=parameters)
`

I think bottomup_nodes should include all nodes of the process tree, but it only holds the first tau you encounter in a breadth-first search from the root. In _bottomup.get_bottomup_nodes(pt, parameters=parameters)_ in line 214 in [pm4py/objects/process_tree/utils/bottomup.py](https://github.com/pm4py/pm4py-core/blob/release/pm4py/objects/process_tree/utils/bottomup.py)  we define _all_nodes_ as a set. I think it should also include all nodes of the process tree, but again, after its computation it holds only the first tau you encounter in a breadth-first search from the root. Because _all_nodes_ is a set, _all_nodes_ will not add other tau nodes after the first tau node has was added.  

**2.** The frequency of some non-leaf nodes seem to be incorrect. For instance, the highlighted xor in the process tree below has a case frequency of 908. I think as a child of a seq-node, the xor-node should share the case frequency of 1050 of its parent. This is also visible in the highlighted part of the frequency annotated Petri net below. The event frequency of 1568 also seems wrong, the seq-parent has an event frequency of 1896. Do we count the event frequency of a xor-node in the frequency annotation if the executed child node is a tau? 

The frequency annotated process tree: 

![Sepsis PT](https://user-images.githubusercontent.com/22832118/171297530-44762f5e-83aa-4550-a721-b4a555d61b83.png)

The frequency annoated 

![Petri net Sepsis](https://user-images.githubusercontent.com/22832118/171297647-1016519e-4649-48cf-b657-5c8c04cb04c0.png)

Thanks in advance for your help :)

**Comment by fit-alessandro-berti** [comment]
Dear henrikkirchmann,

The frequency annotation on the process trees is based on a still un-published alignments approach on process trees.

The implementation of this alignments approach does still not permit to look in detail to the number of times a tau leaf is executed. Instead, the frequency numbers on the visible activities are equivalent to what you obtained with the token-based-replay based visualization on the Petri nets. In future, when this alignments approach is more established, we could integrate the events/case frequency on top of the tau leaf nodes.

Also, the case/events frequency that you consider on the operators is heavily influenced by the presence of the loop. Hence, in this visualization you could consider as fully agreeable only the cases/events frequency on the visible nodes. Which is indeed the only frequency that is displayed in the represnetation.
