### ISSUE TITLE
why using pm4py.get_variants_as_tuples function, I get an error "KeyError: 'concept:name'"

### ISSUE THREAD

**Issue by DAAworld** [process-intelligence-solutions/pm4py#332]
When I use my own csv log,using pm4py.get_variants_as_tuples function and I get an error "KeyError: 'concept:name'".
I find that my csv log's column has't "concept:name" and get_variants_as_tuples function just accept one params named "log".
Please tell me what should I do next and how to handle your own log, not example log；

**Comment by fit-alessandro-berti** [comment]
Dear DAAworld,

In the current version of PM4Py, you need to use the function format_dataframe to ensure that the naming of the columns and the type of the variables is in line with the current implementation.

See https://pm4py.fit.fraunhofer.de/static/assets/api/2.2.18/pm4py.html#pm4py.utils.format_dataframe for more information

**Comment by DAAworld** [comment]
> Dear DAAworld,
> 
> In the current version of PM4Py, you need to use the function format_dataframe to ensure that the naming of the columns and the type of the variables is in line with the current implementation.
> 
> See https://pm4py.fit.fraunhofer.de/static/assets/api/2.2.18/pm4py.html#pm4py.utils.format_dataframe for more information

Think you very much！This is very useful to me.
