### ISSUE TITLE
Error filtering on timeframe

### ISSUE THREAD

**Issue by rsalas90** [process-intelligence-solutions/pm4py#335]
When trying to filter on timeframe I receive the following error:

filtered_log = timestamp_filter.filter_traces_contained(log, "2011-01-06 15:06:00", "2022-06-30 17:56:31")

_TypeError: replace() takes no keyword arguments filter traces pm4py_

**Comment by fit-alessandro-berti** [comment]
Dear rsalas, try to verify the type of the variable log (print(type(log))).

I can ensure that examples like the following are working well in the current release:


import pm4py

log = pm4py.read_xes("tests/input_data/receipt.xes")
print(type(log))

from pm4py.algo.filtering.log.timestamp import timestamp_filter
filtered_log = timestamp_filter.filter_traces_contained(log, "2011-03-09 00:00:00", "2012-01-18 23:59:59")

**Comment by rsalas90** [comment]
As you can see, the type is an eventlog object
![eventlog](https://user-images.githubusercontent.com/32952307/175046231-9bbd6592-c0da-44f7-ae6a-9311184e7863.jpg)

**Comment by rsalas90** [comment]
In the same way, if I want to see the frequency along with the Petrinet after applying alpha miner algorithm I receive the following error. What could be happening?
![image](https://user-images.githubusercontent.com/32952307/175052715-70e67ee7-dd66-42f7-8985-2135ae61d62b.png)

**Comment by fit-alessandro-berti** [comment]
Ok it's not the typing.

I think that the problem is that the type of the timestamp variable in your events (time:timestamp) is string. This can be corrected as in the following example using the module [dateutil](https://pypi.org/project/python-dateutil/):

>>> import pm4py
>>> import pandas as pd
>>> dataframe = pd.read_csv("C:/receipt.csv")
>>> log = pm4py.convert_to_event_log(dataframe)
>>> from dateutil.parser import parse
>>> for trace in log:
...     for event in trace:
...             event["time:timestamp"] = parse(event["time:timestamp"])

**Comment by rsalas90** [comment]
Thank you! That's was the problem, now it's working properly! I had to modify previously the type of the timestamp:

pd.to_datetime(df.TIMESTAMP_).dt.tz_localize('UTC')

**Comment by fit-alessandro-berti** [comment]
You're welcome!
