### ISSUE TITLE
log_skeleton issues

### ISSUE THREAD

**Issue by ccjake** [process-intelligence-solutions/pm4py#336]
Hello,

I am a master student and trying to implement log_skeleton myself based on the paper. For the testing purposes, I used the log_skeleton function to get the model. 

I tried a log with following result.
<img width="1515" alt="截屏2022-06-24 18 56 40" src="https://user-images.githubusercontent.com/37229189/175613276-9d9384ba-343a-4ef4-a8fb-97034ea9c5d7.png">

After modification of the log file, I get another result.
<img width="1532" alt="截屏2022-06-24 19 00 26" src="https://user-images.githubusercontent.com/37229189/175613404-3ee3dc35-b699-4d68-975d-0e9dd6009367.png">

You can the the always_before related activities up from 6 pairs to 6 pairs.(my answer is also 6 pairs)

The only difference between these two logs is that on the first log, there are two consecutive occurrences in one trace. (in the log results to 3 pairs)
<img width="1223" alt="截屏2022-06-24 19 03 23" src="https://user-images.githubusercontent.com/37229189/175613825-7bf2be60-f2b2-4e20-b5c4-987b22b5100c.png">

According to the paper _Log Skeletons: A Classification Approach to Process Discovery_, always_before defined as follow:
<img width="872" alt="截屏2022-06-24 19 41 03" src="https://user-images.githubusercontent.com/37229189/175613941-69636577-cc89-4a17-aa23-c2117e83ae38.png">

It's pretty confusing why the consecutive occurrences of the same activity in one trace would cause this relation to be violated.

Here are two logs I used for test.
[logs.zip](https://github.com/pm4py/pm4py-core/files/8978874/logs.zip)

It that a bug or am I missing something? 
Thanks for any answer!

**Comment by fit-alessandro-berti** [comment]
Good morning.

Thanks for signaling the problem. It seems that there is a bug in the detection of the always_before relation. We'll keep you informed

**Comment by fit-alessandro-berti** [comment]
As discussed by e-mail, a solution of the problem is identified.
