### ISSUE TITLE
What is the difference between the function of "get_partial_order_dataframe" and "get_dfg_graph"?

### ISSUE THREAD

**Issue by DAAworld** [process-intelligence-solutions/pm4py#341]
get_partial_order_dataframe->"from pm4py.algo.discovery.dfg.adapters.pandas.df_statistics import get_partial_order_dataframe"
get_dfg_graph->"from pm4py.algo.discovery.dfg.adapters.pandas.df_statistics import get_dfg_graph"

I found that two funtions all can return two nodes followed and their count  such as [{(a, b):3}].But their result are different.For examples,one return {(a, b):3}, and the other return {(a, b): 10}.
I don't understand why the returned result is not the same and which function I should use.
Please teache me how to apply them

**Comment by fit-alessandro-berti** [comment]
Dear DAAworld,

The first function discovers the eventually follows graph, while the second the directly-follows graph.
The eventually follows graph considers also indirect relationships between events.

As example, if the log contains just the trace ABCD, the directly-follows graph would be {(A,B): 1, (B,C): 1, (C,D):1}, while the eventually-follows graph would be {(A,B): 1, (B,C): 1, (C,D):1, (A,C):1, (A,D): 1, (B,D): 1}

**Comment by DAAworld** [comment]
> Ok，Thank you very much for your guidance.I already understand.
