### ISSUE TITLE
BPMN export positioning broken

### ISSUE THREAD

**Issue by SchererM99** [process-intelligence-solutions/pm4py#348]
Hello, for our project we need the bpmn exported to make it interactive with the bpmn-visualization package. In order to do that we tried all different methods we could find in pm4py. Sadly, the layout of the resulting bpmns when imported in e.g. bpmn.io is totally different to the very nice graph when using the `pm4py.view_bpmn()` function. We do our experiments with the BPI Challenge 2019, so the event log is also quite large. Is there some function we are missing which fixes the layout? Changing the enable_layout parameter in write_bpmn did not change the results. 

Code & Examples:
<h4> Converting from Petri Net </h4>

```
from pm4py.objects.log.importer.xes import importer as xes_importer
from pm4py.algo.discovery.inductive import algorithm as inductive_miner

log = xes_importer.apply("bpic")
net, im, fm = inductive_miner.apply(log)
bpmn_from_petri_net = pm4py.convert_to_bpmn(net, im, fm)
pm4py.write_bpmn(bpmn_from_petri_net, "bpmn_from_petri_net_with_layout.bpmn")
```

Using `pm4py.view_bpmn()` :
![image](https://user-images.githubusercontent.com/50797129/193091037-6c0621d8-2c9e-470f-b5ef-1022471c9aea.png)

bpmn.io:
![image](https://user-images.githubusercontent.com/50797129/193091193-5f105e16-beb4-4b11-8b92-83264d6772e4.png)

<h4> Directly discover bpmn </h4>

```
bpmn_inductive = pm4py.discover_bpmn_inductive(log)
pm4py.write_bpmn(bpmn_inductive, "bpmn_inductive_with_layout.bpmn")
```

Using `pm4py.view_bpmn()` :
![image](https://user-images.githubusercontent.com/50797129/193091471-b9ca10b8-da98-46bd-812a-50620595dae0.png)

bpmn.io:
![image](https://user-images.githubusercontent.com/50797129/193091573-14799f84-3d7c-45dc-a6b4-dd32ef53ab3a.png)

<h4> Discover Process Tree then convert to bpmn </h4>

```
tree = pm4py.discover_process_tree_inductive(log)
bpmn_from_tree = pm4py.convert_to_bpmn(tree)
pm4py.write_bpmn(bpmn_from_tree, "bpmn_tree_direct_with_layout.bpmn")
```

Using `pm4py.view_bpmn()` :
![image](https://user-images.githubusercontent.com/50797129/193091870-1d675076-c763-4837-a178-c9b7fc533d9b.png)

bpmn.io:
![image](https://user-images.githubusercontent.com/50797129/193091927-f17e7639-c0d5-47d5-b174-1878d3ba99dc.png)

<h4> Discover Petri Net, convert to Process Tree and then convert to bpmn </h4>

```
tree = pm4py.convert_to_process_tree(net, im, fm)
bpmn_from_tree_pn = pm4py.convert_to_bpmn(tree)
pm4py.write_bpmn(bpmn_from_tree_pn, "bpmn_tree_pn_with_layout.bpmn")
```

Using `pm4py.view_bpmn()` :
![image](https://user-images.githubusercontent.com/50797129/193092142-828f1582-fa0c-4b7a-9584-8e200f44f3da.png)

bpmn.io:
![image](https://user-images.githubusercontent.com/50797129/193092233-56931efd-b103-4c45-a83c-835093fac556.png)

**Comment by fit-alessandro-berti** [comment]
Dear SchererM99,

Unfortunately the current BPMN layout for .bpmn files, which is based on Graphviz but needed modifications in order to satisfy the format, is not extremely usable (to use an euphemism)

Since there are no good implementations of BPMN layouting algorithms in Python, a good option can be the one of doing the layouting in the frontend. For this, I reference you to a front-end process mining library:
https://www.pm4js.org/
https://www.pm4js.org/bpmn_model.html

The idea is that you can get the current .bpmn output from PM4Py, and then layout it using the front-end library.
