### ISSUE TITLE
sequence of entries in </bpmndi:BPMNDiagram>

### ISSUE THREAD

**Issue by excubo-jg** [process-intelligence-solutions/pm4py#350]
I am parsing the bpmn output from pm4py. While the graphs generated with view_bpmn() look the same, the sequence of the object information in the .bpmn file generated by objects.bpmn.exporter does not stay the same.

Run 1:
	</bpmndi:BPMNDiagram>
	<bpmn:process id="idc990daac-5797-432b-812b-a871afb11c3a" isClosed="false" isExecutable="false" processType="None">
		<bpmn:endEvent id="id39686260-04ca-4bd7-95a9-83e7746490c5" name="end">
			<bpmn:incoming>id1dafc423-b126-460d-a0e4-a4b4f0c19839</bpmn:incoming>
		</bpmn:endEvent>
		<bpmn:task id="idfe6befeb-4468-4455-8691-3bc323431c23" name="pay compensation">
			<bpmn:incoming>idf8f665f5-9e5a-4fbc-a8d3-ae474b58205e</bpmn:incoming>
			<bpmn:outgoing>id4980ba50-a459-4614-a295-86dc64617188</bpmn:outgoing>
		</bpmn:task>
...

where as Run 2 of the same input file:
	</bpmndi:BPMNDiagram>
	<bpmn:process id="id9c18e4cf-6035-4649-85a9-b01fa6861590" isClosed="false" isExecutable="false" processType="None">
		<bpmn:task id="id08f07e1d-bddf-4e7f-852b-ae0378c714c5" name="check ticket">
			<bpmn:incoming>id0f2e963d-3684-4092-b214-868a556374c8</bpmn:incoming>
			<bpmn:outgoing>id127e2aee-a3a6-45fe-9644-d26095ddb7d3</bpmn:outgoing>
		</bpmn:task>
		<bpmn:exclusiveGateway id="id8e0f3125-2542-47aa-812d-5696187b660d" gatewayDirection="converging" name="">
			<bpmn:incoming>id5842aa7a-b550-4d55-8f37-d376c97176df</bpmn:incoming>
			<bpmn:incoming>id370a9de0-e669-49a7-8020-8a7526ce95bb</bpmn:incoming>
			<bpmn:outgoing>ideb335bdc-d14e-4b76-8ea0-920bf9c9112b</bpmn:outgoing>
		</bpmn:exclusiveGateway>
...

Is this expected behavior? It would be easier to compare different runs if the objects were written in the same sequence in the .bpmn-file. Actually, I was surprised to see that they are not. I'd expect the file to look the same as the input file and the processing did not change.

**Comment by fit-alessandro-berti** [comment]
Dear @excubo-jg the order of the elements in the BPMN does not affect other tools (Camunda, BPMN.JS). Due to the nature of the conversion Petri net -> BPMN we could not ensure the same ordering in all the executions (e.g. there is non-determinism involved). Also the labels are going to be generated as unique identifiers in every execution

**Comment by excubo-jg** [comment]
ok, many thanks for the explanation. I am using the name= tokens for matching so I am not impacted by the unique identifiers
