### ISSUE TITLE
Incorrect Places in Alpha Algorithm (Classic)

### ISSUE THREAD

**Issue by aarkue** [process-intelligence-solutions/pm4py#353]
Hi, thanks for maintaining PM4Py as an open-source package!

I think I stumbled upon an inconsistency of the Classic Alpha Algorithm as implemented in PM4Py compared to the definition in the original paper:

![image](https://user-images.githubusercontent.com/20766652/200124444-1095d7a6-b42d-46b5-b781-145094332b5e.png)

When generating new place candidates using the iterative approach the current implementation (in `algo/discovery/alpha/variants/classic.py`) fails to check if the new place candidate pair has causal relations between all elements of the first and second part of the pair.

Adding something like  `__check_all_causal(alpha_abstraction.causal_relation,t1[0],t2[1]) and __check_all_causal(alpha_abstraction.causal_relation,t2[0],t1[1])`  to the existing if-condition in the loop would fix this behavior.

```
def __check_all_causal(causal_relation, item_set_1, item_set_2):
    S = set(product(item_set_1, item_set_2))
    for pair in S:
        if pair not in causal_relation:
            return False
    return True
```

See for example the below attached event log. Currently PM4Py discovers 4 places for this log (one corresponding to the pair ({a,x},{c,b}) which should not be a valid place candidate). As a reference, the ProM implementation discovers the correct Petri net with 5 places.

[alpha_pm4py.xes.gz](https://github.com/pm4py/pm4py-core/files/9943991/alpha_pm4py.xes.gz)

Cheers,
Aaron

**Comment by fit-alessandro-berti** [comment]
Dear @aarkue ,

Thanks for signaling. We implemented a fix in the release 2.2.31

Have a nice Sunday
