### ISSUE TITLE
Multi filtering

### ISSUE THREAD

**Issue by ghost** [process-intelligence-solutions/pm4py#354]
Hello
am trying to apply multiple filters on my log, is there a way which i apply all at once?
This i show am trying 
```
tracefilter_log_pos = pm4py.filter_event_attribute_values(event_log, "concept:invamt", [5426,6654554], level="case", retain=True)
filtered_log = pm4py.filter_time_range(tracefilter_log_pos, "2007-07-13  00:00:00", "2008-05-03  00:00:00", mode='traces_intersecting')
pm4py.discover_dfg(filtered_log)
``` 
is it correct way what am doing. 
Please help me on applying filters on multiple columns at same time and pass it to function.

**Comment by fit-alessandro-berti** [comment]
Dear @Nanda-Incognito 

No, you need to apply them one by one. If you need to apply the same set of filters to different logs, I suggest that you create a Python function accepting the event log and returning the filtered event log.

**Comment by ghost** [comment]
Hi @fit-alessandro-berti thanks for quick response, I dint get exactly what you suggested. what you mean creating function how would i apply filters?  If you don't mind can you share me any sample reference.....

**Comment by fit-alessandro-berti** [comment]
The same way as above

def filter(event_log):
    tracefilter_log_pos = pm4py.filter_event_attribute_values(event_log, "concept:invamt", [5426,6654554], level="case", retain=True)
    filtered_log = pm4py.filter_time_range(tracefilter_log_pos, "2007-07-13  00:00:00", "2008-05-03  00:00:00", mode='traces_intersecting')
    return filtered_log


event_log = pm4py.read_xes("log.xes")
filtered_event_log = filter(event_log)

**Comment by ghost** [comment]
thanks @fit-alessandro-berti  for helping me on this.
