### ISSUE TITLE
The function that calculates the duration of a case is wrong

### ISSUE THREAD

**Issue by DAAworld** [process-intelligence-solutions/pm4py#357]
stastics->traces->generic->pandas->case_statistics->get_cases_description。
The get_cases_description function just use the log's time:timestamp as start and end time. If the log already has start and end time and  case duration = last time:timestamp - first start_timestamp. But now case duration = last time:timestamp - first time:timestamp that  is the difference of the first and end event's end time.

**Comment by fit-alessandro-berti** [comment]
Dear @DAAworld yes, that function supports the specification of only the complete timestamp key as per now.
We will change it to support the provision of a start timestamp key if possible.

**Comment by DAAworld** [comment]
> Dear @DAAworld yes, that function supports the specification of only the complete timestamp key as per now. We will change it to support the provision of a start timestamp key if possible.

OK.

**Comment by fit-alessandro-berti** [comment]
we provided support in pm4py 2.3.2 for the specification of the start timestamp in the given function.
