### ISSUE TITLE
Does “Heuristic Miner Plus Plus” support token-based replay? If support, could you share an example?

### ISSUE THREAD

**Issue by JackEnzo** [process-intelligence-solutions/pm4py#358]

**Comment by fit-alessandro-berti** [comment]
Dear @JackEnzo 

Yes. Once a Petri net was discovered with the Alpha++ algorithm, it can be used with any replay algorithm:

import pm4py

dataframe = pm4py.read_xes("tests/input_data/receipt.xes")
net, im, fm = pm4py.discover_petri_net_alpha_plus(dataframe)
replayed_traces = pm4py.conformance_diagnostics_token_based_replay(dataframe, net, im, fm)
print(replayed_traces)
aligned_traces = pm4py.conformance_diagnostics_alignments(dataframe, net, im, fm)
