### ISSUE TITLE
About PN to PT question

### ISSUE THREAD

**Issue by JackEnzo** [process-intelligence-solutions/pm4py#362]
I don't know why it doesn't work?

```
import pm4py
from pm4py.algo.discovery.heuristics.variants import plusplus
from pm4py.visualization.heuristics_net import visualizer
from pm4py.visualization.petri_net import visualizer as pn_visualizer
import pandas as pd

def execute_script():

    log = pm4py.read_xes("../tests/input_data/interval_event_log.xes")
    net1, im1, fm1 = plusplus.apply(log)
    tree = pm4py.convert_to_process_tree(net1, im1, fm1)
    print(tree)

if __name__ == "__main__":
    execute_script()
```

**Comment by fit-sebastiaan-van-zelst** [comment]
Hi JackEnzo, 

Can you upload a visualization of the Petri net discovered by the heuristic miner? It can be the case that the resulting Petri net is not a process tree. In that case, the conversion should break.

**Comment by JackEnzo** [comment]
Dear @fit-sebastiaan-van-zelst, I upload the Petri net using the Heuristics Miner ++ algorithm as following graph.
![heu_net](https://user-images.githubusercontent.com/54665296/206078409-84c4f446-bd71-496a-bb43-d53a61a7ef87.svg)

**Comment by fit-alessandro-berti** [comment]
Dear @JackEnzo 

The Petri net is not block-structured therefore it cannot be converted to a process tree using the implemented approach.

The approach is described in the paper:

"[Translating Workflow Nets to Process Trees: An Algorithmic Approach](https://www.mdpi.com/1999-4893/13/11/279)"
