### ISSUE TITLE
Last Event Not Included in filter_between

### ISSUE THREAD

**Issue by s-kimel** [process-intelligence-solutions/pm4py#366]
I am trying to use the `filter_between` function to extract just the events that are between two events. It seems like the function does not consider the last event in the `case:concept:name` when returning results. Repex is below.

```
import pm4py
import pandas as pd
from pm4py.objects.conversion.log import converter as log_converter

time = []
for i in range(17):
    time.append(pd.to_datetime('2022-01-01') + pd.Timedelta(days=i))

df = pd.DataFrame({
    'case:concept:name': ['A','A','A','A',
                          'B','B','B','B','B','B','B',
                          'C','C','C',
                          'D','D','D'],
    'concept:name': ['Task 1', 'Task 2', 'Task 3', 'Task 5',
                     'Task 1', 'Task 2', 'Task 4', 'Task 5', 'Task 4', 'Task 3', 'Task 5',
                     'Task 1', 'Task 3', 'Task 5',
                     'Task 1', 'Task 4', 'Task 5'],
    'time:timestamp': time
})

event_log = log_converter.apply(df)
test = pm4py.filter_between(event_log, 'Task 4', 'Task 5')
pm4py.convert_to_dataframe(test)
```

The output I get is:
```
  concept:name time:timestamp case:concept:name
0       Task 4     2022-01-07                 B
1       Task 5     2022-01-08                 B
```

I would expect this output:
```
  concept:name time:timestamp case:concept:name
0       Task 4     2022-01-07                 B
1       Task 5     2022-01-08                 B
2       Task 4     2022-01-09                 B
3       Task 3     2022-01-10                 B
4       Task 5     2022-01-11                 B
5       Task 4     2022-01-16                 D
6       Task 5     2022-01-17                 D
```

If I try other pairs of tasks like `pm4py.filter_between(event_log, 'Task 2', 'Task 3')` I get the expected output. It is only when I include the final task in a trace (in this case Task 5) that it does not return the expected output. Am I missing something with how the function is meant to be used? 

I am using pm4py version 2.3.3

**Comment by s-kimel** [comment]
I tried the same in version 2.2.32 and got the same unexpected result. I see that in 2.3.x that even logs are changed to use pandas dataframes instead. If I do `pm4py.filter_between(df, 'Task 4', 'Task 5')` I get the following result:
```
   case:concept:name concept:name time:timestamp
6             B##@@0       Task 4     2022-01-07
7             B##@@0       Task 5     2022-01-08
8             B##@@1       Task 4     2022-01-09
9             B##@@1       Task 3     2022-01-10
10            B##@@1       Task 5     2022-01-11
15            D##@@0       Task 4     2022-01-16
16            D##@@0       Task 5     2022-01-17
```
This has all the expected events in it. It has some additional text added to the `case:concept:name`. 

The same results occurred with `pm4py.filtering.filter_between` as well where the EventLog does not produce the expected results, but the pandas dataframe does with the additional text in the `case:concept:name`.

**Comment by fit-alessandro-berti** [comment]
Dear s-kimel,

Since potentially a case can be divided in many subcases with the application of the between filter, we need to change the case identifier in order to accomplish this. This is done by adding the suffix with 0, 1 to respectively the first and second subcase inside the case.

Thanks for signaling the bug for the EventLog implementation. we will fix that (even if the EventLog interface is deprecated)
