### ISSUE TITLE
visualization in json format for customization 

### ISSUE THREAD

**Issue by aditya11ad** [process-intelligence-solutions/pm4py#369]
Hi,
I have applied miner and created visualization by following code:

```
heu_net = heuristics_miner.apply_heu(log)

gviz = hn_visualizer.apply(heu_net)
hn_visualizer.view(gviz)
```

now I want the **json** representation of generated **graph** to be passed for customization at frontend.

Is there any method or technique for that?

thanks in advance.

**Comment by fit-alessandro-berti** [comment]
Dear @aditya11ad 

We are not providing currently a default JSON serialization for our HeuristicsNet object nor plan to introduce it in near future.

However, if you look inside the class pm4py.objects.heuristics_net.obj.HeuristicsNet  in particular inside the constructor, you see that the class is mainly based on Python dictionaries / set, which can be serialized quite easily

**Comment by aditya11ad** [comment]
thanks for the quick reply,

can u plz help me with that code of json serialization.

considering:
`heu_net = heuristics_miner.apply_heu(log)`

**Comment by aditya11ad** [comment]
hi there,
can anyone, help me , in this json generation for net plotting.
