### ISSUE TITLE
bpmn-files written without node location information

### ISSUE THREAD

**Issue by excubo-jg** [process-intelligence-solutions/pm4py#371]
`from pm4py.algo.discovery.inductive import algorithm as inductive_miner`
`from pm4py.objects.bpmn.exporter import exporter as bpmn_exporter`
...
`bpmn_exporter.apply(bpmn, "result.bpmn")` 
`pm4py.view_bpmn(bpmn, format="svg")`

displays a well-formatted svg-file but in the bpmn-file all location information is set to zero, e.g.

> <omgdc:Bounds height="100" width="100" x="0" y="0"/>

or
> <omgdi:waypoint x="0" y="0"/>

When the generated bpmn.file is opened in an bpmn-editor, all nodes are present but are drawn on top of one another...

**Comment by fit-alessandro-berti** [comment]
Dear @excubo-jg to automatically activate the layouting I invite you to use the method pm4py.write_bpmn  to persist the BPMN diagram (even if the layout is not exceptionally good)

**Comment by excubo-jg** [comment]
Dear Alessandro, now that the documentations is online again... Apologies for this.

Using write_bpmn fills the coordinates with values. These are in the range of -2800 to 6000... As there are no warning messages I suspect the rather broad range being the cause for nothing being displayed when opening the bpmn-file with the Camunda modeler. The view-bpmn command shows the expected results. Any ideas what might cause this? I am using the running-example.csv so this should not be a large diagram.

**Comment by fit-alessandro-berti** [comment]
Dear @excubo-jg 

I tried with the Camunda modeler. Seems that it can open the provided layout, but you need to scroll upwards to see the diagram (press CTRL and drag down)

While on bpmn.io it is automatically centered in the screen

![image](https://user-images.githubusercontent.com/56342194/210945316-41718396-f46e-494a-a6cb-d9cc0141f8d8.png)

**Comment by excubo-jg** [comment]
Many thanks for hunting this down - I tried the opposite direction and gave up...

Isn't this a scaling issue? The chart has the same layout as the one generated by pm4py.view_bpmn but the distance between the nodes is so large that it dwarfs the nodes. Is there any parametrization one could use to keep the distance between the nodes more in sync with the node size? The svg pm4py.view_bpmn solves this much nicer.

**Comment by fit-alessandro-berti** [comment]
Dear @excubo-jg 

We changed the positioning of the nodes in the diagram to be more neutral in pm4py 2.5.0

It is still not centered in Camunda Modeler but it should be less off.
