### ISSUE TITLE
Inconsistencies with latest version: 2.4.0 or 2.3.5?

### ISSUE THREAD

**Issue by Zoraiyo** [process-intelligence-solutions/pm4py#373]
Hello

The latest version released yesterday has different version numbers. On PyPi and the Github release has version 2.4.0, but the [CHANGELOG.md](https://github.com/pm4py/pm4py-core/blob/release/CHANGELOG.md#pm4py-235-20230106) on the release branch and in the ZIP archive lists the version 2.3.5. 
The official documentation has marked the latest release also as 2.3.5. 
![image](https://user-images.githubusercontent.com/58370727/211158779-ed765f52-49fb-415e-b225-c71849f74831.png)

**Comment by fit-alessandro-berti** [comment]
The latest release is 2.4.0 indeed

Thanks for signaling. We corrected the issue in the CHANGELOG and website
