### ISSUE TITLE
Search function on documentation website not working

### ISSUE THREAD

**Issue by goto-loop** [process-intelligence-solutions/pm4py#375]
When you open the documentation website by heading over to the [PM4Py homepage](https://pm4py.fit.fraunhofer.de/) and clicking on [Documentation](https://pm4py.fit.fraunhofer.de/static/assets/api/2.3.0/index.html), the search function through the magnifying glass on the top right does not work. Nothing happens when you click on it and there is no search field.

Browsers: Firefox and Brave (Chromium based).

**Comment by fit-alessandro-berti** [comment]
Dear @goto-loop 

Thanks for signaling. We will investigate the issue and propose a solution

**Comment by fit-alessandro-berti** [comment]
Due to an issue of the documentation theme, we decided to remove the search button for now.
