### ISSUE TITLE
 DOT serialization for the heuristic net

### ISSUE THREAD

**Issue by aditya11ad** [process-intelligence-solutions/pm4py#378]
for petri nets this is working perfect for generating DOT serialization :

`pm4py.visualization.common.gview.serialize_dot(gviz)`

Now how to get **DOT serialization** for this heuristic net :
```
heu_net = heuristics_miner.apply_heu(log)
h_gviz = hn_visualizer.apply(heu_net)

```

`------code part here------.serialize_dot(h_gviz)`

**Comment by fit-alessandro-berti** [comment]
Dear @aditya11ad 

The heuristics net visualization is not based on Graphviz therefore the DOT cannot be obtained

**Comment by aditya11ad** [comment]
plz guide me, 
how can i serialize this kind of net:
![output](https://user-images.githubusercontent.com/20943198/213981947-6bf11e85-3901-4daf-a866-6819a6f6a6d6.png)

**Comment by fit-alessandro-berti** [comment]
If you want to encode the figure: save it in SVG, send the XML content of the SVG to the frontend and put the code in a DIV
