### ISSUE TITLE
Dependency threshold from the Heuristics Miner produces strange results

### ISSUE THREAD

**Issue by bfreib** [process-intelligence-solutions/pm4py#379]
Is there a bug in the Heuristics Miner?
When I set a high dependency threshold (here 0.8) I see an arc appearing in the Heuristics Net.
![Heu_Net_DT-0 8](https://user-images.githubusercontent.com/94987544/214520388-e889c23d-a1b4-4523-a9ea-f2da9190b7a9.png)

When I set it to a lower value (0.5) it dissapears.
![Heu_Net_DT-0 5](https://user-images.githubusercontent.com/94987544/214520408-1d2199cd-19d7-4f72-8406-b29e9a818336.png)

In my opinion this cannot be right. What am I missing here?
I left the other parameters on the default values.
I'm using pm4py 2.5.0 but i also testet it on previous versions.

Corresponding DFG:
![DFG](https://user-images.githubusercontent.com/94987544/214520279-a60659be-ae46-464a-94b0-3b6583de3f1d.png)

**Comment by fit-alessandro-berti** [comment]
Dear @bfreib 

I investigated your problem but was not able to reproduce it.
With 0.5 i find your first heuristics net (100% matching), but with 0.8 i find another heuristics net containing only activity A, therefore my result does not match with yours.

Minimal code to reproduce

import pm4py
from pm4py.algo.discovery.heuristics.variants import classic


dfg = {("Activity A", "Activity B"): 392, ("Activity B", "Activity A"): 49, ("Activity A", "Activity A"): 68}
start_activities = {"Activity A": 343}
end_activities = {"Activity B": 343}
activities_occurrences = {"Activity A": 460, "Activity B": 392}
pm4py.view_dfg(dfg, start_activities, end_activities)
heu_net = classic.apply_heu_dfg(dfg, activities=list(activities_occurrences), activities_occurrences=activities_occurrences, start_activities=start_activities, end_activities=end_activities, parameters={"dependency_thresh": 0.5})
pm4py.view_heuristics_net(heu_net, format="svg")

**Comment by bfreib** [comment]
Dear @fit-alessandro-berti 

Thank you for your quick answer.
I get the same results with your code, and that is what I would expect using my data.

Is there maybe a bug in the discover method?
`heuristics_net = pm4py.discover_heuristics_net(data_frame, dependency_threshold)`

I tested it also with an EventLog instance and get the same wrong result.

**Comment by fit-alessandro-berti** [comment]
Not sure what to think. Could you share the log with us? Or email it at alessandro.berti@fit.fraunhofer.de

**Comment by bfreib** [comment]
Hi @fit-alessandro-berti,
I need to check if I am allowed to do that. I will let you know.

In the meantime I found another slice of the log where this threshold produced almost the result I would expect.
Can you explain to me why the self loop of "Activity A" does not appear in the heuristics net? It has a dependency of 0.5.
I also played with the other thresholds and they seem to do nothing. Is there a documentation somewhere what exactly they should do?

`
dfg = {("Activity A", "Activity B"): 208, ("Activity B", "Activity A"): 51, ("Activity A", "Activity A"): 1}
start_activities = {"Activity A": 157}
end_activities = {"Activity B": 157}
activities_occurrences = {"Activity A": 209, "Activity B": 208}
pm4py.view_dfg(dfg, start_activities, end_activities)
heu_net = classic.apply_heu_dfg(dfg, activities=list(activities_occurrences), activities_occurrences=activities_occurrences, start_activities=start_activities, end_activities=end_activities, parameters={"dependency_thresh": 0.4})
pm4py.view_heuristics_net(heu_net)
`

DFG:
![dfg1](https://user-images.githubusercontent.com/94987544/214787079-f6c074a8-f9bf-4ee6-9741-eaa248d8439d.png)

Heuristics Net:
![heur1](https://user-images.githubusercontent.com/94987544/214787092-296490ac-9a0f-4686-90dd-5556a05ef908.png)

Thank you very much for your help!

**Comment by fit-alessandro-berti** [comment]
You applied the heuristics threshold correctly. However in the implementation there is a dfg_pre_cleaning_noise_thresh parameter that cleans the DFG before the application of the heuristics miner. This cleans the arcs from the source activity that are less frequent than thresh * max output arcs. The default is 0.05 but you need to set it at 0.0 to avoid such cleaning:

heu_net = classic.apply_heu_dfg(dfg, activities=list(activities_occurrences), activities_occurrences=activities_occurrences, start_activities=start_activities, end_activities=end_activities, parameters={"dependency_thresh": 0.4, "dfg_pre_cleaning_noise_thresh": 0.0})


For the meaning of the other parameters (AND threshold and loops of length 2) you could refer to Weijters, A. J. M. M., Wil MP van Der Aalst, and AK Alves De Medeiros. "Process mining with the heuristics miner-algorithm." Technische Universiteit Eindhoven, Tech. Rep. WP 166.July 2017 (2006): 1-34. 

Possibly the result in your original log is indeed influenced by length 2 loops.

**Comment by bfreib** [comment]
Thank you.
The heuristic miner could not detect a sound net from the original log mentioned in the first comment. Maybe this explains why the parameters did not work correctly.

Another question about the "min_dfg_occurrences" parameter. When I set this parameter to 4, all arcs dissapear in the heuristics net that were used in less than 4 traces. When then converted to a Petri net the arcs are still there.
Is this the intended behavior?

**Comment by fit-alessandro-berti** [comment]
Two comments:
1) the conversion of heuristics net to WF net is not assured to return a sound WF net. indeed, many times this does not happen
2) all activities are included during the conversion. you are right, it makes no sense to include "min_dfg_occurrences" and "min_act_occurrences" in the pm4py.discover_petri_net_heuristics method because they matter in the heuristics net representation but not in the conversion

**Comment by bfreib** [comment]
@fit-alessandro-berti: Thank you again for your help. I think that all my questions on this subject have been answered.
