### ISSUE TITLE
generate diagrams for both frequency and performance

### ISSUE THREAD

**Issue by aditya11ad** [process-intelligence-solutions/pm4py#380]
hi,

this is working fine for **frequency** :
```
heu_net = heuristics_miner.apply_heu(log)
heu_net.dfg_matrix
```
I also want to get **performance**(Time).
what to do?

**Comment by fit-alessandro-berti** [comment]
Hi, please find the performance information in the performance DFG:

perf_dfg, sa, ea = pm4py.discover_peformance_dfg(log)
