### ISSUE TITLE
from pm4py.visualization.petrinet import visualizer as pn_visualizer

### ISSUE THREAD

**Issue by jawaadiqbal** [process-intelligence-solutions/pm4py#381]
When i use the command:
from pm4py.visualization.petrinet import visualizer as pn_visualizer
I get error :
ModuleNotFoundError: No module named 'pm4py.visualization.petrinet'

rest of the visulalizers are working perfectly i.e.
from pm4py.visualization.process_tree import visualizer as pt_visualizer
from pm4py.visualization.heuristics_net import visualizer as hn_visualizer
from pm4py.visualization.dfg import visualizer as dfg_visualization

I tired everything i.e. reinstalled the pm4py, tried updating it and so on but did not find any solution,
could you please help in this regard as I am new to it!

**Comment by fit-alessandro-berti** [comment]
Dear @jawaadiqbal 

The pm4py.visualization.petrinet has been first deprecated and now renamed to pm4py.visualization.petri_net

Therefore simply adding a _ would resolve this problem ;)

**Comment by jawaadiqbal** [comment]
Thank you its working ! 👍
