### ISSUE TITLE
extension read functionality for ocel

### ISSUE THREAD

**Issue by SRottgardt** [process-intelligence-solutions/pm4py#382]
hey,

we are trying to use the OCEL functionality of the library using the CSV file 
[ocel csv datei](https://github.com/pm4py/pm4py-core/blob/release/tests/input_data/ocel/example_log.csv)

As soon as we read the file and use it in a Panda DataFrame we get different values in the Basic Statistics.

`_dataFrame = pm4py.format_dataframe(dataFrame, case_id=caseKey, activity_key=activityKey, timestamp_key=timestampKey)
`

Our values are for 
activity_key : ocel:activity
timestamp_key : ocel:timestamp
case_id : ocel_eid

and then want to convert the log to OCEL format 

```
ocel = pm4py.convert_log_to_ocel(_dataFrame)
print(ocel)
```

> Object-Centric Event Log (number of events: 23, number of objects: 23, number of activities: 15, number of object types: 1, events-objects relationships: 23)
> Activities occurrences: { 'Create Order': 3, 'Create Delivery': 3, 'Delivery Successful': 3, 'Invoice Sent': 2, 'Payment Reminder': 2, 'Pay Order': 1, 'Remove Item': 1, 'Cancel Order': 1, 'Add Item to Order': 1, 'Confirm Order': 1, 'Send for Credit Collection': 1, 'Item out of Stock': 1, 'Item back in Stock': 1, 'Delivery Failed': 1, 'Retry Delivery': 1}
> Object types occurrences (number of objects): {'case:concept:name': 23}
> Please use <THIS>.get_extended_table() to get a dataframe representation of the events related to the objects.

We will get number of objects 23.

If we use the pm4py.read_ocel_csv functionality directly we get the following basic statistics

`ocel = pm4py.read_ocel_csv("C:\example_log.csv")`

> Object-Centric Event Log (number of events: 23, number of objects: 15, number of activities: 15, number of object types: 3, events-objects relationships: 39)
> Activities occurrences: { 'Create Order': 3, 'Create Delivery': 3, 'Delivery Successful': 3, 'Invoice Sent': 2, 'Payment Reminder': 2, 'Confirm Order': 1, 'Item out of Stock': 1, 'Item back in Stock': 1, 'Delivery Failed': 1, 'Retry Delivery': 1, 'Pay Order': 1, 'Remove Item': 1, 'Cancel Order': 1, 'Add Item to Order': 1, 'Send for Credit Collection': 1}
> Object types occurrences (number of objects): {'element': 9, 'delivery': 3, 'order': 3}
> Please use <THIS>.get_extended_table() to get a dataframe representation of the events related to the objects.

We get number of object 15.
Is there an error here?

Additionally we are looking to create an OCEL class from a dataFrame, is there already a way for this?
We didn't find one, so we looked at the read_ocel_csv and wrote an extension for it.

```
def read_ocel_dataFrame(dataFrame: DataFrame) -> OCEL:
    """
    Reads an object-centric event log from a dataFrame.
    The ``OCEL`` object is returned by this method

    :param dataFrame: input is a panda dataFrame
    :rtype: ``OCEL``

    .. code-block:: python3

        import pm4py

        ocel = pm4py.read_ocel_dataFrame(dataFrame)
    """
    from pm4py.objects.ocel.obj import OCEL
    from pm4py.objects.ocel.util import extended_table

    return extended_table.get_ocel_from_extended_table(dataFrame, None, parameters=None)
```

If we use functionality we also get the 15 number of objects as in the doc.

**Comment by fit-alessandro-berti** [comment]
Dear @SRottgardt 

In the first example, you are saying to use as object type column the event identifier.

Since the event identifier is unique for each event, each event is associated to a different object that is its own event identifier.
The object types reported in the OCEL (order, element, delivery) are therefore ignored by your selection.

You should provide the list of correct object types inside the optional parameter of convert_log_to_ocel called object_types if you want to proceed as first.

Otherwise, we always advise the usage of read_ocel_csv which assures compliance to the OCEL standard.

**Comment by SRottgardt** [comment]
Dear @fit-alessandro-berti,


thank you for the quick explanation, so I know and will take the direct way using read_ocel_csv.

On the question of using a dataFrame directly, there is no direct way until now?

**Comment by fit-alessandro-berti** [comment]
Dear @SRottgardt , not without 1000 caveats :( the read_ocel_csv is the safest choice
