### ISSUE TITLE
Process Mining CRM Systems

### ISSUE THREAD

**Issue by shubhamsinha** [process-intelligence-solutions/pm4py#386]
Hi there,

I am really new to Process Mining but fascinated with the CRM use case. Let's say I wanted to process mine our company's Salesforce using pm4py. What would you recommend is the best way to get started with the Salesforce use case? Any guidance on resources would be much appreciated.

**Comment by fit-alessandro-berti** [comment]
Dear @shubhamsinha 

First, you would need to identify the target process. A popular choice is the process of management of opportunities. Usually an opportunity starts with what we call a "Opportunity created" activity (which could be triggered by a business campaign). Then, some events related to the opportunities might be recorded, until an "Opportunity closed" is recorded, for example with winning or losing the opportunity.

You could extract the log for such process from many CRM systems, including the popular Dynamics CRM and Salesforce. By the way, as pm4py team we offer consultance for the extraction, transformation and load of the data. Feel free to contact us at pm4py@pm4py.fit.fraunhofer.de

**Comment by shubhamsinha** [comment]
Hey @fit-alessandro-berti I sent an email but looks like you mail servers are down. Let me know if there is an alternative way to contact you folks. Thanks!

**Comment by fit-sebastiaan-van-zelst** [comment]
Hey @shubhamsinha; could you please forward your email to pm4py@fit.fraunhofer.de; Sadly @fit-alessandro-berti  made a small typo in the email address.

**Comment by shubhamsinha** [comment]
Hi @fit-sebastiaan-van-zelst thank you! I emailed you folks hope to hear back soon

**Comment by shubhamsinha** [comment]
@fit-alessandro-berti @fit-sebastiaan-van-zelst Been trying to get hold of you folks for a bit but no luck :( Please let me know if you are not receiving my emails for some reason but we could definitely use your expertise and consulting
