### ISSUE TITLE
xes_import.apply missed all time:timestamp values

### ISSUE THREAD

**Issue by JZL429** [process-intelligence-solutions/pm4py#387]
Hi,

I have generated an XES file using spyenxes.data_out.XesXmlSerializer, and the file format is like this:

<?xml version="1.0" ?>

<log openxes.version="1.0RC7" xes.features="nested-attributes" xes.version="1.0">
	<trace>
		<string key="concept:name" value="xxx"/>
		<string key="gender" value="xx"/>
		<string key="age" value="xxx"/>
		<string key="charlson" value="xxx"/>
		<string key="elixhauser" value="xxx"/>
		<date key="dob" value="2100-03-06T00:00:00.000Z"/>
		<string key="dod" value="2185-05-26 00:00:00"/>
		<string key="ethnicity" value="xxxxx"/>
		<string key="label" value="xxxxx"/>
		<event>
			<string key="type" value="xxxxx"/>
			<string key="concept:name" value="xxxxxx"/>
			<string key="admission_id" value="xxxxxx"/>
			<date key="time:timestamp" value="2184-05-04T16:13:00.000Z"/>
		</event>
		<event>
			<string key="type" value="xxxxxx"/>
			<string key="concept:name" value="xxxxxx"/>
			<string key="admission_id" value="xxxxxx"/>
			<date key="time:timestamp" value="2184-05-04T16:13:00.000Z"/>
		</event>
        </trace>

However, when I use pm4py.objects.log.importer.xes.factory.xes_import to read it:

log=xes_import.apply(path)
log[0]

I got this in return:

{'attributes': {'concept:name': 'xxx', 'gender': 'x', 'age': 'xx', 'charlson': 'x', 'elixhauser': 'x', 'dod': '2185-05-26 00:00:00', 'ethnicity': 'xxxx', 'label': 'xxx'}, 'events': [{'type': 'xxx', 'concept:name': 'xxxx', 'admission_id': 'xxxxxx'}, '..', {'type': 'xxxx', 'concept:name': 'xxx', 'admission_id': 'xxxxxx'}]}

all the values associated with `date key`, specifically, 'dob' and 'time:timestamp' are missing when I read it, like for the first event:

log[0][0]

returned:

{'type': 'xxx', 'concept:name': 'xxxx', 'admission_id': 'xxxxxx'}

I tried to search for it in the read dictionary:

timestamp = log[0][0].get('time:timestamp')
if timestamp is not None:
    print(timestamp)
else:
    print("No 'time:timestamp' key")

and it returned:

No 'time:timestamp' key

As the file format seems correct, I was wondering what is going on with the xes_import.apply, I have also tried to set parameters when reading the xes file, I set parameters={"timestamp_sort": True, "timestamp_key": "time:timestamp", "reverse_sort": False}, it returned KeyError: 'time:timestamp'.

I treid to read it directly using pandas csv just to see if the timestamp value can be read, and it returned okay with values:

df = pd.read_csv(path)
df[df['<?xml version="1.0" ?>'].str.contains('dob')]

\t\t<date key="dob" value="2100-03-06T00:00:00...
\t\t<date key="dob" value="2108-08-25T01:00:00...
\t\t<date key="dob" value="2123-06-09T01:00:00...
\t\t<date key="dob" value="2090-12-25T00:00:00...
\t\t<date key="dob" value="2069-03-06T00:00:00...
...
\t\t<date key="dob" value="2068-05-01T01:00:00...
\t\t<date key="dob" value="2037-08-01T01:00:00...
\t\t<date key="dob" value="2102-09-10T01:00:00...
\t\t<date key="dob" value="1970-01-02T00:00:00...
\t\t<date key="dob" value="2086-04-08T01:00:00...

opyenxes version == 0.3.0
pm4py version == 1.2.10

Thank you, I hope you could help me solve this issue.

**Comment by fit-alessandro-berti** [comment]
Dear @JZL429 

You are using an extremely deprecated version of pm4py. Please update to 2.5.2

pm4py is not related to opyenxes in any case.

Even with the latest version, it might be that the parsing would still fail, because of the strange dates reported in your comment (2123 !!) .

**Comment by JZL429** [comment]
Thank you, I will try to update the version a bit. Because I was reproducing other's work, so I am using the exact same version as they mentioned.

The time date is because the data has been processed to not reflect the real date, only keeping the relative time delta, but thank you for pointing that out, I will try to see if this makes any differences.

> Dear @JZL429
> 
> You are using an extremely deprecated version of pm4py. Please update to 2.5.2
> 
> pm4py is not related to opyenxes in any case.
> 
> Even with the latest version, it might be that the parsing would still fail, because of the strange dates reported in your comment (2123 !!) .
