### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by mqus** [process-intelligence-solutions/pm4py#389]
There seem to be a few dependencies which are missing in the `requirements.txt`, like `pyvis` and `pyemd` (see https://github.com/pm4py/pm4py-core/blob/release/pm4py/visualization/sna/variants/pyvis.py#L64 and https://github.com/pm4py/pm4py-core/blob/release/pm4py/algo/evaluation/earth_mover_distance/variants/pyemd.py#L20 . I can't execute the tests without them.

I'm installing the dependencies via my linux package manager though so I might be doing something wrong.

**Comment by fit-alessandro-berti** [comment]
Dear @mqus 

Those dependencies were deliberately left out. We targeted pm4py to work on many different platforms/Python versions and decided to come out with some requirements that allow for the usage of 95% of the features, while the other 5% require the user to install manually some packages (e.g. pyemd).

This is suboptimal but necessary (to allow the flexibility on the platforms/Python versions)

**Comment by mqus** [comment]
This is imho fine as long as it is documented (even though I think that pip&co have tools to work around this), but I could not find anything about it. Not in the API reference or in the README, not even as a comment in the requirements.txt or their licenses in the third_party folder.

**Comment by fit-alessandro-berti** [comment]
Dear @mqus 

We now declare the optional dependencies in the README.md file
