### ISSUE TITLE
UserWarning: the EventLog class has been deprecated

### ISSUE THREAD

**Issue by excubo-jg** [process-intelligence-solutions/pm4py#390]
I did update pm4py and ran some old code of mine. I got this new warning:

C:\Users\Admin\anaconda3\envs\BPMNgen\lib\site-packages\pm4py\utils.py:486: UserWarning: the EventLog class has been deprecated and will be removed in a future release.
  warnings.warn("the EventLog class has been deprecated and will be removed in a future release.")

My problem is that I do not make any reference to "EventLog" in my code... Any suggestions on how to find and fix the cause for this warning?

**Comment by fit-alessandro-berti** [comment]
Dear @excubo-jg 

Thanks for signaling. This is generated in some internal call to the EventLog conversion. Indeed, there are still methods that work natively on EventLogs and require (internally) the dataframe to be converted. A typical example is the Petri net alignments algorithm.

We will propose a solution for these warnings in the next release.

**Comment by fit-alessandro-berti** [comment]
The issue should be solved with pm4py 2.6.0

**Comment by excubo-jg** [comment]
Dear Alessandro,

I just checked with 2.6.1 and the warning message has not gone away.

**Comment by fit-alessandro-berti** [comment]
That's weird. We removed every internal warnings and the warning should be triggered only with manual calls to pm4py.convert_to_event_log

Can you check if the version that your script is using is indeed 2.6.1 ? Put print(pm4py.__version__)  in one line in the script (where version is written with two _ before and two _ after).

If it is indeed 2.6.1, can you provide an example code where the problem occurs?

**Comment by fit-alessandro-berti** [comment]
Post-scriptum: if you import a .xes log using the non-simplified interface (e.g. from pm4py.objects.log.importer.xes import importer ....) then an EventLog object is imported and a warning is also launched when you try to use the log with methods of the simplified interface.

**Comment by excubo-jg** [comment]
I can confirm that I am using 2.6.1.
"the warning should be triggered only with manual calls to pm4py.convert_to_event_log" At one instance in my code this function is called. Probably that is the culprit - how to best replace it? [Apologies, I did not realize from the warning message that event_log is related to the EventLog class]
In the code pm4py.objects.log dataframes_util is imported but not importer.xes so I assume this does not cause the problem.

**Comment by fit-alessandro-berti** [comment]
Yes that is the culprit :) This workaround (constants.SHOW_EVENT_LOG_DEPRECATION = False) should work properly for you

import pm4py

from pm4py.util import constants

constants.SHOW_EVENT_LOG_DEPRECATION = False

log = pm4py.read_xes("C:/running-example.xes")

log = pm4py.convert_to_event_log(log)
