### ISSUE TITLE
pm4py.view_events_distribution_graph: plotting weeks has overlapping x-axis

### ISSUE THREAD

**Issue by AndreasKarasenko** [process-intelligence-solutions/pm4py#403]
Plotting event distributions for week of the year in a jupyter notebook leads to overlapping values on the x-axis.
Would it be possible to add a tight_layout() call somewhere in the graph generation?
I was looking up the tmp file that is used for displaying the graph in jupyter, and it's the same.

**Comment by fit-alessandro-berti** [comment]
Dear @AndreasKarasenko 

Thank you for signaling. We will evaluate some changes in the x-axis for the next release

**Comment by fit-alessandro-berti** [comment]
Dear @AndreasKarasenko 

We changed the X axis of the view_events_distribution_graph in order to allow for a more compact representation of the values:

<img width="525" alt="image" src="https://user-images.githubusercontent.com/56342194/229466879-77faa35e-61fe-4a3b-ae77-a3cf73f0cbd5.png">
