### ISSUE TITLE
`get_trace_attribute_values` inconsistent behavior in `DataFrame` and `EventLog`

### ISSUE THREAD

**Issue by ainnoot** [process-intelligence-solutions/pm4py#406]
Consider the following, on version `2.7.2`:

```python
log_df = pm4py.read_xes("sepsis.xes")
event_log = pm4py.convert_to_event_log(log_df)

activities_df = pm4py.get_trace_attribute_values(log_df, 'case:concept:name')

# Implicit `case:`, also a bug?
activities_el = pm4py.get_trace_attribute_values(event_log, 'concept:name')

print(activities_df['A']) # prints 22, which is the length of the trace
print(activities_el['A']) # prints 1
```

I believe the intended is behavior is the one in the soon-to-be-deprecated `EventLog`, since `case:concept:name` is the unique identifier of the trace. It seems that on `DataFrame`s, trace attributes get counted multiple times, one for each event in the trace, since they appear multiple times in the `DataFrame`.

**Comment by fit-alessandro-berti** [comment]
It is very difficult to have a coherent behavior given the inherent differences in the log objects.

We proposed https://github.com/pm4py/pm4py-core/commit/0ba6b34c19587357425cb27cccb23b12d70978a7 as workaround

**Comment by fit-alessandro-berti** [comment]
See release 2.7.3
