### ISSUE TITLE
Missing petri net, DFG option for inductive miner

### ISSUE THREAD

**Issue by william-vw** [process-intelligence-solutions/pm4py#408]
Just out of interest - as per the [documentation](https://pm4py-source.readthedocs.io/en/stable/pm4py.algo.discovery.inductive.html#module-pm4py.algo.discovery.inductive.algorithm) (and this [very useful tutorial](https://www.futurelearn.com/courses/process-mining-healthcare)) the inductive miner algorithm should support mining petri nets, but [algorithm#apply](https://github.com/pm4py/pm4py-core/blob/release/pm4py/algo/discovery/inductive/algorithm.py#L52) only returns process trees. What is this implemented at a previous point but removed?

**Comment by william-vw** [comment]
Ah I found a process tree converter in [one of the examples](https://github.com/pm4py/pm4py-core/blob/release/examples/decisiontree_align_example.py) that does the trick :-)

Still I think it would be useful to update the documentation :-)

**Comment by fit-alessandro-berti** [comment]
Dear @william-vw the documentation reported there is outdated. Please refer to https://pm4py.fit.fraunhofer.de

**Comment by william-vw** [comment]
@fit-alessandro-berti thanks - but the [API reference](https://pm4py.fit.fraunhofer.de/static/assets/api/2.7.3/api.html) reachable from that page did not seem to correspond at all to the package structure of the latest pm4py.

I accidentally stumbled onto [this page](https://pm4py.fit.fraunhofer.de/static/assets/api/2.7.3/pm4py.algo.html) which seems to be up-to-date - did I miss a link or something? ...

**Comment by fit-alessandro-berti** [comment]
Every command that you find on the first page should also work!

**Comment by william-vw** [comment]
Ah I see, thanks!
