### ISSUE TITLE
Why do many functions that calculate duration only use timestamp_key instead of reserving start_timestamp and timestamp_key at the same time.

### ISSUE THREAD

**Issue by DAAworld** [process-intelligence-solutions/pm4py#411]
I wonder if pm4py didn't consider the start and end time in the log at the same time, because many functions that calculate the duration only use timestamp_key instead of reserving start_timestamp and timestamp_key at the same time.

**Comment by fit-alessandro-berti** [comment]
Dear @DAAworld 

Most process mining algorithms consider naturally events with just a timestamp.
Very few use the start/end timestamp information.

In pm4py, some methods offer support for start/end timestamps, however, the support is not systematic and limited to few algorithms.

**Comment by DAAworld** [comment]
> Dear @DAAworld
> 
> Most process mining algorithms consider naturally events with just a timestamp. Very few use the start/end timestamp information.
> 
> In pm4py, some methods offer support for start/end timestamps, however, the support is not systematic and limited to few algorithms.

Yes, I noticed, so, in some needed methods, I can only modify it myself. Have you considered making some changes in the future?

**Comment by fit-alessandro-berti** [comment]
As long term plan yes, but that also depends on the development of process mining algorithms that use the lifecycle information in a more effective way
