### ISSUE TITLE
Why is the duration of pm4py in seconds?

### ISSUE THREAD

**Issue by DAAworld** [process-intelligence-solutions/pm4py#412]
If the process is executed by a computer, such as RPA, then the time is likely to be shortened to the millisecond level. If the second is still used at this time, then nothing can be analyzed. I've tried monkey patching astype("int64") // 10 ** 9 to 10 ** 6, or changing astype('timedelta64[s]') to astype('timedelta64[ms]') , I found that the workload was too great and finally gave up.

**Comment by fit-alessandro-berti** [comment]
Dear @DAAworld 

Thanks for the suggestion. We may consider to change the timestamp difference computation from seconds to milliseconds.

**Comment by DAAworld** [comment]
> Dear @DAAworld
> 
> Thanks for the suggestion. We may consider to change the timestamp difference computation from seconds to milliseconds.

OK, I hope the project will get better and better

**Comment by fit-alessandro-berti** [comment]
Dear @DAAworld 

We checked and in the current version of the code, the two patterns have been mostly replaced. We'll finish their replacement in the next release.
