### ISSUE TITLE
Why when obtaining the precision value the process gets killed every time.

### ISSUE THREAD

**Issue by GuilleMoya** [process-intelligence-solutions/pm4py#413]
Im obtaining a pretri net from a event log of 38.4MB. When obtaining the values for fitness, generalizartion and simplicity I get no problems. However, when I try to obtain the precision value it always gets terminated.

**Comment by fit-alessandro-berti** [comment]
Dear @GuilleMoya 

We need more details in order to help you. Which precision algorithm are you using? Can you provide a code snippet?

**Comment by GuilleMoya** [comment]
Hi, im using the Algorithms of Heuristic miner, inductive miner and alpha miner. Once i obtain the net, the initial marking and the final marking y pass this variables to the precision function.
`    precision = pm4py.precision_token_based_replay(event_log, net, initial_marking, final_marking)
`

I then just print the result, which never appears because it gets terminated

**Comment by fit-alessandro-berti** [comment]
Dear @GuilleMoya 

That is weird indeed. Token-based replay is based on some heuristics, which may fail for the models discovered using the Heuristics Miner. But should not fail at least for models discovered using the Inductive Miner.

Could you try the (slower) pm4py.precision_alignments(event_log, net, initial_marking, final_marking) ?

**Comment by GuilleMoya** [comment]
I've tried this solutiuon and the result is the same.

**Comment by fit-alessandro-berti** [comment]
Allright. We'll investigate the problem, which is weird because the methods were released quite some time ago. If possible, could we ask you to attach the process model (if it is not sensitive)?

**Comment by GuilleMoya** [comment]
This would be the petri net for my event log of 41.2MB using the inductive miner. I've tried obtaining the precision with this exact petri net and I have always obtained a terminated process.

![ID_guay](https://github.com/pm4py/pm4py-core/assets/37296418/a78d461c-8611-4a64-bec2-c542072a6dab)

**Comment by fit-alessandro-berti** [comment]
Unfortunately we were not able to reproduce the problem yet
