### ISSUE TITLE
vis_heuristics_net bgcolor does not overwrite default

### ISSUE THREAD

**Issue by AntonyRLee** [process-intelligence-solutions/pm4py#420]
I cannot get the background of the heuristic net to change from white (default). Does not work for saving net either. 

Example:
import pm4py
log = pm4py.read_xes("running-example.xes")
hn = pm4py.discover_heuristics_net(log)
pm4py.view_heuristics_net(hn, bgcolor='red') # background unchanged

**Comment by fit-alessandro-berti** [comment]
Dear @AntonyRLee 

Thanks for signaling. We'll release a fix in the upcoming release.

Cheers

**Comment by fit-alessandro-berti** [comment]
The issue is resolved in pm4py 2.7.5
