### ISSUE TITLE
pm4py.conformance.fitness_token_based_replay - Parameter 'consider_activities_not_in_model_in_fitness'

### ISSUE THREAD

**Issue by WiedPakusa** [process-intelligence-solutions/pm4py#421]
TBR in pm4py seems to ignore all events that do not occur in the model.
As an effect, traces with activities that are not in the model might be reported as fitting.

The parameter 'consider_activities_not_in_model_in_fitness' seems to control this behaviour.
Unfortunately, it is impossible to set the parameter via the function pm4py.conformance.fitness_token_based_replay() since the keyword 'parameters' is missing.
Moreover, if the parameter is set via an attribute of the log, then it gets lost in case that a diagnostics dataframe is returned (probably because of the conversion into the old log format).

**Comment by fit-alessandro-berti** [comment]
Dear @WiedPakusa 

Thanks for signaling.
We'll add support for optional parameters in the token-based replay exposed by the simplified interface.
