### ISSUE TITLE
dataframe_utils.py:176: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`.

### ISSUE THREAD

**Issue by skyocean** [process-intelligence-solutions/pm4py#423]
Hi, I really appreciate some help. 
Regarding `pm4py.read_xes()`, I tried to pass running_example.xes and other xes dataset.  I got warnings: "log\util\dataframe_utils.py:176: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format."

Then I tried to run https://github.com/pm4py/pm4py-core/blob/release/notebooks/2_event_data_filtering.ipynb.

I got different results and warning:

```
import pm4py
log = pm4py.read_xes('data/running_example.xes')
list(map(lambda t: len(t), log))
```
Output, instead
` [9, 5, 5, 5, 13, 5] `
I got 
`[12, 12, 14, 8, 8, 5, 17] `

Regarding this command
```
lf = pm4py.filter_log(lambda t: len(t) > 5, log)
list(map(lambda t: len(t), lf))
```

I got warning 
"C:\Users\oZZo\AppData\Local\Temp\ipykernel_5964\553380614.py:1: DeprecatedWarning: filter_log is deprecated as of 2.3.0 and will be removed in 3.0.0. the EventLog class will be removed in a future release.
  lf = pm4py.filter_log(lambda t: len(t) > 5, log1)
C:\Users\oZZo\AppData\Local\Programs\Python\Python311\Lib\site-packages\pm4py\hof.py:48: UserWarning: input log object not of appropriate type, filter() not applied
  warnings.warn('input log object not of appropriate type, filter() not applied')"

**Comment by fit-alessandro-berti** [comment]
Dear @skyocean 

Thanks for signaling. We will fix the notebook(s) in the upcoming release.

**Comment by fit-alessandro-berti** [comment]
Dear @skyocean 

We fixed the provided notebooks
