### ISSUE TITLE
Save BPMN from discover_dfg or performance_dfg

### ISSUE THREAD

**Issue by NKMatha** [process-intelligence-solutions/pm4py#427]
Hi team,

I saving the BPMN from dfg's, but wondering to have the edges weight while saving BPMN like number of occurrences or performance time which we're getting in dfg graphs. Is there any procedure to have or its not going to consider the edges weight....

Thanks in advance.

**Comment by fit-alessandro-berti** [comment]
Dear @NKMatha 

The original question is not that clear.
1) You can export the frequency DFG both as a picture (pm4py.save_vis_dfg) and in the .dfg format (pm4py.write_dfg)
2) You can export the performance DFG only as a picture (pm4py.save_vis_performance_dfg)
3) You can convert the DFG to a BPMN diagram, and then save a visualization of it (pm4py.save_vis_bpmn) or export it as BPMN 2.0 XML (pm4py.write_bpmn)

**Comment by NKMatha** [comment]
Hi @fit-alessandro-berti 

I was looking to save bpmn something like bellow and while loading bpmn(pm4py.read_bmpm()) would like read the edges weight i.e: 94,7,23.
![image](https://github.com/pm4py/pm4py-core/assets/122022435/655fd4e0-dab9-4eb3-8170-2aa662ddcac4)

Is there any possibility for that....?

**Comment by fit-alessandro-berti** [comment]
Dear @NKMatha 

Unfortunately we do not support custom annotations on the arcs for importing/exporting

**Comment by NKMatha** [comment]
ok, thanks for your support @fit-alessandro-berti
