### ISSUE TITLE
Output in html format shows blank

### ISSUE THREAD

**Issue by fpjaa** [process-intelligence-solutions/pm4py#428]
Hello,

I'm running some notebooks on Jupyter without the Graphviz executables, so i use the format = 'html' parameter as suggested in a previous issue.

However, the last few days instead of seeing the usual maps I get a blank output.

Is there any way to know what's failing? I try recreating the same maps that worked before.

Thanks in advance.

**Comment by fit-alessandro-berti** [comment]
Dear @fpjaa 

Thanks for signaling. Actually, the authors moved the path to an external JS that was needed in the HTML page to render the diagram. We'll fix that in the next release
