### ISSUE TITLE
openAI?

### ISSUE THREAD

**Issue by Krasnomakov** [process-intelligence-solutions/pm4py#429]
Can't find openAI that previously existed? Do you plan to create AI-powered automation?

**Comment by fit-alessandro-berti** [comment]
Dear @Krasnomakov 

We renamed the "pm4py.openai" module to "pm4py.llm". Find complete documentation at https://pm4py.fit.fraunhofer.de/static/assets/api/2.7.5/index.html 

We don't plan to integrate AI-powered RPA soon, although it may be a good idea for the future

**Comment by Krasnomakov** [comment]
Great, thanks!
