### ISSUE TITLE
Examples / documentation for clustering.trace_attribute_driven

### ISSUE THREAD

**Issue by william-vw** [process-intelligence-solutions/pm4py#433]
I was wondering whether some examples (or documentation) are available on the functions in clustering.trace_attribute_driven? 

Normally the [repo examples folder](https://github.com/pm4py/pm4py-core/tree/release/examples) is a good source - I found  an [example for trace clustering](https://github.com/pm4py/pm4py-core/blob/release/examples/trace_clustering.py) - but nothing on that particular module.

**Comment by fit-alessandro-berti** [comment]
Dear @william-vw 

Thank you for your request. We will add an example script in the next release

**Comment by fit-alessandro-berti** [comment]
[trace_attrib_hierarch_cluster.py.txt](https://github.com/pm4py/pm4py-core/files/12266685/trace_attrib_hierarch_cluster.py.txt)

**Comment by william-vw** [comment]
@fit-alessandro-berti Ok, thanks a lot!
