### ISSUE TITLE
The results based on token backtracking seem counterintuitive

### ISSUE THREAD

**Issue by DAAworld** [process-intelligence-solutions/pm4py#435]
我有一个bpmn模型，大致是a->b->c这么个流程，我的变体是a->b->c->d，我在使用基于token回演的方法时（from pm4py.algo.conformance.tokenreplay.variants import token_replay），他的结果是1，这看上去不符合直觉，我感觉这不是合规的

**Comment by fit-alessandro-berti** [comment]
Dear @DAAworld 

I would invite you to use English as language to open an issue.

Token-based replay cannot consider activities that are not in the model (as they would not increase neither the number of missing and remaining tokens), so they are simply ignored. Even if this is counterintuitive

**Comment by DAAworld** [comment]
thank you very much for your answer
