### ISSUE TITLE
Missing process name while parsing BPMN XML

### ISSUE THREAD

**Issue by ww917352** [process-intelligence-solutions/pm4py#437]
Dear all,

I found out that in

https://github.com/pm4py/pm4py-core/blob/a199fbbc68637cf453d27f317e91c78a0269e599/pm4py/objects/bpmn/importer/variants/lxml.py#L42C29-L43C43

only the process ID is fetched while the process name is left out.

Is this intentional or do I have wrong understanding here?

Thank you!

Cheers,
Wei

**Comment by fit-alessandro-berti** [comment]
Dear @ww917352 

Generally the name of the BPMN is not essential for our purposes. In any case, thanks for signaling, we'll provide a correction for that.

**Comment by ww917352** [comment]
Thank you a lot. Would you please link this issue to the PR when it is ready?

**Comment by fit-alessandro-berti** [comment]
Dear @ww917352 

See https://github.com/pm4py/pm4py-core/commit/189ab5112aaf463fbd4a395561b43a1f152942fd

**Comment by ww917352** [comment]
Thanks a lot! Have a great week ahead.
