### ISSUE TITLE
'pm4py.objects.log.importer.parquet' is missing in pm4py

### ISSUE THREAD

**Issue by n14b** [process-intelligence-solutions/pm4py#438]
Getting NoModuleFound Error 'pm4py.objects.log.importer.parquet' is missing in pm4py while executing below code 

from pm4pydistr.local_wrapper import factory as local_wrapper_factory

wrapper = local_wrapper_factory.apply("roadtraffic1")
print(wrapper.calculate_dfg())

roadtraffic1 is a directory having parquet data files

**Comment by fit-alessandro-berti** [comment]
Dear @n14b 

The pm4py distributed engine is not maintained anymore (as it is in the "Javert899" personal repository).

We removed pm4py.objects.log.importer.parquet as it was simply a wrapper to pandas.read_parquet and it did not really make sense to keep it in the codebase
