### ISSUE TITLE
Missing names in SequenceFlow when parsing XML

### ISSUE THREAD

**Issue by sap-lukas** [process-intelligence-solutions/pm4py#441]
I found that when parsing BPMNs from XML files, the names of sequence flows get lost (I think this may be related to this line: https://github.com/pm4py/pm4py-core/blob/3987530f234859a9e2c60d177ad988429b18b69a/pm4py/objects/bpmn/importer/variants/lxml.py#L231 where name is always set to an empty string). 

Is there a reason why the sequence flow names are being dropped?

Cheers
Lukas

**Comment by fit-alessandro-berti** [comment]
Dear @sap-lukas 

Thanks for signaling. Albeit we do not use the information internally, we'll propose a fix to properly store the name of SequenceFlow(s).
