### ISSUE TITLE
Issue reading UTF-8 encoded OCEL file

### ISSUE THREAD

**Issue by johannesmols** [process-intelligence-solutions/pm4py#442]
Hi, I just encountered an issue trying to read a UTF-8 encoded JSONOCEL file with a special character in it (in my case "ø").

The error happens on this line: [ocel = json.load(open(file_path, "r"))](https://github.com/pm4py/pm4py-core/blob/8643661515cb8653ccea621787d97cb0e89091c4/pm4py/objects/ocel/importer/jsonocel/variants/classic.py#L64C43-L64C43). The error message is this: `UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 8790034: character maps to <undefined>`.

Setting the encoding parameter of the open function to "utf-8" solves the issue. Python seems to use CP-1252 by default. I'm not sure whether it is ok to just set UTF-8 as a default or if there is a way of detecting the encoding before opening the file. It would at least allow Unicode characters to be present in values, which would be nice.

**Comment by fit-alessandro-berti** [comment]
Thanks for signaling! We'll make it customizable

**Comment by johannesmols** [comment]
Awesome, thanks for the quick answer.
