### ISSUE TITLE
Token-based replay KeyError in `get_diagnostics_dataframe`

### ISSUE THREAD

**Issue by goto-loop** [process-intelligence-solutions/pm4py#446]
When you derive a Petri net from a log, then perform a token-based replay and finally call `pm4py.algo.conformance.tokenreplay.algorithm.get_diagnostics_dataframe()` to get the results in a nicely formatted DataFrame, a KeyError is thrown.

PM4Py version: 2.7.8.1
Python version: 3.11.5

Minimal reproducible example:

```python
import pm4py

log = pm4py.read_xes("tests/input_data/running-example.xes")
petri_net, initial_marking, final_marking = pm4py.discover_petri_net_inductive(log)
replayed_traces = pm4py.conformance_diagnostics_token_based_replay(log, petri_net, initial_marking, final_marking)
diagnostics = pm4py.algo.conformance.tokenreplay.algorithm.get_diagnostics_dataframe(log, replayed_traces)
```

**Comment by fit-alessandro-berti** [comment]
Dear @goto-loop 

Please use the method in the simplified interface as follows, that make sure that the get_diagnostics_dataframe work

import pm4py

log = pm4py.read_xes("tests/input_data/running-example.xes")  
petri_net, initial_marking, final_marking = pm4py.discover_petri_net_inductive(log)  
diagnostics = pm4py.conformance_diagnostics_token_based_replay(log, petri_net, initial_marking, final_marking, return_diagnostics_dataframe=True)

**Comment by goto-loop** [comment]
Wow, I wasn't aware of the simplified interface. It works also with the actual data I'm working on. Thanks a lot!
