### ISSUE TITLE
EventLog Object

### ISSUE THREAD

**Issue by isobelKeen** [process-intelligence-solutions/pm4py#451]
Hi, 
I want to add an artificial start and end date to my log and I used these lines of code:

log = xes_importer.apply(sys.argv[1], variant=variant, parameters=parameters)
log_new=pm4py.objects.log.util.log.add_artficial_start_and_end(log, start='[start>', end='[end]', activity_key='concept:name')

But I get this error:

File "/Users/IsobelKeen/Documents/Year 3/AMP III/DiscoveryTemplate-main/main.py", line 268, in <module>
    log_new=pm4py.objects.log.util.log.add_artficial_start_and_end(log, start='[start>', end='[end]', activity_key='concept:name')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/IsobelKeen/anaconda3/lib/python3.11/site-packages/pm4py/objects/log/util/log.py", line 150, in add_artficial_start_and_end
    trace.insert(0, event_log.Event({activity_key: start}))
                    ^^^^^^^^^^^^^^^
AttributeError: 'EventLog' object has no attribute 'Event'

Thanks for your help!

**Comment by fit-alessandro-berti** [comment]
Dear @isobelKeen 

Please use:

 log = pm4py.insert_artificial_start_end(log, activity_key="concept:name")

If you need to use custom symbols, please put before the aforementioned command these lines:

pm4py.util.constants.DEFAULT_ARTIFICIAL_START_ACTIVITY = '[start>'  
pm4py.util.constants.DEFAULT_ARTIFICIAL_END_ACTIVITY = '[end]'

**Comment by isobelKeen** [comment]
Thanks!
