### ISSUE TITLE
Unclear status of format_dataframe function

### ISSUE THREAD

**Issue by goto-loop** [process-intelligence-solutions/pm4py#452]
I would like to ask about the current status of the `pm4py.format_dataframe()` function.

It used to raise a DeprecatedWarning, but the warning has disappeared a while ago. On the other hand, the function has no entry in the [API reference](https://pm4py.fit.fraunhofer.de/static/assets/api/2.7.8/api.html) which PM4Py's website links to.

Is `format_dataframe()` still supposed to be used in new code?

**Comment by fit-alessandro-berti** [comment]
Dear @goto-loop 

The format_dataframe is there to stay for the foreseeable future, despite its triviality. Essentially what it does is:
- ensuring that case ID, activity (and resource) columns are of type string
- renaming the columns to the pm4py standard
- making sure that time:timestamp is of type datetime (so the datetime are parsed)
- making sure that the dataframe events are sorted according to the timestamp.

We'll update the documentation to properly include and reference the format_dataframe function.

**Comment by goto-loop** [comment]
Thanks for the answer, that's good to know! The function may be trivial, but it seems useful to me because you end up with a properly formatted dataframe using just a single line of code.

Doesn't `format_dataframe` also add two new columns, `@@index` and `@@case_index`?
