### ISSUE TITLE
Can't manage to format the duration within nodes

### ISSUE THREAD

**Issue by IoanaCantCode** [process-intelligence-solutions/pm4py#454]
Dear Brinkhuis,

The discovery operation should be done specifying the performance variant, like in the following example:

import pm4py
from pm4py.algo.discovery.dfg import algorithm as dfg_discovery
from pm4py.visualization.dfg import visualizer as dfg_visualizer

log = pm4py.read_xes("C:/running-example.xes")
dfg_frequency = dfg_discovery.apply(log)
dfg_performance = dfg_discovery.apply(log, variant=dfg_discovery.Variants.PERFORMANCE)
print(dfg_frequency)
print(dfg_performance)
gviz1 = dfg_visualizer.apply(dfg_frequency)
dfg_visualizer.view(gviz1)
gviz2 = dfg_visualizer.apply(dfg_performance)
dfg_visualizer.view(gviz2)

In this case the graphs are clearly different:

![image](https://user-images.githubusercontent.com/56342194/107213158-4c75c000-6a08-11eb-8699-18f6397c2cd7.png)
![image](https://user-images.githubusercontent.com/56342194/107213192-57305500-6a08-11eb-8333-f193c474bf7e.png)

_Originally posted by @fit-alessandro-berti in https://github.com/pm4py/pm4py-core/issues/209#issuecomment-775074948_

**Comment by IoanaCantCode** [comment]
This post helped me very much. However, I can't format the durations from seconds to minutes, without losing the durations from within the nodes. See below code and the dfg before and after the formatting. How is this done properly?
------------------------------
import pm4py
from pm4py.algo.discovery.dfg import algorithm as dfg_discovery
from pm4py.visualization.dfg import visualizer as dfg_visualizer
from pm4py.objects.log.importer.xes import importer as xes_importer

# Import the log from the XES file
log = xes_importer.apply('repairExample.xes')




dfg, start_activities, end_activities = pm4py.discover_dfg(log)

dfg_performance = dfg_discovery.apply(log, variant=dfg_discovery.Variants.PERFORMANCE)

print(dfg_performance)

gviz2 = dfg_visualizer.apply(dfg_performance)
dfg_visualizer.view(gviz2)

#Trying to adjust to minutes
#edges
rounded_dfg_performance = {edge: round(duration, 2) for edge, duration in dfg_performance.items()}

#nodes
rounded_start_activities = {act: round(duration, 2) for act, duration in start_activities.items()}
rounded_end_activities = {act: round(duration, 2) for act, duration in end_activities.items()}

Parameters = {
    dfg_visualizer.Variants.PERFORMANCE.value.Parameters.START_ACTIVITIES: rounded_start_activities,
    dfg_visualizer.Variants.PERFORMANCE.value.Parameters.END_ACTIVITIES: rounded_end_activities
}

gviz2 = dfg_visualizer.apply(rounded_dfg_performance, parameters=Parameters, variant=dfg_visualizer.Variants.PERFORMANCE)
dfg_visualizer.view(gviz2)

-----------------------------

![image](https://github.com/pm4py/pm4py-core/assets/150533985/50895e17-bff4-4a86-b635-cc3c919ae051)

![image](https://github.com/pm4py/pm4py-core/assets/150533985/1a8ce0b2-5331-4993-b2e1-06ee8617f7bb)

**Comment by fit-alessandro-berti** [comment]
Dear @IoanaCantCode 

You were almost there :) just round the performance_dfg items, not the start/end activities

**Comment by IoanaCantCode** [comment]
> Dear @IoanaCantCode
> 
> You were almost there :) just round the performance_dfg items, not the start/end activities

Dear @fit-alessandro-berti,

Thank you so much for your instant reply.  I thought I was doing that here:

rounded_dfg_performance = {edge: round(duration, 2) for edge, duration in dfg_performance.items()}

Isn't this the right way? 
This is actually working, but only for the edges, as you can see in the second picture.  Unfortunately I'm losing the duration within the nodes.
