### ISSUE TITLE
dfg created using dfg_visualizer not detecting the starting activity of the process. I am using correlation miner without case id. 

### ISSUE THREAD

**Issue by Ashish3080** [process-intelligence-solutions/pm4py#458]
I created a demo process flow diagram using dfg_visualizer but it is not detecting the starting activity and the final activity. As per my flow the correct **starting activity** should be '**open filezilla**' and the correct **final activity** should be **close filezilla**.  I am using correlation miner as my log file does not has case id associated with the tasks
<img width="713" alt="Screenshot 2023-12-06 185811" src="https://github.com/pm4py/pm4py-core/assets/135946854/282d64af-c547-4152-9f9f-ac74a3620f93">

**Comment by fit-alessandro-berti** [comment]
Dear @Ashish3080 

For the correlation mining, you should manually provide the start/end activities as this is not detected by the method.

You can use the method pm4py.view_dfg(dfg, sa, ea) where:
- dfg is the directly-follows graph obtained using the correlation mining technique
- sa is a dictionary of start activities that you manually provide (you can associate the frequency 1 to all the expected start activities)
- ea is a dictionary of end activities that you manually provide (you can associate the frequency 1 to all the expected start activities)

The correlation mining technique could add arcs between end and start activities. Given the provided start/end activities, be sure that you remove them beforehand.
