### ISSUE TITLE
pm4py.write.write_bpmn(...) produces invalid BPMN schema

### ISSUE THREAD

**Issue by EmmArrGee** [process-intelligence-solutions/pm4py#459]
pm4py.write.write_bpmn(...) produces XML files with an invalid schema. The following issues have been found:

1.  Gateway nodes (_exclusiveGateway_, _parallelGateway_, ...) have an attribute _gatewayDirection_ that is one of _converging_, _diverging_, etc. According to [https://www.omg.org/spec/BPMN/2.0/PDF, chapter 8.3.9, page 121, table 8.46](https://www.omg.org/spec/BPMN/2.0/PDF) this attribute's value should be one of _Unspecified_, _Converging_, _Diverging_, _Mixed_ (note the capital letters in the beginning).

2. Although I did not find a source for this claim in the before referenced BPMN specifications, it seems that some BPMN schema validators expect the _bpmn:process_ node to be found **before** all other nodes (e.g. the _bpmndi:BPMNDiagram_ node).

**Comment by fit-alessandro-berti** [comment]
Dear @EmmArrGee 

Thanks for signaling. We will fix this issues in our next release.

Cheers
Alessandro

**Comment by EmmArrGee** [comment]
Thanks a lot! :)
