### ISSUE TITLE
GPU-based process mining

### ISSUE THREAD

**Issue by JaydanPB** [process-intelligence-solutions/pm4py#464]
Hi,

We have been trying to reduce the time it takes our process mining script to run. 
Having read the `PM4Py-GPU: a High-Performance General-Purpose Library for Process Mining` paper we now believe that that the performance is limited by it being single-threaded. I would appreciate if you could help me with two questions:

- Am I correct in thinking pm4py-core is limited by single CPU core performance?
- What is the status of integrating GPU / CUDF acceleration into this codebase? I have looked at the `Javert899/pm4pygpu` project but it seems to be a bit outdated now. 

Thanks!

**Comment by fit-alessandro-berti** [comment]
Dear @JaydanPB 

We integrated CuDF support in pm4py, that is used automatically when CUDA and the NVIDIA Rapids framework is installed.

In this way, every operation in pm4py is executed on top of the CUDA dataframes of possible. This does not required any effort from the final user

**Comment by fit-alessandro-berti** [comment]
By the way, the original pm4py-gpu project is now unmaintained, because GPU support has been directly added to the main pm4py as in the previous post

**Comment by JaydanPB** [comment]
Ah, brilliant. Thanks for the help.
