### ISSUE TITLE
Missing PEP 561-compliancy

### ISSUE THREAD

**Issue by aaronkurz** [process-intelligence-solutions/pm4py#470]
Due to missing type hints (e.g. with a `py.typed` file), usage of the library together with type checkers results in issues. For example, mypy flags `"pm4py": module is installed, but missing library stubs or py.typed marker  [import-untyped]`.

More info:
- [PEP 561](https://peps.python.org/pep-0561/)
- [mypy docs](https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker)

**Comment by fit-alessandro-berti** [comment]
Dear @aaronkurz 

That is true. However, we do not plan to address the issue in the short term
