### ISSUE TITLE
OCDFG: Visualization issue when having only one activity to show

### ISSUE THREAD

**Issue by solterbeck** [process-intelligence-solutions/pm4py#473]
Dear PM4PY Guys,

thanks for your extraordinary work. I have a question or an issue, I don't really know.

When I run the following script:
```
import pm4py

selections2 = {'Container': ['Order Empty Containers', 'Pick Up Empty Container']}
selections1 = {'Container': ['Order Empty Containers']}

# Source of OCEL 2.0: https://zenodo.org/records/8428084
ocel = pm4py.read_ocel2_json('input/ContainerLogistics.json')

ocel_selected1 = pm4py.filter_ocel_object_types_allowed_activities(ocel, selections1)
ocdfg= pm4py.discover_ocdfg(ocel_selected1)
pm4py.save_vis_ocdfg(ocdfg, 'output/graph_selection1.png', rankdir='TB')

ocel_selected2 = pm4py.filter_ocel_object_types_allowed_activities(ocel, selections2)
ocdfg= pm4py.discover_ocdfg(ocel_selected2)
pm4py.save_vis_ocdfg(ocdfg, 'output/graph_selection2.png', rankdir='TB')

ocpn = pm4py.discover_oc_petri_net(ocel_selected1)
pm4py.save_vis_ocpn(ocpn, 'output/ocpn_selection1.png', rankdir='TB')
```
Don't ask me why I'm doing this ;-) 

- After filtering with two activities I will get a filtered OCDFG with the oval label for "Container" and the appropriate underlined label.
![graph_selection2](https://github.com/pm4py/pm4py-core/assets/16978779/369228da-9a94-419b-9f7f-9ee89d8ba06b)
- But when I filter only one activity no labels will be shown in the OCDFG.
![graph_selection1](https://github.com/pm4py/pm4py-core/assets/16978779/bbbff1d1-10d8-4e6c-a72d-18ff71544fa9)
- Nevertheless showing the one activty OCPN, then I will see the labels. 
![ocpn_selection1](https://github.com/pm4py/pm4py-core/assets/16978779/f16fc025-be21-4db2-8eb1-eeea15973909)

I'm feeling not confortable, when one activity shall be shown in the OCDFG. I would be grateful, if you could put a light on my issue. But at the end I would like to have s.th. like an "Activity - OT (manual)" filter, as you have it in OC-PM (which I like also very much).

Cheers, Sven

**Comment by fit-alessandro-berti** [comment]
Dear @solterbeck 

Thank for signaling. We'll release a fix for this issue
