### ISSUE TITLE
Duplicated sequence from activity to Exclusive Gateway in BPMN visualization

### ISSUE THREAD

**Issue by jacaballero** [process-intelligence-solutions/pm4py#475]
Hi all,

I don't know if this is a problem with the library or if it is accepted in BPMN models, but I have been working for a long time with other frameworks such as ProM, and it's the first time that I found it.

I'm importing a CSV log to show its BPMN model. When I apply a significant noise_threshold (i.e. 0.20), a duplicated sequence with two exclusive gateways is shown as appears in the image below:

<img width="377" alt="screenshot" src="https://github.com/pm4py/pm4py-core/assets/5695488/31bfbc07-9b26-480d-8ffc-548553c5d67a">

The function where I create and save the BPMN is very simple, it is included below:

```
# BPMN: Discover and save model
def get_bpmn(filtered_log, file_name):
    noise_threshold = 0.0
    noise_threshold = float(input("Insert the ratio (0-100) to filter infrequent paths: "))
    bpmn_model = pm4py.discover_bpmn_inductive(filtered_log, noise_threshold/100)
    pm4py.save_vis_bpmn(bpmn_model, file_name)
```

When I get the BPMN model without filtering infrequent paths (or with scarce filters as 0.01), this doesn't happen.

Could you help me with this, please?

Thanks

**Comment by fit-alessandro-berti** [comment]
Dear @jacaballero 

It's not technically wrong, but we'll have a look to avoid these double arcs in the conversion

**Comment by jacaballero** [comment]
Dear @fit-alessandro-berti 

That's great.

Thank you for your quick response.

**Comment by fit-alessandro-berti** [comment]
By the way, could you attach a small example log where this happens?

Cheers

**Comment by jacaballero** [comment]
The log that I'm using has 240000 lines in XES format. I'll try to test if with a sample of the traces it happens as well.

**Comment by jacaballero** [comment]
Dear @fit-alessandro-berti 

I attached a CSV sample of where this happens. I loaded it as below:

log = pm4py.format_dataframe(pandas.read_csv('filtered_file.csv', sep=';'), case_id='case_id',activity_key='concept:name', timestamp_key='time:timestamp')

And then applied the function that I included in a previous comment.

Hope this helps to debug it.

Regards

[filtered_file.csv](https://github.com/pm4py/pm4py-core/files/14613412/filtered_file.csv)

**Comment by fit-alessandro-berti** [comment]
Thanks, we identified and resolved the issue :-)

**Comment by jacaballero** [comment]
I checked the last version and now it works. Thank you!!
