### ISSUE TITLE
Convert_to_process_tree not working

### ISSUE THREAD

**Issue by DriesJarijch** [process-intelligence-solutions/pm4py#476]
[pn to pt.zip](https://github.com/pm4py/pm4py-core/files/14761021/pn.to.pt.zip)

Using this file, I was hoping to generate a process tree from the petrinets provided. My output is stored in the ptrees file. They don't seem to convert correctly.

Thank you in advance

**Comment by fit-alessandro-berti** [comment]
Dear @DriesJarijch 

The conversion works without problems on 1.pnml, 2.pnml and test_im.pnml (which are block-structured)

For test_bm.pnml, it does not work because the Petri net is not block structured (the algorithm works only for that class of Petri nets).

**Comment by fit-alessandro-berti** [comment]
Errata corrige: it is indeed block-structured. We will work to fix this issue

**Comment by fit-alessandro-berti** [comment]
We resolved the problems, and obtain the following process trees:

1.pnml:
![1](https://github.com/pm4py/pm4py-core/assets/56342194/f67d1ebc-dde5-4af5-909a-1a470aecfbd2)

2.pnml:
![2](https://github.com/pm4py/pm4py-core/assets/56342194/7f109cdc-cda2-44a5-a654-0c5f875b94bc)

test_im.pnml:
![test_im](https://github.com/pm4py/pm4py-core/assets/56342194/5492e805-fa38-410a-a845-ebdea79e2a29)

test_bm.pnml:
![test_bm](https://github.com/pm4py/pm4py-core/assets/56342194/9448fcb3-8dee-4c8a-988b-2e24b913a3bc)
