### ISSUE TITLE
Getting a False soundness result for the simplest BPMN model

### ISSUE THREAD

**Issue by DigitalGabriele** [process-intelligence-solutions/pm4py#484]
I am running a soundness check on a simple BPMN model, by running the following code:

```
import pm4py
bpmn_path = "diagram_5.bpmn"
net, initial_marking, final_marking = pm4py.read_pnml(bpmn_path)
is_sound = pm4py.check_soundness(net, initial_marking, final_marking)
```

The printed result for `is_sound`:

```
(False,
 {<Outputs.DIAGNOSTIC_MESSAGES: 'diagnostic_messages'>: ['There is more than one initial or final marking.']})
```

The BPMN looks like:

<img width="334" alt="Screenshot 2024-05-04 at 12 55 25" src="https://github.com/pm4py/pm4py-core/assets/5788396/f5b5117c-2d9a-49ce-8f51-080f0161a923">

What am I doing wrong?

**Comment by fit-alessandro-berti** [comment]
Dear @DigitalGabriele 

You should read the BPMN using pm4py.read_bpmn and convert it later to Petri net using pm4py.convert_to_petri_net

**Comment by DigitalGabriele** [comment]
Thanks!
