### ISSUE TITLE
petrinet to bpmn

### ISSUE THREAD

**Issue by Dehghanpour1990** [process-intelligence-solutions/pm4py#487]
Hi, I have a code generating a Petri net as a dictionary. Now I want to convert it to a BPMN file and save it as .bpmn. How can I do it?

**Comment by fit-alessandro-berti** [comment]
Dear @Dehghanpour1990 

You can use the commands:

import pm4py

bpmn_graph = pm4py.convert_to_bpmn(net, initial_marking, final_marking)
pm4py.write_bpmn(bpmn_graph, "output.bpmn")

**Comment by Dehghanpour1990** [comment]
Dear @fit-alessandro-berti,
Thank you for your reply. Your suggestion is for when we get a Petri_net from a discovery method using the PM4PY library right? 
I have written a code generating Petri_net based on directly-follow-graph and want to convert it into a .bpmn file which will be used in another software.

**Comment by fit-alessandro-berti** [comment]
Yes, any Petri net object in pm4py

**Comment by Dehghanpour1990** [comment]
@fit-alessandro-berti 
The problem is I have my code developing a discovery algorithm from scratch and the output is not a Petri net object in pm4py, just a Petri net as a dictionary. How can I convert this dictionary to a BPMN file?
