### ISSUE TITLE
SSL Down PM4PY.FIT.FRAUNHOFER.DE website

### ISSUE THREAD

**Issue by masterivanic** [process-intelligence-solutions/pm4py#488]
The official [website documentation](https://pm4py.fit.fraunhofer.de/) ssl is down :), it's now unsecure. 
This was firstly secure before.

**Comment by skwashd** [comment]
I opened an issue reporting the expired certificate weeks ago. #483 was closed without the cert being updated. My followup comment went unanswered.

**Comment by fit-alessandro-berti** [comment]
Dear all,

We managed to complete the update of the certificate of the website
