### ISSUE TITLE
images are not shown in browser

### ISSUE THREAD

**Issue by vddo** [process-intelligence-solutions/pm4py#490]
Hi, in the documentations, chapter getting started, are two png's that are not rendered in my browser at least. 
https://pm4py.fit.fraunhofer.de/static/assets/api/2.7.11/getting_started.html
- bpmn_running_example.png
- csv_snapshot.png
Wanted to let you folks know.

**Comment by fit-alessandro-berti** [comment]
Dear @vddo 

Thanks for signaling. We will come back soon with a solution of the problem.

**Comment by fit-alessandro-berti** [comment]
Dear @vddo 

We fixed the issue
