### ISSUE TITLE
In Docs > getting started: import_csv()

### ISSUE THREAD

**Issue by vddo** [process-intelligence-solutions/pm4py#491]
Hi, I have a question regarding the import_csv function in `Getting started > Importing your first event log > Loading csv files`. 
```python 
def import_csv(file_path):
    event_log = pandas.read_csv(file_path, sep=';')
    num_events = len(event_log)
    num_cases = len(event_log.case_id.unique())
    print("Number of events: {}\nNumber of cases: {}".format(num_events, num_cases))
```
In line 4 (`num_cases`) how can `case_id` be an attribute of `pandas.DataFrame`? Maybe it should look like this:
```python
   num_cases = len(event_log['case_id'].unique())
```

**Comment by fit-alessandro-berti** [comment]
Dear @vddo 

If the name of the column does not contain strange characters, like in the mentioned situation, then dataframe.case_id is equivalent to dataframe["case_id"]
