### ISSUE TITLE
Official Docker image lacks version tagging

### ISSUE THREAD

**Issue by andrewparsons-janus** [process-intelligence-solutions/pm4py#495]
The Docker image defined [here](https://github.com/pm4py/pm4py-core/blob/release/Dockerfile) and distributed on [Docker Hub](https://hub.docker.com/r/pm4py/pm4py-core/tags) lacks version tagging.

As a developer, I wish to pin an image requirement to, for example, `2.7.11`.

In other words, not this...

```dockerfile
# my custom Dockerfile for a production application

FROM pm4py/pm4py-core:latest
```

...but rather this:

```dockerfile
# my custom Dockerfile for a production application

FROM pm4py/pm4py-core:2.7.11
```

Pinning a Docker image tag is crucial to ensure that an application always uses the same environment, libraries, and dependencies. This prevents unexpected changes due to updates or new releases.

**Comment by fit-alessandro-berti** [comment]
Dear @andrew-parsons-janus 

Thanks for requesting. We pushed pm4py/pm4py-core:2.7.11 to the docker hub, and that will remain 'stable'
