### ISSUE TITLE
Many new changes in release branch are missing

### ISSUE THREAD

**Issue by Deepan-mn** [process-intelligence-solutions/pm4py#498]
Many functionality in `release branch` is not available
My pm4py library is `pm4py==2.2.23`
Example 
I need to use , `pm4py/algo/transformation/log_to_target/variants/next_activity.py`

**Comment by fit-alessandro-berti** [comment]
Dear @Deepan-mn 

The current release of pm4py is 2.7.11.12  and many old features are renamed / removed. Please consult only the documentation provided at: https://processintelligence.solutions/static/api/2.7.11/index.html
