### ISSUE TITLE
Cannot visualise DFG

### ISSUE THREAD

**Issue by mapto** [process-intelligence-solutions/pm4py#503]
First of all thanks for your contributions with this project. 

I'm new to pm4py, I tried visualising a simple DirectlyFollowsGraph using this simple code:
```python
log = pd.read_csv("log.csv")
params = {
    "log":log,
    "case_id_key": "book",
    "activity_key":"activity",
    "timestamp_key": "date",
}
dfg = pp.discover_dfg(**params)
dfg
pp.view_dfg(dfg,
    start_activities=pp.get_start_activities(**params),
    end_activities=pp.get_end_activities(**params)
)
```
This resulted in an exception:
```
KeyError                                  Traceback (most recent call last)
...
File ~/.local/lib/python3.10/site-packages/pm4py/objects/dfg/utils/dfg_utils.py:236, in get_activities_from_dfg(dfg)
    225 set_activities = set()
    226 for el in dfg:
--> 227     if type(el[0]) is str:
    228         assert type(el) == tuple, f"type of {el} is {type(el)}, not tuple"
    229         set_activities.add(el[0])

KeyError: 0
```

I investigated this and managed to come up with a patch, but made me suspect a wider issue. In this code:
https://github.com/pm4py/pm4py-core/blob/48b2d02d4d42d8cc9dc6dfccf479fc2fb5225211/pm4py/objects/dfg/obj.py#L52
the `__iter__(self)` method puts together three structures with apparently different types. In particular while `self.graph` is of the type `Counter[tuple[str,str],int]`, `self.start_activities` and `self.end_activities` are of type `Counter[str,int]`. This leads to the need to distinguish cases each time one iterates over dfg (e.g. with a for loop). If this assessment of mine is correct, this leads to a huge overhead that I'd suggest could be avoided. I can think of two possible solutions:

1. Introduce dummy `\{start}` and `\{end}` nodes and convert `self.start_activities` and `self.end_activities` above in structures with the same signature/type as `self.graph`. This would have the downside that any code that iterates over the graph needs to be aware of the presence of these dummy nodes and handle them as special cases.

2. Exclude `self.start_activities` and `self.end_activities` from the results of `__iter__(self)`, which would produce a realistic total edge count, but would require special treatment of start and end nodes.

Depending on the scope of this (and I am afraid this might be huge), I am willing to implement this solution as a pull request, but I would appreciate any guidance on which approach might be more inline with the overall vision of pm4py.

Thanks!
Martin

**Comment by fit-alessandro-berti** [comment]
Dear @mapto 

Please try with the following two lines of code, as the method returns the DFG plus the start activities plus the end activities

dfg, sa, ea = pp.discover_dfg(**params)
pp.view_dfg(dfg, sa, ea, format="svg")

**Comment by mapto** [comment]
Thank you. Does not respond to my issue with `__iter__(self)`, but useful anyway.
