### ISSUE TITLE
Question about Fitness Alignments value, when having silent transition on Petri Net

### ISSUE THREAD

**Issue by denisesato** [process-intelligence-solutions/pm4py#510]
I have created a simple event log with one loop activity (activity C).
I have discovered the Petri net using the inductive miner algorithm, which includes a silent transition to represent the loop.

Then, I executed the fitness_alignments method using the same log and the discovered Petri net. I expected all the traces to align with cost 0, resulting in a fitness=1. However, every time the silent transition is reached, a move in model is counted (however is an invisible move on model), as detailed in the conformance diagnostics. Based on the book "Process Mining - Data Science in Action" authored by van der Aalst, I understand that "Moves in model only have no costs if the transition is invisible, i.e., δ($,(τ,t)) = 0 for invisible model moves" (page 259).

{'alignment': [('A', 'A'), ('B', 'B'), ('C', 'C'), ('>>', None), ('C', 'C'), ('>>', None), ('C', 'C'), ('D', 'D'), ('E', 'E')], 'cost': 2, 'visited_states': 9, 'queued_states': 26, 'traversed_arcs': 28, 'lp_solved': 1, 'fitness': 1.0, 'bwc': 120000}

The resulting fitness is 0.9999889830508475. Is this correct? Should the silent transition be costed as a move on the model?

I appreciate it if someone could clarify this to me. Maybe I have a wrong understanding of the fitness metric based on alignments.

![petrinet](https://github.com/user-attachments/assets/0a0e7c4e-20ca-44bc-9e4e-9e8eaa562a2f)

[ExemploLoops1.xes.gz](https://github.com/user-attachments/files/17940087/ExemploLoops1.xes.gz)

```
import pandas
import pm4py

def fitness(file_path):
    df = pm4py.format_dataframe(pandas.read_csv(file_path, sep=";"), case_id="case_id", activity_key="activity",
                                       timestamp_key="timestamp")
    pn, im, fm = pm4py.discover_petri_net_inductive(df)
    pm4py.save_vis_petri_net(pn, im, fm, "data/output/petrinet.png")
    fitness_tbr = pm4py.fitness_token_based_replay(df, pn, im, fm)
    print(f"Fitness token-based replay: {fitness_tbr}")

    fitness_alignments = pm4py.fitness_alignments(df, pn, im, fm)
    print(f"Fitness alignments: {fitness_alignments}")
    conformance_diagnostics_alignments = pm4py.conformance_diagnostics_alignments(df, pn, im, fm)
    print(f"Conformance diagnostics alignments:")
    for c in conformance_diagnostics_alignments:
        print(f"{c}")

    fitness_footprints = pm4py.fitness_footprints(df, pn, im, fm)
    print(f"Fitness footprints: {fitness_footprints}")


if __name__ == "__main__":
    log_path = "data/ExemploLoops1.csv"
    fitness(log_path)
```

**Comment by fit-alessandro-berti** [comment]
Dear @denisesato,

Yes, the fitness computation works as you found out (since in the cost function, we kept 1 for the move-on-model related to invisible transitions, and 10,000 for the other move-on-model and move-on-log). I suggest to use the round(value, N) to round the number with the given precision

**Comment by denisesato** [comment]
Dear Alessandro,

Thanks for the response. Just one more question. Is it possible to change the value of the cost function associated to the invisible transition moves from 1 to 0 in pm4py? I am investigating some processes with a lot of loops and I would like to avoid reducing the fitness value (even a little) on this situation. Thanks in advance.

Kind regards,
Denise

**Comment by fit-alessandro-berti** [comment]
Dear @denisesato 

Yes. See https://github.com/pm4py/pm4py-core/blob/release/examples/alignment_test.py for an example

However, it should also be noted, the cost equal to 1 was to "cover" exactly that case, in which models have lots of loops. Expect alignments to become slightly lower with the provided cost function

**Comment by denisesato** [comment]
Thanks!
