### ISSUE TITLE
Add perf_aggregation_key parameter to discover_performance_dfg method

### ISSUE THREAD

**Issue by OverLeo007** [process-intelligence-solutions/pm4py#512]
#### Problem

Currently, the [`discover_performance_dfg`](https://github.com/pm4py/pm4py-core/blob/c724aa53d5a7de507e99c10e667868f37b6a5b8f/pm4py/discovery.py#L157) method does not allow specifying the `perf_aggregation_key` parameter.  
However, the [`get_dfg_graph`](https://github.com/pm4py/pm4py-core/blob/c724aa53d5a7de507e99c10e667868f37b6a5b8f/pm4py/algo/discovery/dfg/adapters/pandas/df_statistics.py#L26) method, which is called inside `discover_performance_dfg`, already supports this parameter.  
In the current implementation, `discover_performance_dfg` always passes `"all"` as the value for `perf_aggregation_key`, which makes it impossible to use alternative aggregation keys without modifying the resulting graph manually.

#### Proposal

Add the `perf_aggregation_key` parameter to the signature of the `discover_performance_dfg` method and pass it to the `get_dfg_graph` call.  
The default value of this parameter can be `"all"` to preserve the current behavior.

#### Suggested Changes

In the [`pm4py/discovery.py`](https://github.com/pm4py/pm4py-core/blob/c724aa53d5a7de507e99c10e667868f37b6a5b8f/pm4py/discovery.py#L157) file, update the `discover_performance_dfg` method as follows:

```python
def discover_performance_dfg(...other_args, perf_aggregation_key: str = "all"):
    # ...
    dfg = get_dfg_graph(...other_args, perf_aggregation_key=perf_aggregation_key, ...other_args)
    # ...

**Comment by OverLeo007** [comment]
I noticed that for the implementation of the graph visualization methods, it needs to have all aggregation_measure, however, I would like to have an easy way to convert the resulting graph without resorting to using `{k: v for k, v in map(lambda kv: (kv[0], kv[1]["mean"]), perf_dfg.items())}`.  (It took a while to get it working due to a silly error 😅)

**Comment by fit-alessandro-berti** [comment]
Dear @OverLeo007 thanks for the suggestion. We will consider that for a future release. Cheers
